repos:
  - repo: local
    hooks:
      - id: cargo-test
        name: cargo test
        entry: cargo test --all
        language: system
        stages: [commit]
        pass_filenames: false
        always_run: true

      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all
        language: system
        stages: [commit]
        pass_filenames: false
        always_run: true

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all -- -D warnings
        language: system
        stages: [commit]
        pass_filenames: false
        always_run: true
