//! Minimal HTML5 writer.
//!
//! Produces a small, predictable subset of `docutils.writers.html5_polyglot`
//! output suitable for downstream consumers that just need semantic HTML
//! for the supported node kinds. This is intentionally not a parity
//! gate; see `docs/compat.md` for the accepted-deviation note.
//!
//! Output is a fragment (no `<html>`/`<head>`/`<body>` envelope).

use crate::doctree::{Doctree, Node, NodeId, NodeKind};
use std::fmt::Write as _;

pub fn html5(
    tree: &Doctree,
    options: &crate::cli::Html5Options,
    common: &crate::cli::CommonOptions,
) -> String {
    let mut out = String::new();
    let root = tree.root();
    let mut tasks: Vec<Task> = Vec::new();
    for &c in tree.node(root).children.iter().rev() {
        tasks.push(Task::Enter(c));
    }
    while let Some(task) = tasks.pop() {
        match task {
            Task::Append(s) => out.push_str(&s),
            Task::Enter(id) => emit_enter(tree, id, &mut out, options, &mut tasks),
        }
    }

    // Add generator / date string to end of document
    let include_generator = common.no_generator.is_none() && common.generator.is_some();
    let datestamp = get_datestamp(common);
    if include_generator || datestamp.is_some() {
        if include_generator {
            out.push_str("Generated by <a href=\"https://docutils.sourceforge.io/\">Docutils</a> from <a href=\"https://docutils.sourceforge.io/rst.html\">reStructuredText</a> source.");
        }
        if let Some(date_str) = datestamp {
            if include_generator {
                out.push('\n');
            }
            out.push_str("Generated on: ");
            out.push_str(&escape(&date_str));
            out.push('.');
        }
    }

    out
}

enum Task {
    Enter(NodeId),
    Append(String),
}

/// Schedule `node`'s children (in document order) followed by `close`,
/// applied after any tasks already on the stack. Since `tasks` is a LIFO
/// stack, `close` is pushed first so it ends up underneath (and
/// therefore runs after) the children.
fn schedule(node: &Node, close: impl Into<String>, tasks: &mut Vec<Task>) {
    tasks.push(Task::Append(close.into()));
    for &c in node.children.iter().rev() {
        tasks.push(Task::Enter(c));
    }
}

fn wrap(node: &Node, tag: &str, out: &mut String, tasks: &mut Vec<Task>) {
    let _ = write!(out, "<{tag}>");
    schedule(node, format!("</{tag}>"), tasks);
}

fn wrap_with_class(node: &Node, tag: &str, class: &str, out: &mut String, tasks: &mut Vec<Task>) {
    let _ = write!(out, "<{tag} class=\"{class}\">");
    schedule(node, format!("</{tag}>"), tasks);
}

/// Write `id`'s own opening markup (if any) immediately to `out`, then
/// schedule its closing markup and children as `tasks` rather than
/// recursing — see the module doc comment.
fn emit_enter(
    tree: &Doctree,
    id: NodeId,
    out: &mut String,
    options: &crate::cli::Html5Options,
    tasks: &mut Vec<Task>,
) {
    let node = tree.node(id);
    match &node.kind {
        NodeKind::Text(s) => out.push_str(&escape(s)),
        NodeKind::Document { .. } => {
            for &c in node.children.iter().rev() {
                tasks.push(Task::Enter(c));
            }
        }
        NodeKind::Section { ids, .. } => {
            let _ = write!(out, "<section id=\"{ids}\">");
            schedule(node, "</section>", tasks);
        }
        NodeKind::Title => {
            // Heading level is determined by ancestor section depth; we
            // approximate as `<h1>` and rely on CSS for visual depth.
            wrap(node, "h1", out, tasks);
        }
        NodeKind::Subtitle { .. } => wrap_with_class(node, "p", "subtitle", out, tasks),
        NodeKind::Transition => out.push_str("<hr/>"),
        NodeKind::Paragraph => wrap(node, "p", out, tasks),
        NodeKind::Emphasis => wrap(node, "em", out, tasks),
        NodeKind::Strong => wrap(node, "strong", out, tasks),
        NodeKind::Literal => wrap(node, "code", out, tasks),
        NodeKind::TitleReference => wrap(node, "cite", out, tasks),
        NodeKind::Inline { classes } => {
            if classes.is_empty() {
                out.push_str("<span>");
            } else {
                let _ = write!(out, "<span class=\"{classes}\">");
            }
            schedule(node, "</span>", tasks);
        }
        NodeKind::LiteralBlock { classes } => {
            if classes.is_empty() {
                out.push_str("<pre>");
            } else {
                let _ = write!(out, "<pre class=\"{classes}\">");
            }
            schedule(node, "</pre>", tasks);
        }
        NodeKind::BulletList { .. } => {
            if is_compactable(tree, id, options, false) {
                wrap_with_class(node, "ul", "simple", out, tasks)
            } else {
                wrap(node, "ul", out, tasks)
            }
        }
        NodeKind::EnumeratedList { .. } => {
            if is_compactable(tree, id, options, false) {
                wrap_with_class(node, "ol", "simple", out, tasks)
            } else {
                wrap(node, "ol", out, tasks)
            }
        }
        NodeKind::ListItem => wrap(node, "li", out, tasks),
        NodeKind::DefinitionList => {
            if is_compactable(tree, id, options, false) {
                wrap_with_class(node, "dl", "simple", out, tasks)
            } else {
                wrap(node, "dl", out, tasks)
            }
        }
        NodeKind::DefinitionListItem => {
            for &c in node.children.iter().rev() {
                tasks.push(Task::Enter(c));
            }
        }
        NodeKind::Term => wrap(node, "dt", out, tasks),
        NodeKind::Classifier => wrap_with_class(node, "span", "classifier", out, tasks),
        NodeKind::Definition => wrap(node, "dd", out, tasks),
        NodeKind::FieldList => {
            if is_compactable(tree, id, options, true) {
                wrap_with_class(node, "dl", "field-list simple", out, tasks)
            } else {
                wrap_with_class(node, "dl", "field-list", out, tasks)
            }
        }
        NodeKind::Field => {
            for &c in node.children.iter().rev() {
                tasks.push(Task::Enter(c));
            }
        }
        NodeKind::FieldName => wrap(node, "dt", out, tasks),
        NodeKind::FieldBody => wrap(node, "dd", out, tasks),
        NodeKind::Docinfo => wrap(node, "dl", out, tasks),
        NodeKind::Bibliographic { tag } => {
            let _ = write!(out, "<dt>{tag}</dt><dd>");
            schedule(node, "</dd>", tasks);
        }
        NodeKind::BlockQuote => wrap(node, "blockquote", out, tasks),
        NodeKind::Admonition { kind } => {
            // Mirrors docutils' HTML5 writer: a fixed-kind admonition
            // (`.. note::`, `.. seealso::`, ...) renders as
            // `<div class="admonition {kind}"><p class="admonition-title">
            // {Title}</p>{body}</div>` — real Sphinx builds never use
            // `<aside>` for these.
            let title = match *kind {
                "seealso" => "See also",
                "note" => "Note",
                "warning" => "Warning",
                "tip" => "Tip",
                "hint" => "Hint",
                "important" => "Important",
                "attention" => "Attention",
                "caution" => "Caution",
                "danger" => "Danger",
                "error" => "Error",
                _ => kind,
            };
            let _ = write!(out, "<div class=\"admonition {kind}\">");
            let _ = write!(out, "<p class=\"admonition-title\">{}</p>", escape(title));
            schedule(node, "</div>", tasks);
        }
        NodeKind::Container { classes } => {
            // `.. container:: classes` — real docutils/Sphinx markup:
            // `<div class="{classes} docutils container">`.
            if classes.is_empty() {
                out.push_str("<div class=\"docutils container\">");
            } else {
                let _ = write!(out, "<div class=\"{classes} docutils container\">");
            }
            schedule(node, "</div>", tasks);
        }
        NodeKind::GenericAdmonition { title, classes } => {
            // `.. admonition:: Title` (optionally `:class: extra`) — real
            // markup reverses the class order vs. fixed-kind admonitions:
            // `<div class="{classes or 'admonition'} admonition">`.
            if classes.is_empty() {
                out.push_str("<div class=\"admonition\">");
            } else {
                let _ = write!(out, "<div class=\"{classes} admonition\">");
            }
            let _ = write!(out, "<p class=\"admonition-title\">{}</p>", escape(title));
            schedule(node, "</div>", tasks);
        }
        NodeKind::Epigraph { classes } => {
            if classes.is_empty() {
                out.push_str("<blockquote class=\"epigraph\">");
            } else {
                let _ = write!(out, "<blockquote class=\"epigraph {classes}\">");
            }
            schedule(node, "</blockquote>", tasks);
        }
        NodeKind::Toctree { .. } => {
            // Standalone docutilsrs has no notion of a multi-document
            // project to expand this into; `sphinxdocrs` resolves it
            // into a real subtree before this writer ever sees it (see
            // `BuildEnvironment::resolve_toctree_nodes`). Renders nothing
            // here, matching a `:hidden:` toctree's real behavior.
        }
        NodeKind::Image { uri, alt, .. } => {
            let _ = write!(out, "<img src=\"{}\"", escape(uri));
            if let Some(a) = alt {
                let _ = write!(out, " alt=\"{}\"", escape(a));
            }
            out.push_str("/>");
        }
        NodeKind::Raw { format } => {
            if format == "html" {
                // Raw HTML passes through.
                for &c in &node.children {
                    if let NodeKind::Text(s) = &tree.node(c).kind {
                        out.push_str(s);
                    }
                }
            }
        }
        NodeKind::Math { latex } => {
            let backend = get_math_backend(options);
            out.push_str(&mathrenderrs::render(
                backend,
                mathrenderrs::MathDisplay::Inline,
                latex,
            ));
        }
        NodeKind::MathBlock { latex } => {
            let backend = get_math_backend(options);
            out.push_str(&mathrenderrs::render(
                backend,
                mathrenderrs::MathDisplay::Block,
                latex,
            ));
        }
        NodeKind::Comment => {
            out.push_str("<!-- ");
            for &c in &node.children {
                if let NodeKind::Text(s) = &tree.node(c).kind {
                    out.push_str(&escape(s));
                }
            }
            out.push_str(" -->");
        }
        NodeKind::Reference {
            refuri, classes, ..
        } => {
            let is_mailto = refuri.starts_with("mailto:");
            let should_cloak = is_mailto && options.cloak_email_addresses.is_some();
            let mut uri = escape(refuri);
            if should_cloak {
                uri = uri.replace("@", "&#37;&#52;&#48;").replace(".", "&#46;");
            }
            if classes.is_empty() {
                let _ = write!(out, "<a href=\"{}\">", uri);
            } else {
                let _ = write!(out, "<a class=\"{}\" href=\"{}\">", escape(classes), uri);
            }
            tasks.push(Task::Append("</a>".to_string()));
            for &c in node.children.iter().rev() {
                if should_cloak {
                    if let NodeKind::Text(s) = &tree.node(c).kind {
                        let mut cloaked = escape(s);
                        cloaked = cloaked.replace("@", "&#64;").replace(".", "&#46;");
                        tasks.push(Task::Append(cloaked));
                        continue;
                    }
                }
                tasks.push(Task::Enter(c));
            }
        }
        NodeKind::Target { .. } => {}
        NodeKind::SubstitutionDefinition { .. } => {}
        NodeKind::SubstitutionReference { refname } => {
            let _ = write!(out, "{}", escape(refname));
        }
        NodeKind::Table => {
            let mut classes = vec![];
            if let Some(style) = &options.table_style {
                classes.extend(style.split(',').map(|s| s.trim()).filter(|s| !s.is_empty()));
            }
            if classes.is_empty() {
                wrap(node, "table", out, tasks)
            } else {
                let _ = write!(out, "<table class=\"{}\">", classes.join(" "));
                schedule(node, "</table>", tasks);
            }
        }
        NodeKind::Tgroup { .. } => {
            for &c in node.children.iter().rev() {
                tasks.push(Task::Enter(c));
            }
        }
        NodeKind::Colspec { .. } => {}
        NodeKind::Thead => wrap(node, "thead", out, tasks),
        NodeKind::Tbody => wrap(node, "tbody", out, tasks),
        NodeKind::Row => wrap(node, "tr", out, tasks),
        NodeKind::Entry { morecols, morerows } => {
            let mut tag = String::from("<td");
            if *morecols > 0 {
                let _ = write!(tag, " colspan=\"{}\"", morecols + 1);
            }
            if *morerows > 0 {
                let _ = write!(tag, " rowspan=\"{}\"", morerows + 1);
            }
            tag.push('>');
            out.push_str(&tag);
            schedule(node, "</td>", tasks);
        }
        NodeKind::Attribution => {
            out.push_str("<p class=\"attribution\">— ");
            schedule(node, "</p>", tasks);
        }
        NodeKind::Figure => wrap(node, "figure", out, tasks),
        NodeKind::Caption => wrap(node, "figcaption", out, tasks),
        NodeKind::Legend => wrap_with_class(node, "div", "legend", out, tasks),
        NodeKind::Label => wrap_with_class(node, "span", "label", out, tasks),
        NodeKind::Footnote { ids, .. } => {
            let _ = write!(out, "<aside class=\"footnote\" id=\"{ids}\">");
            schedule(node, "</aside>", tasks);
        }
        NodeKind::FootnoteReference { refid, .. } => {
            let style = options.footnote_references.as_deref().unwrap_or("brackets");
            let _ = write!(
                out,
                "<a class=\"{style}\" href=\"#{refid}\" id=\"footnote-reference-1\" role=\"doc-noteref\">"
            );
            if style == "brackets" {
                out.push_str("<span class=\"fn-bracket\">[</span>");
                schedule(node, "<span class=\"fn-bracket\">]</span></a>", tasks);
            } else {
                schedule(node, "</a>", tasks);
            }
        }
        NodeKind::Citation { ids, .. } => {
            let _ = write!(out, "<aside class=\"citation\" id=\"{ids}\">");
            schedule(node, "</aside>", tasks);
        }
        NodeKind::CitationReference { refid, .. } => {
            let _ = write!(out, "<a class=\"citation-reference\" href=\"#{refid}\">");
            schedule(node, "</a>", tasks);
        }
        NodeKind::Problematic { refid, ids } => {
            let _ = write!(
                out,
                "<a class=\"problematic\" id=\"{ids}\" href=\"#{refid}\">"
            );
            schedule(node, "</a>", tasks);
        }
        NodeKind::SystemMessage { level, ty, .. } => {
            let _ = write!(
                out,
                "<aside class=\"system-message level-{level} type-{ty}\">"
            );
            schedule(node, "</aside>", tasks);
        }
        NodeKind::Extension { class_name, attrs } => {
            let visit = crate::plugins::invoke_node_visit(class_name, "html", attrs);
            if let Some(open) = &visit {
                out.push_str(open);
            }
            let close = if visit.is_some() {
                crate::plugins::invoke_node_depart(class_name, "html", attrs)
            } else {
                None
            };
            schedule(node, close.unwrap_or_default(), tasks);
        }
        NodeKind::Abbreviation { explanation } => {
            if explanation.is_empty() {
                out.push_str("<abbr>");
            } else {
                let _ = write!(out, "<abbr title=\"{}\">", escape(explanation));
            }
            schedule(node, "</abbr>", tasks);
        }
        NodeKind::Subscript => wrap(node, "sub", out, tasks),
        NodeKind::Superscript => wrap(node, "sup", out, tasks),
        NodeKind::Keyboard => wrap_with_class(node, "kbd", "kbd", out, tasks),
        NodeKind::Rubric => wrap_with_class(node, "p", "rubric", out, tasks),
        NodeKind::VersionModified { kind, version } => {
            let _ = write!(
                out,
                "<div class=\"versionmodified {kind}\"><span class=\"versionmodified\">"
            );
            let prefix = match *kind {
                "added" => "Added in version",
                "changed" => "Changed in version",
                "deprecated" => "Deprecated since version",
                _ => "Modified in version",
            };
            let _ = write!(out, "{} {}", prefix, escape(version));
            if !node.children.is_empty() {
                out.push_str(": </span>");
                schedule(node, "</div>", tasks);
            } else {
                out.push_str(".</span>");
                out.push_str("</div>");
            }
        }
        NodeKind::PendingXref { reftype, .. } => wrap_with_class(
            node,
            "span",
            &format!("xref {}", escape(reftype)),
            out,
            tasks,
        ),
        NodeKind::ObjectDescription {
            classes,
            ids,
            sig_text,
        } => {
            if classes.is_empty() {
                out.push_str("<dl>");
            } else {
                let _ = write!(out, "<dl class=\"{}\">", escape(classes));
            }
            if ids.is_empty() {
                out.push_str("<dt>");
            } else {
                let _ = write!(out, "<dt id=\"{}\">", escape(ids));
            }
            out.push_str(&escape(sig_text));
            out.push_str("</dt><dd>");
            schedule(node, "</dd></dl>", tasks);
        }
    }
}

fn escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            _ => out.push(ch),
        }
    }
    out
}

fn get_math_backend(options: &crate::cli::Html5Options) -> mathrenderrs::MathBackend {
    if let Some(format) = &options.math_output {
        let fmt = format
            .split_whitespace()
            .next()
            .unwrap_or("")
            .to_lowercase();
        match fmt.as_str() {
            "mathjax" => mathrenderrs::MathBackend::MathJax,
            "html" | "mathml" => mathrenderrs::MathBackend::Ratex, // Fallback since MathML isn't natively MathML here in our backend yet.
            _ => mathrenderrs::MathBackend::default(),
        }
    } else {
        mathrenderrs::MathBackend::default()
    }
}

fn is_compactable(
    tree: &crate::doctree::Doctree,
    node_id: crate::doctree::NodeId,
    options: &crate::cli::Html5Options,
    is_field_list: bool,
) -> bool {
    use crate::doctree::NodeKind;
    let node = tree.node(node_id);

    if is_field_list {
        if options.no_compact_field_lists.is_some() {
            return false;
        }
    } else {
        if options.no_compact_lists.is_some() {
            return false;
        }
    }

    for &child_id in &node.children {
        let child = tree.node(child_id);
        let mut child_content: Vec<crate::doctree::NodeId> = vec![];

        match child.kind {
            NodeKind::Field => {
                if child.children.len() >= 2 {
                    let field_body = tree.node(child.children[1]);
                    child_content = field_body.children.clone();
                }
            }
            NodeKind::DefinitionListItem => {
                if let Some(&def_id) = child.children.last() {
                    let definition = tree.node(def_id);
                    if let NodeKind::Definition = definition.kind {
                        child_content = definition.children.clone();
                    }
                }
            }
            _ => {
                child_content = child.children.clone();
            }
        }

        if !child_content.is_empty() {
            let last_child_id = *child_content.last().unwrap();
            let last_child = tree.node(last_child_id);
            match last_child.kind {
                NodeKind::BulletList { .. }
                | NodeKind::EnumeratedList { .. }
                | NodeKind::FieldList => {
                    child_content.pop();
                }
                _ => {}
            }
        }

        if child_content.len() > 1 {
            return false;
        }
    }

    true
}

fn get_datestamp(common: &crate::cli::CommonOptions) -> Option<String> {
    if common.no_datestamp.is_some() {
        return None;
    }
    if common.time.is_some() {
        let utc = chrono::Utc::now();
        Some(utc.format("%Y-%m-%d %H:%M UTC").to_string())
    } else if common.date.is_some() {
        let utc = chrono::Utc::now();
        Some(utc.format("%Y-%m-%d").to_string())
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::doctree::Doctree;

    #[test]
    fn deeply_nested_html5_does_not_use_call_stack() {
        let mut tree = Doctree::new_document("deep.html");
        let mut parent = tree.root();
        for _ in 0..10_000 {
            parent = tree.append(
                parent,
                NodeKind::Container {
                    classes: String::new(),
                },
            );
        }
        tree.append(parent, NodeKind::Text("deep".to_string()));

        let options = crate::cli::Html5Options::default();
        let common = crate::cli::CommonOptions::default();
        let rendered = html5(&tree, &options, &common);
        assert_eq!(
            rendered
                .matches("<div class=\"docutils container\">")
                .count(),
            10_000
        );
        assert_eq!(rendered.matches("</div>").count(), 10_000);
        assert!(rendered.contains("deep"));
    }
}
