//! Lexer alias → lexer instance resolution.
//!
//! Mirrors `pygments.lexers.get_lexer_by_name`. This module implements a **hybrid lexer registry**
//! that combines compile-time performance with runtime extensibility:
//!
//! ## Design
//!
//! - **Compile-time lexers** (`LEXER_MAP`): ~800 built-in lexers registered via a perfect hash function
//!   (phf crate). These provide O(1) lookup with zero runtime overhead.
//! - **Runtime lexers** (`RUNTIME_LEXERS`): Dynamically registered lexers (e.g., from plugins, Python
//!   interop). Stored in a thread-safe `HashMap<&'static str, LexerConstructor>` behind `RwLock`.
//!
//! ## Access Pattern
//!
//! 1. [`get_lexer_by_name`] checks the built-in map first (fast, lock-free)
//! 2. Falls back to the runtime registry if not found (minimal contention)
//!
//! ## Usage
//!
//! ```rust,ignore
//! use pygmentsrs::lexers::registry::{get_lexer_by_name, register_lexer};
//!
//! // Use a built-in lexer (O(1), no locks)
//! let lexer = get_lexer_by_name("python")?;
//!
//! // Register a custom lexer at runtime (e.g., from a plugin)
//! register_lexer("my-lang", || Box::new(MyLexer))?;
//! let custom = get_lexer_by_name("my-lang")?;
//!
//! // Cannot override built-ins (safety guarantee)
//! assert!(register_lexer("python", || Box::new(MyLexer)).is_err());
//! ```
//!
//! ## Thread Safety
//!
//! - `get_lexer_by_name()` is lock-free for built-ins and uses a read-lock for runtime lexers
//! - `register_lexer()` and `unregister_lexer()` acquire a write lock
//! - Safe for concurrent use across threads

use crate::lexer::Lexer;
use crate::lexers::delegating::*;
use crate::lexers::diff::DiffLexer;
use crate::lexers::generated;
use crate::lexers::json::JsonLexer;
use crate::lexers::json_ld::JsonLdLexer;
use crate::lexers::python::PythonLexer;
use crate::lexers::text::TextLexer;
use crate::lexers::yaml_ld::YamlLdLexer;
use phf::{self, phf_map};
use std::collections::HashMap;
use std::sync::{OnceLock, RwLock};

type LexerConstructor = fn() -> Box<dyn Lexer>;

// Compile-time perfect hash function (generated by phf macro)
// O(1) lookup with zero runtime overhead
static LEXER_MAP: phf::Map<&'static str, LexerConstructor> = phf_map! {

    "abap" => || Box::new(generated::abap::AbapLexer),
    "abl" => || Box::new(generated::openedge::OpenedgeLexer),
    "abnf" => || Box::new(generated::abnf::AbnfLexer),
    "aconf" => || Box::new(generated::apache::ApacheLexer),
    "actionscript" => || Box::new(generated::actionscript::ActionscriptLexer),
    "actionscript3" => || Box::new(generated::actionscript3::Actionscript3Lexer),
    "ada" => || Box::new(generated::ada::AdaLexer),
    "ada2005" => || Box::new(generated::ada::AdaLexer),
    "ada95" => || Box::new(generated::ada::AdaLexer),
    "adl" => || Box::new(generated::adl::AdlLexer),
    "agda" => || Box::new(generated::agda::AgdaLexer),
    "aheui" => || Box::new(generated::aheui::AheuiLexer),
    "ahk" => || Box::new(generated::autohotkey::AutohotkeyLexer),
    "alloy" => || Box::new(generated::alloy::AlloyLexer),
    "ambienttalk" => || Box::new(generated::ambienttalk::AmbienttalkLexer),
    "ambienttalk/2" => || Box::new(generated::ambienttalk::AmbienttalkLexer),
    "amdgpu" => || Box::new(generated::amdgpu::AmdgpuLexer),
    "ampl" => || Box::new(generated::ampl::AmplLexer),
    "androidbp" => || Box::new(generated::androidbp::AndroidbpLexer),
    "ansys" => || Box::new(generated::ansys::AnsysLexer),
    "antlr" => || Box::new(generated::antlr::AntlrLexer),
    "antlr-actionscript" => || Box::new(AntlrActionScriptLexer),
    "antlr-as" => || Box::new(AntlrActionScriptLexer),
    "antlr-c#" => || Box::new(AntlrCSharpLexer),
    "antlr-cpp" => || Box::new(AntlrCppLexer),
    "antlr-csharp" => || Box::new(AntlrCSharpLexer),
    "antlr-java" => || Box::new(AntlrJavaLexer),
    "antlr-objc" => || Box::new(AntlrObjectiveCLexer),
    "antlr-perl" => || Box::new(AntlrPerlLexer),
    "antlr-python" => || Box::new(AntlrPythonLexer),
    "apache" => || Box::new(generated::apache::ApacheLexer),
    "apacheconf" => || Box::new(generated::apache::ApacheLexer),
    "apdl" => || Box::new(generated::ansys::AnsysLexer),
    "apl" => || Box::new(generated::apl::AplLexer),
    "applescript" => || Box::new(generated::applescript::ApplescriptLexer),
    "arduino" => || Box::new(generated::arduino::ArduinoLexer),
    "arexx" => || Box::new(generated::rexx::RexxLexer),
    "arrow" => || Box::new(generated::arrow::ArrowLexer),
    "as" => || Box::new(generated::actionscript::ActionscriptLexer),
    "as3" => || Box::new(generated::actionscript3::Actionscript3Lexer),
    "asc" => || Box::new(generated::asc::AscLexer),
    "asm" => || Box::new(generated::gas::GasLexer),
    "asn1" => || Box::new(generated::asn1::Asn1Lexer),
    "aspectj" => || Box::new(generated::aspectj::AspectjLexer),
    "asy" => || Box::new(generated::asymptote::AsymptoteLexer),
    "asymptote" => || Box::new(generated::asymptote::AsymptoteLexer),
    "at" => || Box::new(generated::ambienttalk::AmbienttalkLexer),
    "augeas" => || Box::new(generated::augeas::AugeasLexer),
    "autohotkey" => || Box::new(generated::autohotkey::AutohotkeyLexer),
    "autoit" => || Box::new(generated::autoit::AutoitLexer),
    "awk" => || Box::new(generated::awk::AwkLexer),
    "b3d" => || Box::new(generated::blitzbasic::BlitzbasicLexer),
    "bare" => || Box::new(generated::bare::BareLexer),
    "basemake" => || Box::new(generated::basemake::BasemakeLexer),
    "bash" => || Box::new(generated::bash::BashLexer),
    "basic" => || Box::new(generated::qbasic::QbasicLexer),
    "bat" => || Box::new(generated::batch::BatchLexer),
    "batch" => || Box::new(generated::batch::BatchLexer),
    "bbcbasic" => || Box::new(generated::bbcbasic::BbcbasicLexer),
    "bbcode" => || Box::new(generated::bbcode::BbcodeLexer),
    "bc" => || Box::new(generated::bc::BcLexer),
    "bdd" => || Box::new(generated::bdd::BddLexer),
    "be" => || Box::new(generated::berry::BerryLexer),
    "befunge" => || Box::new(generated::befunge::BefungeLexer),
    "berry" => || Box::new(generated::berry::BerryLexer),
    "bf" => || Box::new(generated::brainfuck::BrainfuckLexer),
    "bitbake" => || Box::new(generated::bitbake::BitbakeLexer),
    "blitzbasic" => || Box::new(generated::blitzbasic::BlitzbasicLexer),
    "blitzmax" => || Box::new(generated::blitzmax::BlitzmaxLexer),
    "blueprint" => || Box::new(generated::blueprint::BlueprintLexer),
    "bmax" => || Box::new(generated::blitzmax::BlitzmaxLexer),
    "bnf" => || Box::new(generated::bnf::BnfLexer),
    "boa" => || Box::new(generated::boa::BoaLexer),
    "boo" => || Box::new(generated::boo::BooLexer),
    "boogie" => || Box::new(generated::boogie::BoogieLexer),
    "bp" => || Box::new(generated::androidbp::AndroidbpLexer),
    "bplus" => || Box::new(generated::blitzbasic::BlitzbasicLexer),
    "bqn" => || Box::new(generated::bqn::BqnLexer),
    "brainfuck" => || Box::new(generated::brainfuck::BrainfuckLexer),
    "bro" => || Box::new(generated::zeek::ZeekLexer),
    "bst" => || Box::new(generated::bst::BstLexer),
    "bst-pybtex" => || Box::new(generated::bst::BstLexer),
    "bugs" => || Box::new(generated::bugs::BugsLexer),
    "c" => || Box::new(generated::c::CLexer),
    "c#" => || Box::new(generated::csharp::CsharpLexer),
    "c++" => || Box::new(generated::cpp::CppLexer),
    "c++-objdumb" => || Box::new(CppObjdumpLexer),
    "c-objdump" => || Box::new(CObjdumpLexer),
    "ca65" => || Box::new(generated::ca65::Ca65Lexer),
    "cadl" => || Box::new(generated::cadl::CadlLexer),
    "camkes" => || Box::new(generated::camkes::CamkesLexer),
    "capdl" => || Box::new(generated::capdl::CapdlLexer),
    "capnp" => || Box::new(generated::capnp::CapnpLexer),
    "carbon" => || Box::new(generated::carbon::CarbonLexer),
    "cbmbas" => || Box::new(generated::cbmbas::CbmbasLexer),
    "cddl" => || Box::new(generated::cddl::CddlLexer),
    "cel" => || Box::new(generated::cel::CelLexer),
    "ceylon" => || Box::new(generated::ceylon::CeylonLexer),
    "cf3" => || Box::new(generated::cfengine3::Cfengine3Lexer),
    "cfengine3" => || Box::new(generated::cfengine3::Cfengine3Lexer),
    "cfg" => || Box::new(generated::ini::IniLexer),
    "cfs" => || Box::new(generated::cfs::CfsLexer),
    "chai" => || Box::new(generated::chaiscript::ChaiscriptLexer),
    "chaiscript" => || Box::new(generated::chaiscript::ChaiscriptLexer),
    "chapel" => || Box::new(generated::chapel::ChapelLexer),
    "charmci" => || Box::new(generated::charmci::CharmciLexer),
    "cheetah" => || Box::new(generated::cheetah::CheetahLexer),
    "chpl" => || Box::new(generated::chapel::ChapelLexer),
    "cirru" => || Box::new(generated::cirru::CirruLexer),
    "cl" => || Box::new(generated::common_lisp::CommonLispLexer),
    "clay" => || Box::new(generated::clay::ClayLexer),
    "clean" => || Box::new(generated::clean::CleanLexer),
    "clipper" => || Box::new(generated::foxpro::FoxproLexer),
    "clj" => || Box::new(generated::clojure::ClojureLexer),
    "cljs" => || Box::new(generated::clojurescript::ClojurescriptLexer),
    "clojure" => || Box::new(generated::clojure::ClojureLexer),
    "clojurescript" => || Box::new(generated::clojurescript::ClojurescriptLexer),
    "cmake" => || Box::new(generated::cmake::CmakeLexer),
    "cobol" => || Box::new(generated::cobol::CobolLexer),
    "cobolfree" => || Box::new(generated::cobolfree::CobolfreeLexer),
    "codeql" => || Box::new(generated::codeql::CodeqlLexer),
    "coffee" => || Box::new(generated::coffeescript::CoffeescriptLexer),
    "coffee-script" => || Box::new(generated::coffeescript::CoffeescriptLexer),
    "coffeescript" => || Box::new(generated::coffeescript::CoffeescriptLexer),
    "comal" => || Box::new(generated::comal::ComalLexer),
    "comal80" => || Box::new(generated::comal::ComalLexer),
    "common-lisp" => || Box::new(generated::common_lisp::CommonLispLexer),
    "componentpascal" => || Box::new(generated::componentpascal::ComponentpascalLexer),
    "control" => || Box::new(generated::debcontrol::DebcontrolLexer),
    "coq" => || Box::new(generated::coq::CoqLexer),
    "cp" => || Box::new(generated::componentpascal::ComponentpascalLexer),
    "cplint" => || Box::new(generated::cplint::CplintLexer),
    "cpp" => || Box::new(generated::cpp::CppLexer),
    "cpp-objdump" => || Box::new(CppObjdumpLexer),
    "cpsa" => || Box::new(generated::cpsa::CpsaLexer),
    "crmsh" => || Box::new(generated::crmsh::CrmshLexer),
    "croc" => || Box::new(generated::croc::CrocLexer),
    "cry" => || Box::new(generated::cryptol::CryptolLexer),
    "cryptol" => || Box::new(generated::cryptol::CryptolLexer),
    "cs" => || Box::new(generated::csharp::CsharpLexer),
    "csh" => || Box::new(generated::tcsh::TcshLexer),
    "csharp" => || Box::new(generated::csharp::CsharpLexer),
    "csound-csd" => || Box::new(generated::csound_document::CsoundDocumentLexer),
    "csound-document" => || Box::new(generated::csound_document::CsoundDocumentLexer),
    "csound-sco" => || Box::new(generated::csound_score::CsoundScoreLexer),
    "csound-score" => || Box::new(generated::csound_score::CsoundScoreLexer),
    "css" => || Box::new(generated::css::CssLexer),
    "css+django" => || Box::new(CssDjangoLexer),
    "css+genshi" => || Box::new(CssGenshiLexer),
    "css+genshitext" => || Box::new(CssGenshiLexer),
    "css+jinja" => || Box::new(CssDjangoLexer),
    "css+lasso" => || Box::new(LassoCssLexer),
    "css+mako" => || Box::new(MakoCssLexer),
    "css+mozpreproc" => || Box::new(MozPreprocCssLexer),
    "css+myghty" => || Box::new(MyghtyCssLexer),
    "css+php" => || Box::new(CssPhpLexer),
    "css+smarty" => || Box::new(CssSmartyLexer),
    "css+ul4" => || Box::new(CSSUL4Lexer),
    "cu" => || Box::new(generated::cuda::CudaLexer),
    "cucumber" => || Box::new(generated::gherkin::GherkinLexer),
    "cuda" => || Box::new(generated::cuda::CudaLexer),
    "cypher" => || Box::new(generated::cypher::CypherLexer),
    "cython" => || Box::new(generated::cython::CythonLexer),
    "d" => || Box::new(generated::d::DLexer),
    "d-objdump" => || Box::new(DObjdumpLexer),
    "dart" => || Box::new(generated::dart::DartLexer),
    "dax" => || Box::new(generated::dax::DaxLexer),
    "debcontrol" => || Box::new(generated::debcontrol::DebcontrolLexer),
    "debian.sources" => || Box::new(generated::debian_sources::DebianSourcesLexer),
    "debsources" => || Box::new(generated::debsources::DebsourcesLexer),
    "desktop" => || Box::new(generated::desktop::DesktopLexer),
    "devicetree" => || Box::new(generated::devicetree::DevicetreeLexer),
    "dg" => || Box::new(generated::dg::DgLexer),
    "diff" => || Box::new(DiffLexer),
    "django" => || Box::new(generated::django::DjangoLexer),
    "dmesg" => || Box::new(generated::kmsg::KmsgLexer),
    "do" => || Box::new(generated::stata::StataLexer),
    "docker" => || Box::new(generated::docker::DockerLexer),
    "dockerfile" => || Box::new(generated::docker::DockerLexer),
    "dosbatch" => || Box::new(generated::batch::BatchLexer),
    "dosini" => || Box::new(generated::ini::IniLexer),
    "dot" => || Box::new(generated::graphviz::GraphvizLexer),
    "dpatch" => || Box::new(generated::darcs::DarcsLexer),
    "dtd" => || Box::new(generated::dtd::DtdLexer),
    "dts" => || Box::new(generated::devicetree::DevicetreeLexer),
    "duel" => || Box::new(generated::duel::DuelLexer),
    "dylan" => || Box::new(generated::dylan::DylanLexer),
    "dylan-lid" => || Box::new(generated::dylan_lid::DylanLidLexer),
    "earl-grey" => || Box::new(generated::earl_grey::EarlGreyLexer),
    "earlgrey" => || Box::new(generated::earl_grey::EarlGreyLexer),
    "easytrieve" => || Box::new(generated::easytrieve::EasytrieveLexer),
    "ebnf" => || Box::new(generated::ebnf::EbnfLexer),
    "ec" => || Box::new(generated::ec::EcLexer),
    "ecl" => || Box::new(generated::ecl::EclLexer),
    "eg" => || Box::new(generated::earl_grey::EarlGreyLexer),
    "eiffel" => || Box::new(generated::eiffel::EiffelLexer),
    "elisp" => || Box::new(generated::emacs_lisp::EmacsLispLexer),
    "elixir" => || Box::new(generated::elixir::ElixirLexer),
    "elm" => || Box::new(generated::elm::ElmLexer),
    "elpi" => || Box::new(generated::elpi::ElpiLexer),
    "emacs" => || Box::new(generated::emacs_lisp::EmacsLispLexer),
    "emacs-lisp" => || Box::new(generated::emacs_lisp::EmacsLispLexer),
    "erlang" => || Box::new(generated::erlang::ErlangLexer),
    "evoque" => || Box::new(generated::evoque::EvoqueLexer),
    "ex" => || Box::new(generated::elixir::ElixirLexer),
    "execline" => || Box::new(generated::execline::ExeclineLexer),
    "exs" => || Box::new(generated::elixir::ElixirLexer),
    "extempore" => || Box::new(generated::extempore::ExtemporeLexer),
    "ezhil" => || Box::new(generated::ezhil::EzhilLexer),
    "f#" => || Box::new(generated::fsharp::FsharpLexer),
    "f90" => || Box::new(generated::fortran::FortranLexer),
    "factor" => || Box::new(generated::factor::FactorLexer),
    "fan" => || Box::new(generated::fan::FanLexer),
    "fancy" => || Box::new(generated::fancy::FancyLexer),
    "fc" => || Box::new(generated::func::FuncLexer),
    "felix" => || Box::new(generated::felix::FelixLexer),
    "fennel" => || Box::new(generated::fennel::FennelLexer),
    "fif" => || Box::new(generated::fift::FiftLexer),
    "fift" => || Box::new(generated::fift::FiftLexer),
    "fish" => || Box::new(generated::fish::FishLexer),
    "fishshell" => || Box::new(generated::fish::FishLexer),
    "flatline" => || Box::new(generated::flatline::FlatlineLexer),
    "flo" => || Box::new(generated::floscript::FloscriptLexer),
    "floscript" => || Box::new(generated::floscript::FloscriptLexer),
    "flx" => || Box::new(generated::felix::FelixLexer),
    "fnl" => || Box::new(generated::fennel::FennelLexer),
    "forth" => || Box::new(generated::forth::ForthLexer),
    "fortran" => || Box::new(generated::fortran::FortranLexer),
    "foxpro" => || Box::new(generated::foxpro::FoxproLexer),
    "freefem" => || Box::new(generated::freefem::FreefemLexer),
    "fsharp" => || Box::new(generated::fsharp::FsharpLexer),
    "fstar" => || Box::new(generated::fstar::FstarLexer),
    "func" => || Box::new(generated::func::FuncLexer),
    "futhark" => || Box::new(generated::futhark::FutharkLexer),
    "fy" => || Box::new(generated::fancy::FancyLexer),
    "gap" => || Box::new(generated::gap::GapLexer),
    "gas" => || Box::new(generated::gas::GasLexer),
    "gawk" => || Box::new(generated::awk::AwkLexer),
    "gcode" => || Box::new(generated::gcode::GcodeLexer),
    "gd" => || Box::new(generated::gdscript::GdscriptLexer),
    "gdscript" => || Box::new(generated::gdscript::GdscriptLexer),
    "genshitext" => || Box::new(generated::genshitext::GenshitextLexer),
    "gherkin" => || Box::new(generated::gherkin::GherkinLexer),
    "gleam" => || Box::new(generated::gleam::GleamLexer),
    "glsl" => || Box::new(generated::glsl::GlslLexer),
    "gnuplot" => || Box::new(generated::gnuplot::GnuplotLexer),
    "go" => || Box::new(generated::go::GoLexer),
    "golang" => || Box::new(generated::go::GoLexer),
    "golo" => || Box::new(generated::golo::GoloLexer),
    "gooddata-cl" => || Box::new(generated::gooddata_cl::GooddataClLexer),
    "googlesql" => || Box::new(generated::googlesql::GooglesqlLexer),
    "gosu" => || Box::new(generated::gosu::GosuLexer),
    "graphql" => || Box::new(generated::graphql::GraphqlLexer),
    "graphviz" => || Box::new(generated::graphviz::GraphvizLexer),
    "groff" => || Box::new(generated::groff::GroffLexer),
    "groovy" => || Box::new(generated::groovy::GroovyLexer),
    "gsed" => || Box::new(generated::sed::SedLexer),
    "gsql" => || Box::new(generated::gsql::GsqlLexer),
    "handlebars" => || Box::new(generated::handlebars::HandlebarsLexer),
    "hare" => || Box::new(generated::hare::HareLexer),
    "haskell" => || Box::new(generated::haskell::HaskellLexer),
    "haxeml" => || Box::new(generated::haxeml::HaxemlLexer),
    "hexdump" => || Box::new(generated::hexdump::HexdumpLexer),
    "hlsl" => || Box::new(generated::hlsl::HlslLexer),
    "hs" => || Box::new(generated::haskell::HaskellLexer),
    "hsa" => || Box::new(generated::hsail::HsailLexer),
    "hsail" => || Box::new(generated::hsail::HsailLexer),
    "hspec" => || Box::new(generated::hspec::HspecLexer),
    "html" => || Box::new(generated::html::HtmlLexer),
    "html+cheetah" => || Box::new(CheetahHtmlLexer),
    "html+django" => || Box::new(HtmlDjangoLexer),
    "html+evoque" => || Box::new(EvoqueHtmlLexer),
    "html+handlebars" => || Box::new(HandlebarsHtmlLexer),
    "html+jinja" => || Box::new(HtmlDjangoLexer),
    "html+lasso" => || Box::new(LassoHtmlLexer),
    "html+mako" => || Box::new(MakoHtmlLexer),
    "html+myghty" => || Box::new(MyghtyHtmlLexer),
    "html+ng2" => || Box::new(Angular2HtmlLexer),
    "html+php" => || Box::new(HtmlPhpLexer),
    "html+smarty" => || Box::new(HtmlSmartyLexer),
    "html+spitfire" => || Box::new(CheetahHtmlLexer),
    "html+twig" => || Box::new(TwigHtmlLexer),
    "html+ul4" => || Box::new(HTMLUL4Lexer),
    "html+velocity" => || Box::new(VelocityHtmlLexer),
    "hxml" => || Box::new(generated::haxeml::HaxemlLexer),
    "hy" => || Box::new(generated::hylang::HylangLexer),
    "hybris" => || Box::new(generated::hybris::HybrisLexer),
    "hylang" => || Box::new(generated::hylang::HylangLexer),
    "i6" => || Box::new(generated::inform6::Inform6Lexer),
    "i6t" => || Box::new(generated::i6t::I6tLexer),
    "i7" => || Box::new(generated::inform7::Inform7Lexer),
    "icon" => || Box::new(generated::icon::IconLexer),
    "idl" => || Box::new(generated::idl::IdlLexer),
    "idl4" => || Box::new(generated::camkes::CamkesLexer),
    "idr" => || Box::new(generated::idris::IdrisLexer),
    "idris" => || Box::new(generated::idris::IdrisLexer),
    "igor" => || Box::new(generated::igor::IgorLexer),
    "igorpro" => || Box::new(generated::igor::IgorLexer),
    "ik" => || Box::new(generated::ioke::IokeLexer),
    "inform6" => || Box::new(generated::inform6::Inform6Lexer),
    "inform7" => || Box::new(generated::inform7::Inform7Lexer),
    "ini" => || Box::new(generated::ini::IniLexer),
    "io" => || Box::new(generated::io::IoLexer),
    "ioke" => || Box::new(generated::ioke::IokeLexer),
    "irc" => || Box::new(generated::irc::IrcLexer),
    "isabelle" => || Box::new(generated::isabelle::IsabelleLexer),
    "j" => || Box::new(generated::j::JLexer),
    "jags" => || Box::new(generated::jags::JagsLexer),
    "janet" => || Box::new(generated::janet::JanetLexer),
    "jasmin" => || Box::new(generated::jasmin::JasminLexer),
    "jasminxt" => || Box::new(generated::jasmin::JasminLexer),
    "java" => || Box::new(generated::java::JavaLexer),
    "javascript" => || Box::new(generated::javascript::JavascriptLexer),
    "javascript+cheetah" => || Box::new(CheetahJavascriptLexer),
    "javascript+django" => || Box::new(JavascriptDjangoLexer),
    "javascript+lasso" => || Box::new(LassoJavascriptLexer),
    "javascript+mako" => || Box::new(MakoJavascriptLexer),
    "javascript+mozpreproc" => || Box::new(MozPreprocJavascriptLexer),
    "javascript+myghty" => || Box::new(MyghtyJavascriptLexer),
    "javascript+php" => || Box::new(JavascriptPhpLexer),
    "javascript+smarty" => || Box::new(JavascriptSmartyLexer),
    "jbst" => || Box::new(generated::duel::DuelLexer),
    "jcl" => || Box::new(generated::jcl::JclLexer),
    "jinja" => || Box::new(generated::django::DjangoLexer),
    "jl" => || Box::new(generated::julia::JuliaLexer),
    "jmespath" => || Box::new(generated::jmespath::JmespathLexer),
    "jp" => || Box::new(generated::jmespath::JmespathLexer),
    "jproperties" => || Box::new(generated::properties::PropertiesLexer),
    "js" => || Box::new(generated::javascript::JavascriptLexer),
    "js+cheetah" => || Box::new(CheetahJavascriptLexer),
    "js+django" => || Box::new(JavascriptDjangoLexer),
    "js+genshi" => || Box::new(JavascriptGenshiLexer),
    "js+genshitext" => || Box::new(JavascriptGenshiLexer),
    "js+lasso" => || Box::new(LassoJavascriptLexer),
    "js+mako" => || Box::new(MakoJavascriptLexer),
    "js+myghty" => || Box::new(MyghtyJavascriptLexer),
    "js+php" => || Box::new(JavascriptPhpLexer),
    "js+smarty" => || Box::new(JavascriptSmartyLexer),
    "js+ul4" => || Box::new(JavascriptUL4Lexer),
    "jsgf" => || Box::new(generated::jsgf::JsgfLexer),
    "jslt" => || Box::new(generated::jslt::JsltLexer),
    "json" => || Box::new(JsonLexer),
    "json-ld" => || Box::new(JsonLdLexer),
    "json-object" => || Box::new(JsonLexer),
    "json5" => || Box::new(generated::json5::Json5Lexer),
    "jsonld" => || Box::new(JsonLdLexer),
    "jsonml+bst" => || Box::new(generated::duel::DuelLexer),
    "jsonnet" => || Box::new(generated::jsonnet::JsonnetLexer),
    "jsx" => || Box::new(generated::jsx::JsxLexer),
    "julia" => || Box::new(generated::julia::JuliaLexer),
    "juttle" => || Box::new(generated::juttle::JuttleLexer),
    "k" => || Box::new(generated::k::KLexer),
    "kal" => || Box::new(generated::kal::KalLexer),
    "kconfig" => || Box::new(generated::kconfig::KconfigLexer),
    "ksh" => || Box::new(generated::bash::BashLexer),
    "kernel-config" => || Box::new(generated::kconfig::KconfigLexer),
    "kmsg" => || Box::new(generated::kmsg::KmsgLexer),
    "koka" => || Box::new(generated::koka::KokaLexer),
    "kotlin" => || Box::new(generated::kotlin::KotlinLexer),
    "kql" => || Box::new(generated::kql::KqlLexer),
    "kuin" => || Box::new(generated::kuin::KuinLexer),
    "kusto" => || Box::new(generated::kql::KqlLexer),
    "lasso" => || Box::new(generated::lasso::LassoLexer),
    "lassoscript" => || Box::new(generated::lasso::LassoLexer),
    "latex" => || Box::new(generated::tex::TexLexer),
    "ldapconf" => || Box::new(generated::ldapconf::LdapconfLexer),
    "ldaprc" => || Box::new(generated::ldapconf::LdapconfLexer),
    "ldif" => || Box::new(generated::ldif::LdifLexer),
    "lean" => || Box::new(generated::lean::LeanLexer),
    "lean3" => || Box::new(generated::lean::LeanLexer),
    "lean4" => || Box::new(generated::lean4::Lean4Lexer),
    "less" => || Box::new(generated::less::LessLexer),
    "lid" => || Box::new(generated::dylan_lid::DylanLidLexer),
    "lighttpd" => || Box::new(generated::lighttpd::LighttpdLexer),
    "lighty" => || Box::new(generated::lighttpd::LighttpdLexer),
    "limbo" => || Box::new(generated::limbo::LimboLexer),
    "linux-config" => || Box::new(generated::kconfig::KconfigLexer),
    "linuxconfig" => || Box::new(generated::unixconfig::UnixconfigLexer),
    "liquid" => || Box::new(generated::liquid::LiquidLexer),
    "lisp" => || Box::new(generated::common_lisp::CommonLispLexer),
    "live-script" => || Box::new(generated::livescript::LivescriptLexer),
    "livescript" => || Box::new(generated::livescript::LivescriptLexer),
    "llvm" => || Box::new(generated::llvm::LlvmLexer),
    "llvm-mir" => || Box::new(generated::llvm_mir::LlvmMirLexer),
    "llvm-mir-body" => || Box::new(generated::llvm_mir_body::LlvmMirBodyLexer),
    "lobas" => || Box::new(generated::vb_net::VbNetLexer),
    "logos" => || Box::new(generated::logos::LogosLexer),
    "logtalk" => || Box::new(generated::logtalk::LogtalkLexer),
    "lsl" => || Box::new(generated::lsl::LslLexer),
    "lua" => || Box::new(generated::lua::LuaLexer),
    "luau" => || Box::new(generated::luau::LuauLexer),
    "m2" => || Box::new(generated::modula2::Modula2Lexer),
    "macaulay2" => || Box::new(generated::macaulay2::Macaulay2Lexer),
    "macsyma" => || Box::new(generated::maxima::MaximaLexer),
    "mako" => || Box::new(generated::mako::MakoLexer),
    "man" => || Box::new(generated::groff::GroffLexer),
    "maql" => || Box::new(generated::maql::MaqlLexer),
    "markdown" => || Box::new(generated::markdown::MarkdownLexer),
    "mask" => || Box::new(generated::mask::MaskLexer),
    "mason" => || Box::new(generated::mason::MasonLexer),
    "mathematica" => || Box::new(generated::mathematica::MathematicaLexer),
    "matlab" => || Box::new(generated::matlab::MatlabLexer),
    "mawk" => || Box::new(generated::awk::AwkLexer),
    "maxima" => || Box::new(generated::maxima::MaximaLexer),
    "mcf" => || Box::new(generated::mcfunction::McfunctionLexer),
    "mcfunction" => || Box::new(generated::mcfunction::McfunctionLexer),
    "mcschema" => || Box::new(generated::mcschema::McschemaLexer),
    "md" => || Box::new(generated::markdown::MarkdownLexer),
    "menuconfig" => || Box::new(generated::kconfig::KconfigLexer),
    "meson" => || Box::new(generated::meson::MesonLexer),
    "meson.build" => || Box::new(generated::meson::MesonLexer),
    "minid" => || Box::new(generated::minid::MinidLexer),
    "miniscript" => || Box::new(generated::miniscript::MiniscriptLexer),
    "mips" => || Box::new(generated::mips::MipsLexer),
    "mma" => || Box::new(generated::mathematica::MathematicaLexer),
    "modelica" => || Box::new(generated::modelica::ModelicaLexer),
    "modula2" => || Box::new(generated::modula2::Modula2Lexer),
    "moin" => || Box::new(generated::trac_wiki::TracWikiLexer),
    "mojo" => || Box::new(generated::mojo::MojoLexer),
    "monkey" => || Box::new(generated::monkey::MonkeyLexer),
    "monte" => || Box::new(generated::monte::MonteLexer),
    "moo" => || Box::new(generated::moocode::MoocodeLexer),
    "moocode" => || Box::new(generated::moocode::MoocodeLexer),
    "moon" => || Box::new(generated::moonscript::MoonscriptLexer),
    "moonscript" => || Box::new(generated::moonscript::MoonscriptLexer),
    "mosel" => || Box::new(generated::mosel::MoselLexer),
    "mozhashpreproc" => || Box::new(generated::moz_hashpreproc::MozHashpreprocLexer),
    "mozpercentpreproc" => || Box::new(generated::moz_percentpreproc::MozPercentpreprocLexer),
    "mq4" => || Box::new(generated::mql::MqlLexer),
    "mq5" => || Box::new(generated::mql::MqlLexer),
    "mql" => || Box::new(generated::mql::MqlLexer),
    "mql4" => || Box::new(generated::mql::MqlLexer),
    "mql5" => || Box::new(generated::mql::MqlLexer),
    "ms" => || Box::new(generated::miniscript::MiniscriptLexer),
    "msc" => || Box::new(generated::mscgen::MscgenLexer),
    "mscgen" => || Box::new(generated::mscgen::MscgenLexer),
    "mupad" => || Box::new(generated::mupad::MupadLexer),
    "mxml" => || Box::new(generated::mxml::MxmlLexer),
    "myghty" => || Box::new(generated::myghty::MyghtyLexer),
    "mysql" => || Box::new(generated::mysql::MysqlLexer),
    "nasm" => || Box::new(generated::nasm::NasmLexer),
    "nawk" => || Box::new(generated::awk::AwkLexer),
    "nb" => || Box::new(generated::mathematica::MathematicaLexer),
    "ncl" => || Box::new(generated::ncl::NclLexer),
    "nemerle" => || Box::new(generated::nemerle::NemerleLexer),
    "nesc" => || Box::new(generated::nesc::NescLexer),
    "nestedtext" => || Box::new(generated::nestedtext::NestedtextLexer),
    "newlisp" => || Box::new(generated::newlisp::NewlispLexer),
    "newspeak" => || Box::new(generated::newspeak::NewspeakLexer),
    "ng2" => || Box::new(generated::ng2::Ng2Lexer),
    "nginx" => || Box::new(generated::nginx::NginxLexer),
    "nim" => || Box::new(generated::nimrod::NimrodLexer),
    "nimrod" => || Box::new(generated::nimrod::NimrodLexer),
    "nit" => || Box::new(generated::nit::NitLexer),
    "nix" => || Box::new(generated::nixos::NixosLexer),
    "nixos" => || Box::new(generated::nixos::NixosLexer),
    "nroff" => || Box::new(generated::groff::GroffLexer),
    "nsh" => || Box::new(generated::nsis::NsisLexer),
    "nsi" => || Box::new(generated::nsis::NsisLexer),
    "nsis" => || Box::new(generated::nsis::NsisLexer),
    "nt" => || Box::new(generated::nestedtext::NestedtextLexer),
    "numba_ir" => || Box::new(generated::numba_ir::NumbaIrLexer),
    "numbair" => || Box::new(generated::numba_ir::NumbaIrLexer),
    "numpy" => || Box::new(generated::numpy::NumpyLexer),
    "nusmv" => || Box::new(generated::nusmv::NusmvLexer),
    "obj-c" => || Box::new(generated::objective_c::ObjectiveCLexer),
    "obj-c++" => || Box::new(generated::objective_cpp::ObjectiveCppLexer),
    "obj-j" => || Box::new(generated::objective_j::ObjectiveJLexer),
    "objc" => || Box::new(generated::objective_c::ObjectiveCLexer),
    "objc++" => || Box::new(generated::objective_cpp::ObjectiveCppLexer),
    "objdump" => || Box::new(generated::objdump::ObjdumpLexer),
    "objdump-nasm" => || Box::new(generated::objdump_nasm::ObjdumpNasmLexer),
    "objective-c" => || Box::new(generated::objective_c::ObjectiveCLexer),
    "objective-c++" => || Box::new(generated::objective_cpp::ObjectiveCppLexer),
    "objective-j" => || Box::new(generated::objective_j::ObjectiveJLexer),
    "objectivec" => || Box::new(generated::objective_c::ObjectiveCLexer),
    "objectivec++" => || Box::new(generated::objective_cpp::ObjectiveCppLexer),
    "objectivej" => || Box::new(generated::objective_j::ObjectiveJLexer),
    "objj" => || Box::new(generated::objective_j::ObjectiveJLexer),
    "ocaml" => || Box::new(generated::ocaml::OcamlLexer),
    "octave" => || Box::new(generated::octave::OctaveLexer),
    "odin" => || Box::new(generated::odin::OdinLexer),
    "omg-idl" => || Box::new(generated::omg_idl::OmgIdlLexer),
    "oobas" => || Box::new(generated::vb_net::VbNetLexer),
    "ooc" => || Box::new(generated::ooc::OocLexer),
    "opa" => || Box::new(generated::opa::OpaLexer),
    "openbugs" => || Box::new(generated::bugs::BugsLexer),
    "openrc" => || Box::new(generated::bash::BashLexer),
    "openedge" => || Box::new(generated::openedge::OpenedgeLexer),
    "openscad" => || Box::new(generated::openscad::OpenscadLexer),
    "org" => || Box::new(generated::org::OrgLexer),
    "org-mode" => || Box::new(generated::org::OrgLexer),
    "orgmode" => || Box::new(generated::org::OrgLexer),
    "pacmanconf" => || Box::new(generated::pacmanconf::PacmanconfLexer),
    "pan" => || Box::new(generated::pan::PanLexer),
    "parasail" => || Box::new(generated::parasail::ParasailLexer),
    "pawn" => || Box::new(generated::pawn::PawnLexer),
    "pcmk" => || Box::new(generated::crmsh::CrmshLexer),
    "pddl" => || Box::new(generated::pddl::PddlLexer),
    "peg" => || Box::new(generated::peg::PegLexer),
    "pem" => || Box::new(generated::asc::AscLexer),
    "perl" => || Box::new(generated::perl::PerlLexer),
    "phix" => || Box::new(generated::phix::PhixLexer),
    "php" => || Box::new(generated::php::PhpLexer),
    "php3" => || Box::new(generated::php::PhpLexer),
    "php4" => || Box::new(generated::php::PhpLexer),
    "php5" => || Box::new(generated::php::PhpLexer),
    "pig" => || Box::new(generated::pig::PigLexer),
    "pike" => || Box::new(generated::pike::PikeLexer),
    "pkgconfig" => || Box::new(generated::pkgconfig::PkgconfigLexer),
    "pl" => || Box::new(generated::perl::PerlLexer),
    "plain" => || Box::new(TextLexer),
    "po" => || Box::new(generated::gettext::GettextLexer),
    "pointless" => || Box::new(generated::pointless::PointlessLexer),
    "pony" => || Box::new(generated::pony::PonyLexer),
    "posh" => || Box::new(generated::powershell::PowershellLexer),
    "postgres-explain" => || Box::new(generated::postgres_explain::PostgresExplainLexer),
    "postscr" => || Box::new(generated::postscript::PostscriptLexer),
    "postscript" => || Box::new(generated::postscript::PostscriptLexer),
    "pot" => || Box::new(generated::gettext::GettextLexer),
    "pov" => || Box::new(generated::pov::PovLexer),
    "powershell" => || Box::new(generated::powershell::PowershellLexer),
    "praat" => || Box::new(generated::praat::PraatLexer),
    "procfile" => || Box::new(generated::procfile::ProcfileLexer),
    "progress" => || Box::new(generated::openedge::OpenedgeLexer),
    "prolog" => || Box::new(generated::prolog::PrologLexer),
    "promela" => || Box::new(generated::promela::PromelaLexer),
    "promql" => || Box::new(generated::promql::PromqlLexer),
    "properties" => || Box::new(generated::properties::PropertiesLexer),
    "proto" => || Box::new(generated::protobuf::ProtobufLexer),
    "protobuf" => || Box::new(generated::protobuf::ProtobufLexer),
    "prql" => || Box::new(generated::prql::PrqlLexer),
    "ps1" => || Box::new(generated::powershell::PowershellLexer),
    "psm1" => || Box::new(generated::powershell::PowershellLexer),
    "ptx" => || Box::new(generated::ptx::PtxLexer),
    "puppet" => || Box::new(generated::puppet::PuppetLexer),
    "purescript" => || Box::new(generated::purescript::PurescriptLexer),
    "purs" => || Box::new(generated::purescript::PurescriptLexer),
    "pwsh" => || Box::new(generated::powershell::PowershellLexer),
    "py" => || Box::new(PythonLexer),
    "py+ul4" => || Box::new(PythonUL4Lexer),
    "py2" => || Box::new(generated::python2::Python2Lexer),
    "py2tb" => || Box::new(generated::py2tb::Py2tbLexer),
    "py3" => || Box::new(PythonLexer),
    "py3tb" => || Box::new(generated::pytb::PytbLexer),
    "pypy" => || Box::new(generated::pypylog::PypylogLexer),
    "pypylog" => || Box::new(generated::pypylog::PypylogLexer),
    "pyrex" => || Box::new(generated::cython::CythonLexer),
    "pytb" => || Box::new(generated::pytb::PytbLexer),
    "python" => || Box::new(PythonLexer),
    "python2" => || Box::new(generated::python2::Python2Lexer),
    "python3" => || Box::new(PythonLexer),
    "pyx" => || Box::new(generated::cython::CythonLexer),
    "q" => || Box::new(generated::q::QLexer),
    "qbasic" => || Box::new(generated::qbasic::QbasicLexer),
    "qbs" => || Box::new(generated::qml::QmlLexer),
    "ql" => || Box::new(generated::codeql::CodeqlLexer),
    "qlik" => || Box::new(generated::qlik::QlikLexer),
    "qlikscript" => || Box::new(generated::qlik::QlikLexer),
    "qliksense" => || Box::new(generated::qlik::QlikLexer),
    "qlikview" => || Box::new(generated::qlik::QlikLexer),
    "qml" => || Box::new(generated::qml::QmlLexer),
    "qvt" => || Box::new(generated::qvto::QvtoLexer),
    "qvto" => || Box::new(generated::qvto::QvtoLexer),
    "r" => || Box::new(generated::r::RLexer),
    "racket" => || Box::new(generated::racket::RacketLexer),
    "ragel" => || Box::new(generated::ragel::RagelLexer),
    "ragel-c" => || Box::new(RagelCLexer),
    "ragel-cpp" => || Box::new(RagelCppLexer),
    "ragel-d" => || Box::new(RagelDLexer),
    "ragel-em" => || Box::new(generated::ragel_em::RagelEmLexer),
    "ragel-java" => || Box::new(RagelJavaLexer),
    "ragel-objc" => || Box::new(RagelObjectiveCLexer),
    "rd" => || Box::new(generated::rd::RdLexer),
    "react" => || Box::new(generated::jsx::JsxLexer),
    "reason" => || Box::new(generated::reasonml::ReasonmlLexer),
    "reasonml" => || Box::new(generated::reasonml::ReasonmlLexer),
    "redcode" => || Box::new(generated::redcode::RedcodeLexer),
    "registry" => || Box::new(generated::registry::RegistryLexer),
    "rego" => || Box::new(generated::rego::RegoLexer),
    "rell" => || Box::new(generated::rell::RellLexer),
    "resource" => || Box::new(generated::resourcebundle::ResourcebundleLexer),
    "resourcebundle" => || Box::new(generated::resourcebundle::ResourcebundleLexer),
    "rest" => || Box::new(generated::restructuredtext::RestructuredtextLexer),
    "restructuredtext" => || Box::new(generated::restructuredtext::RestructuredtextLexer),
    "rexx" => || Box::new(generated::rexx::RexxLexer),
    "ride" => || Box::new(generated::ride::RideLexer),
    "rita" => || Box::new(generated::rita::RitaLexer),
    "rkt" => || Box::new(generated::racket::RacketLexer),
    "rnc" => || Box::new(generated::rng_compact::RngCompactLexer),
    "rng-compact" => || Box::new(generated::rng_compact::RngCompactLexer),
    "roboconf-graph" => || Box::new(generated::roboconf_graph::RoboconfGraphLexer),
    "roboconf-instances" => || Box::new(generated::roboconf_instances::RoboconfInstancesLexer),
    "rocq" => || Box::new(generated::coq::CoqLexer),
    "rocq-prover" => || Box::new(generated::coq::CoqLexer),
    "rql" => || Box::new(generated::rql::RqlLexer),
    "rs" => || Box::new(generated::rust::RustLexer),
    "rsl" => || Box::new(generated::rsl::RslLexer),
    "rst" => || Box::new(generated::restructuredtext::RestructuredtextLexer),
    "rts" => || Box::new(generated::trafficscript::TrafficscriptLexer),
    "rust" => || Box::new(generated::rust::RustLexer),
    "s" => || Box::new(generated::r::RLexer),
    "salt" => || Box::new(YamlJinjaLexer),
    "sarl" => || Box::new(generated::sarl::SarlLexer),
    "sas" => || Box::new(generated::sas::SasLexer),
    "savi" => || Box::new(generated::savi::SaviLexer),
    "sbatch" => || Box::new(generated::slurm::SlurmLexer),
    "sc" => || Box::new(generated::supercollider::SupercolliderLexer),
    "scala" => || Box::new(generated::scala::ScalaLexer),
    "scd" => || Box::new(generated::scdoc::ScdocLexer),
    "scdoc" => || Box::new(generated::scdoc::ScdocLexer),
    "scilab" => || Box::new(generated::scilab::ScilabLexer),
    "scss" => || Box::new(generated::scss::ScssLexer),
    "sed" => || Box::new(generated::sed::SedLexer),
    "sgf" => || Box::new(generated::sgf::SgfLexer),
    "sh" => || Box::new(generated::bash::BashLexer),
    "shell" => || Box::new(generated::bash::BashLexer),
    "shen" => || Box::new(generated::shen::ShenLexer),
    "shex" => || Box::new(generated::shexc::ShexcLexer),
    "shexc" => || Box::new(generated::shexc::ShexcLexer),
    "sieve" => || Box::new(generated::sieve::SieveLexer),
    "silver" => || Box::new(generated::silver::SilverLexer),
    "singularity" => || Box::new(generated::singularity::SingularityLexer),
    "slurm" => || Box::new(generated::slurm::SlurmLexer),
    "smali" => || Box::new(generated::smali::SmaliLexer),
    "smalltalk" => || Box::new(generated::smalltalk::SmalltalkLexer),
    "smarty" => || Box::new(generated::smarty::SmartyLexer),
    "smithy" => || Box::new(generated::smithy::SmithyLexer),
    "snbt" => || Box::new(generated::snbt::SnbtLexer),
    "snobol" => || Box::new(generated::snobol::SnobolLexer),
    "sobas" => || Box::new(generated::vb_net::VbNetLexer),
    "solidity" => || Box::new(generated::solidity::SolidityLexer),
    "soong" => || Box::new(generated::androidbp::AndroidbpLexer),
    "sophia" => || Box::new(generated::sophia::SophiaLexer),
    "sources.list" => || Box::new(generated::debsources::DebsourcesLexer),
    "sourceslist" => || Box::new(generated::debsources::DebsourcesLexer),
    "sp" => || Box::new(generated::sp::SpLexer),
    "sparql" => || Box::new(generated::sparql::SparqlLexer),
    "spec" => || Box::new(generated::spec::SpecLexer),
    "spice" => || Box::new(generated::spice::SpiceLexer),
    "spicelang" => || Box::new(generated::spice::SpiceLexer),
    "spitfire" => || Box::new(generated::cheetah::CheetahLexer),
    "splus" => || Box::new(generated::r::RLexer),
    "sql" => || Box::new(generated::sql::SqlLexer),
    "sql+jinja" => || Box::new(SqlJinjaLexer),
    "squeak" => || Box::new(generated::smalltalk::SmalltalkLexer),
    "squid" => || Box::new(generated::squidconf::SquidconfLexer),
    "squid.conf" => || Box::new(generated::squidconf::SquidconfLexer),
    "squidconf" => || Box::new(generated::squidconf::SquidconfLexer),
    "srcinfo" => || Box::new(generated::srcinfo::SrcinfoLexer),
    "ssed" => || Box::new(generated::sed::SedLexer),
    "st" => || Box::new(generated::smalltalk::SmalltalkLexer),
    "stan" => || Box::new(generated::stan::StanLexer),
    "stata" => || Box::new(generated::stata::StataLexer),
    "supercollider" => || Box::new(generated::supercollider::SupercolliderLexer),
    "sv" => || Box::new(generated::systemverilog::SystemverilogLexer),
    "swift" => || Box::new(generated::swift::SwiftLexer),
    "swig" => || Box::new(generated::swig::SwigLexer),
    "systemd" => || Box::new(generated::systemd::SystemdLexer),
    "systemverilog" => || Box::new(generated::systemverilog::SystemverilogLexer),
    "t-sql" => || Box::new(generated::tsql::TsqlLexer),
    "tablegen" => || Box::new(generated::tablegen::TablegenLexer),
    "tact" => || Box::new(generated::tact::TactLexer),
    "tads3" => || Box::new(generated::tads3::Tads3Lexer),
    "tal" => || Box::new(generated::tal::TalLexer),
    "tap" => || Box::new(generated::tap::TapLexer),
    "tasm" => || Box::new(generated::tasm::TasmLexer),
    "tcl" => || Box::new(generated::tcl::TclLexer),
    "tcsh" => || Box::new(generated::tcsh::TcshLexer),
    "td" => || Box::new(generated::tablegen::TablegenLexer),
    "teal" => || Box::new(generated::teal::TealLexer),
    "teraterm" => || Box::new(generated::teratermmacro::TeratermmacroLexer),
    "teratermmacro" => || Box::new(generated::teratermmacro::TeratermmacroLexer),
    "termcap" => || Box::new(generated::termcap::TermcapLexer),
    "terminfo" => || Box::new(generated::terminfo::TerminfoLexer),
    "tex" => || Box::new(generated::tex::TexLexer),
    "text" => || Box::new(TextLexer),
    "thingsdb" => || Box::new(generated::ti::TiLexer),
    "thrift" => || Box::new(generated::thrift::ThriftLexer),
    "ti" => || Box::new(generated::ti::TiLexer),
    "tid" => || Box::new(generated::tid::TidLexer),
    "tlb" => || Box::new(generated::tlb::TlbLexer),
    "tls" => || Box::new(generated::tls::TlsLexer),
    "todotxt" => || Box::new(generated::todotxt::TodotxtLexer),
    "toml" => || Box::new(generated::toml::TomlLexer),
    "trac-wiki" => || Box::new(generated::trac_wiki::TracWikiLexer),
    "trafficscript" => || Box::new(generated::trafficscript::TrafficscriptLexer),
    "ts" => || Box::new(generated::typescript::TypescriptLexer),
    "tsql" => || Box::new(generated::tsql::TsqlLexer),
    "tsx" => || Box::new(generated::tsx::TsxLexer),
    "ttl" => || Box::new(generated::teratermmacro::TeratermmacroLexer),
    "turtle" => || Box::new(generated::turtle::TurtleLexer),
    "twig" => || Box::new(generated::twig::TwigLexer),
    "typescript" => || Box::new(generated::typescript::TypescriptLexer),
    "typoscript" => || Box::new(generated::typoscript::TyposcriptLexer),
    "typoscriptcssdata" => || Box::new(generated::typoscriptcssdata::TyposcriptcssdataLexer),
    "typoscripthtmldata" => || Box::new(generated::typoscripthtmldata::TyposcripthtmldataLexer),
    "typst" => || Box::new(generated::typst::TypstLexer),
    "ucode" => || Box::new(generated::ucode::UcodeLexer),
    "udiff" => || Box::new(DiffLexer),
    "ul4" => || Box::new(generated::ul4::Ul4Lexer),
    "unicon" => || Box::new(generated::unicon::UniconLexer),
    "unixconfig" => || Box::new(generated::unixconfig::UnixconfigLexer),
    "urlencoded" => || Box::new(generated::urlencoded::UrlencodedLexer),
    "usd" => || Box::new(generated::usd::UsdLexer),
    "usda" => || Box::new(generated::usd::UsdLexer),
    "uxntal" => || Box::new(generated::tal::TalLexer),
    "v" => || Box::new(generated::verilog::VerilogLexer),
    "vala" => || Box::new(generated::vala::ValaLexer),
    "vapi" => || Box::new(generated::vala::ValaLexer),
    "vb.net" => || Box::new(generated::vb_net::VbNetLexer),
    "vbnet" => || Box::new(generated::vb_net::VbNetLexer),
    "vbscript" => || Box::new(generated::vbscript::VbscriptLexer),
    "vcl" => || Box::new(generated::vcl::VclLexer),
    "vclsnippet" => || Box::new(generated::vclsnippets::VclsnippetsLexer),
    "vclsnippets" => || Box::new(generated::vclsnippets::VclsnippetsLexer),
    "vctreestatus" => || Box::new(generated::vctreestatus::VctreestatusLexer),
    "velocity" => || Box::new(generated::velocity::VelocityLexer),
    "verifpal" => || Box::new(generated::verifpal::VerifpalLexer),
    "verilog" => || Box::new(generated::verilog::VerilogLexer),
    "vfp" => || Box::new(generated::foxpro::FoxproLexer),
    "vgl" => || Box::new(generated::vgl::VglLexer),
    "vhdl" => || Box::new(generated::vhdl::VhdlLexer),
    "vim" => || Box::new(generated::vim::VimLexer),
    "visual-basic" => || Box::new(generated::vb_net::VbNetLexer),
    "visualbasic" => || Box::new(generated::vb_net::VbNetLexer),
    "visualprolog" => || Box::new(generated::visualprolog::VisualprologLexer),
    "visualprologgrammar" => || Box::new(generated::visualprologgrammar::VisualprologgrammarLexer),
    "vue" => || Box::new(generated::vue::VueLexer),
    "vyper" => || Box::new(generated::vyper::VyperLexer),
    "wast" => || Box::new(generated::wast::WastLexer),
    "wat" => || Box::new(generated::wast::WastLexer),
    "wdiff" => || Box::new(generated::wdiff::WdiffLexer),
    "webidl" => || Box::new(generated::webidl::WebidlLexer),
    "wgsl" => || Box::new(generated::wgsl::WgslLexer),
    "whiley" => || Box::new(generated::whiley::WhileyLexer),
    "winbatch" => || Box::new(generated::batch::BatchLexer),
    "winbugs" => || Box::new(generated::bugs::BugsLexer),
    "wl" => || Box::new(generated::mathematica::MathematicaLexer),
    "wolfram" => || Box::new(generated::mathematica::MathematicaLexer),
    "wowtoc" => || Box::new(generated::wowtoc::WowtocLexer),
    "wren" => || Box::new(generated::wren::WrenLexer),
    "x10" => || Box::new(generated::x10::X10Lexer),
    "xbase" => || Box::new(generated::foxpro::FoxproLexer),
    "xml" => || Box::new(generated::xml::XmlLexer),
    "xml+cheetah" => || Box::new(CheetahXmlLexer),
    "xml+django" => || Box::new(XmlDjangoLexer),
    "xml+evoque" => || Box::new(EvoqueXmlLexer),
    "xml+jinja" => || Box::new(XmlDjangoLexer),
    "xml+lasso" => || Box::new(LassoXmlLexer),
    "xml+mako" => || Box::new(MakoXmlLexer),
    "xml+myghty" => || Box::new(MyghtyXmlLexer),
    "xml+php" => || Box::new(XmlPhpLexer),
    "xml+smarty" => || Box::new(XmlSmartyLexer),
    "xml+spitfire" => || Box::new(CheetahXmlLexer),
    "xml+ul4" => || Box::new(XMLUL4Lexer),
    "xml+velocity" => || Box::new(VelocityXmlLexer),
    "xorg.conf" => || Box::new(generated::xorg_conf::XorgConfLexer),
    "xslt" => || Box::new(generated::xslt::XsltLexer),
    "xten" => || Box::new(generated::x10::X10Lexer),
    "xtend" => || Box::new(generated::xtend::XtendLexer),
    "xul+mozpreproc" => || Box::new(MozPreprocXulLexer),
    "yaml" => || Box::new(YamlLdLexer),
    "yaml+jinja" => || Box::new(YamlJinjaLexer),
    "yaml-ld" => || Box::new(YamlLdLexer),
    "yamlld" => || Box::new(YamlLdLexer),
    "yang" => || Box::new(generated::yang::YangLexer),
    "yar" => || Box::new(generated::yara::YaraLexer),
    "yara" => || Box::new(generated::yara::YaraLexer),
    "zeek" => || Box::new(generated::zeek::ZeekLexer),
    "zephir" => || Box::new(generated::zephir::ZephirLexer),
    "zetasql" => || Box::new(generated::googlesql::GooglesqlLexer),
    "zig" => || Box::new(generated::zig::ZigLexer),
    "zone" => || Box::new(generated::zone::ZoneLexer),
    "zsh" => || Box::new(generated::bash::BashLexer),
    "🔥" => || Box::new(generated::mojo::MojoLexer),
};

// Runtime-mutable registry for dynamically registered lexers (e.g., plugins, Python interop).
// Initialized lazily on first use with zero overhead if never accessed.
static RUNTIME_LEXERS: OnceLock<RwLock<HashMap<&'static str, LexerConstructor>>> = OnceLock::new();

fn get_runtime_registry() -> &'static RwLock<HashMap<&'static str, LexerConstructor>> {
    RUNTIME_LEXERS.get_or_init(|| RwLock::new(HashMap::new()))
}

/// Get a lexer by name, checking both compile-time and runtime registries.
///
/// **Performance**: O(1) for built-in lexers (perfect hash), O(1) average for runtime lexers.
///
/// # Arguments
///
/// * `alias` - Lexer name/alias (case-sensitive, e.g., "python", "json", "rust")
///
/// # Returns
///
/// `Some(Box<dyn Lexer>)` if the alias is registered, `None` otherwise.
///
/// # Examples
///
/// ```rust,ignore
/// // Get a built-in lexer (fast, lock-free)
/// if let Some(lexer) = get_lexer_by_name("python") {
///     let tokens = lexer.get_tokens("x = 42");
/// }
///
/// // Get a dynamically registered lexer
/// if let Some(lexer) = get_lexer_by_name("my-custom-lang") {
///     // Use the lexer
/// }
/// ```
pub fn get_lexer_by_name(alias: &str) -> Option<Box<dyn Lexer>> {
    // Fast path: check compile-time phf map first (O(1), zero-copy)
    if let Some(constructor) = LEXER_MAP.get(alias) {
        return Some(constructor());
    }

    // Fallback: check runtime registry for dynamically registered lexers
    if let Ok(registry) = get_runtime_registry().read() {
        if let Some(constructor) = registry.get(alias) {
            return Some(constructor());
        }
    }

    None
}

/// Register a lexer at runtime (for plugins, Python interop, etc.).
///
/// Lexers registered here become available via [`get_lexer_by_name`] and appear in [`native_aliases`].
/// Built-in lexer names cannot be overridden (to prevent accidental shadowing).
///
/// # Arguments
///
/// * `name` - Lexer alias to register (must have `'static` lifetime)
/// * `constructor` - Closure that constructs a `Box<dyn Lexer>`
///
/// # Errors
///
/// Returns `Err("Cannot override built-in lexer")` if `name` is already a built-in alias.
/// Returns `Err("Failed to acquire write lock...")` if the registry lock cannot be acquired.
///
/// # Thread Safety
///
/// This function acquires a write lock on the runtime registry. Multiple registrations
/// may block each other briefly, but reads remain unaffected.
///
/// # Examples
///
/// ```rust,ignore
/// use pygmentsrs::lexers::registry::register_lexer;
///
/// struct MyCustomLexer;
/// impl crate::lexer::Lexer for MyCustomLexer {
///     // ...
/// }
///
/// // Register a custom lexer
/// register_lexer("my-lang", || Box::new(MyCustomLexer))?;
///
/// // Now it's available
/// let lexer = get_lexer_by_name("my-lang")?;
/// ```
pub fn register_lexer(
    name: &'static str,
    constructor: LexerConstructor,
) -> Result<(), &'static str> {
    // Prevent runtime registration from shadowing built-ins
    if LEXER_MAP.contains_key(name) {
        return Err("Cannot override built-in lexer");
    }

    let mut registry = get_runtime_registry()
        .write()
        .map_err(|_| "Failed to acquire write lock on lexer registry")?;

    registry.insert(name, constructor);
    Ok(())
}

/// Unregister a dynamically registered lexer.
///
/// Built-in lexers cannot be unregistered (they remain available for the lifetime of the program).
///
/// # Arguments
///
/// * `name` - Name of the lexer to unregister
///
/// # Returns
///
/// `Some(constructor)` if the lexer was dynamically registered and successfully removed.
/// `None` if the alias is not found, is a built-in, or the write lock cannot be acquired.
///
/// # Examples
///
/// ```rust,ignore
/// use pygmentsrs::lexers::registry::{register_lexer, unregister_lexer, get_lexer_by_name};
///
/// // Register and then unregister
/// register_lexer("temp-lang", || Box::new(MyLexer))?;
/// assert!(get_lexer_by_name("temp-lang").is_some());
///
/// unregister_lexer("temp-lang");
/// assert!(get_lexer_by_name("temp-lang").is_none());
/// ```
pub fn unregister_lexer(name: &str) -> Option<LexerConstructor> {
    get_runtime_registry().write().ok()?.remove(name)
}

/// Advertise all available aliases (both built-in and runtime-registered).
///
/// This function returns the union of built-in lexer aliases and any dynamically registered ones.
/// Callers can use this to decide whether to short-circuit a PyO3 hop to upstream Pygments.
///
/// # Returns
///
/// A `Vec` of all registered lexer aliases (both compile-time and runtime).
///
/// # Examples
///
/// ```rust,ignore
/// use pygmentsrs::lexers::registry::{native_aliases, register_lexer};
///
/// let aliases = native_aliases();
/// assert!(aliases.contains(&"python"));  // Built-in
/// assert!(aliases.contains(&"py"));      // Built-in
///
/// // After registering a custom lexer
/// register_lexer("my-lang", || Box::new(MyLexer))?;
/// let aliases = native_aliases();
/// assert!(aliases.contains(&"my-lang")); // Now included
/// ```
pub fn native_aliases() -> Vec<&'static str> {
    let mut aliases = vec![
        "",
        "abap",
        "abl",
        "abnf",
        "aconf",
        "actionscript",
        "actionscript3",
        "ada",
        "ada2005",
        "ada95",
        "adl",
        "agda",
        "aheui",
        "ahk",
        "alloy",
        "ambienttalk",
        "ambienttalk/2",
        "amdgpu",
        "ampl",
        "androidbp",
        "ansys",
        "antlr",
        "antlr-actionscript",
        "antlr-as",
        "antlr-c#",
        "antlr-cpp",
        "antlr-csharp",
        "antlr-java",
        "antlr-objc",
        "antlr-perl",
        "antlr-python",
        "apache",
        "apacheconf",
        "apdl",
        "apl",
        "applescript",
        "arduino",
        "arexx",
        "arrow",
        "as",
        "as3",
        "asc",
        "asm",
        "asn1",
        "aspectj",
        "asy",
        "asymptote",
        "at",
        "augeas",
        "autohotkey",
        "autoit",
        "awk",
        "b3d",
        "bare",
        "basemake",
        "bash",
        "basic",
        "bat",
        "batch",
        "bbcbasic",
        "bbcode",
        "bc",
        "bdd",
        "be",
        "befunge",
        "berry",
        "bf",
        "bitbake",
        "blitzbasic",
        "blitzmax",
        "blueprint",
        "bmax",
        "bnf",
        "boa",
        "boo",
        "boogie",
        "bp",
        "bplus",
        "bqn",
        "brainfuck",
        "bro",
        "bst",
        "bst-pybtex",
        "bugs",
        "c",
        "c#",
        "c++",
        "c++-objdumb",
        "c-objdump",
        "ca65",
        "cadl",
        "camkes",
        "capdl",
        "capnp",
        "carbon",
        "cbmbas",
        "cddl",
        "cel",
        "ceylon",
        "cf3",
        "cfengine3",
        "cfg",
        "cfs",
        "chai",
        "chaiscript",
        "chapel",
        "charmci",
        "cheetah",
        "chpl",
        "cirru",
        "cl",
        "clay",
        "clean",
        "clipper",
        "clj",
        "cljs",
        "clojure",
        "clojurescript",
        "cmake",
        "cobol",
        "cobolfree",
        "codeql",
        "coffee",
        "coffee-script",
        "coffeescript",
        "comal",
        "comal80",
        "common-lisp",
        "componentpascal",
        "control",
        "coq",
        "cp",
        "cplint",
        "cpp",
        "cpp-objdump",
        "cpsa",
        "crmsh",
        "croc",
        "cry",
        "cryptol",
        "cs",
        "csh",
        "csharp",
        "csound-csd",
        "csound-document",
        "csound-sco",
        "csound-score",
        "css",
        "css+django",
        "css+genshi",
        "css+genshitext",
        "css+jinja",
        "css+lasso",
        "css+mako",
        "css+mozpreproc",
        "css+myghty",
        "css+php",
        "css+smarty",
        "css+ul4",
        "cu",
        "cucumber",
        "cuda",
        "cypher",
        "cython",
        "d",
        "d-objdump",
        "dart",
        "dax",
        "debcontrol",
        "debian.sources",
        "debsources",
        "desktop",
        "devicetree",
        "dg",
        "diff",
        "django",
        "dmesg",
        "do",
        "docker",
        "dockerfile",
        "dosbatch",
        "dosini",
        "dot",
        "dpatch",
        "dtd",
        "dts",
        "duel",
        "dylan",
        "dylan-lid",
        "earl-grey",
        "earlgrey",
        "easytrieve",
        "ebnf",
        "ec",
        "ecl",
        "eg",
        "eiffel",
        "elisp",
        "elixir",
        "elm",
        "elpi",
        "emacs",
        "emacs-lisp",
        "erlang",
        "evoque",
        "ex",
        "execline",
        "exs",
        "extempore",
        "ezhil",
        "f#",
        "f90",
        "factor",
        "fan",
        "fancy",
        "fc",
        "felix",
        "fennel",
        "fif",
        "fift",
        "fish",
        "fishshell",
        "flatline",
        "flo",
        "floscript",
        "flx",
        "fnl",
        "forth",
        "fortran",
        "foxpro",
        "freefem",
        "fsharp",
        "fstar",
        "func",
        "futhark",
        "fy",
        "gap",
        "gas",
        "gawk",
        "gcode",
        "gd",
        "gdscript",
        "genshitext",
        "gherkin",
        "gleam",
        "glsl",
        "gnuplot",
        "go",
        "golang",
        "golo",
        "gooddata-cl",
        "googlesql",
        "gosu",
        "graphql",
        "graphviz",
        "groff",
        "groovy",
        "gsed",
        "gsql",
        "handlebars",
        "hare",
        "haskell",
        "haxeml",
        "hexdump",
        "hlsl",
        "hs",
        "hsa",
        "hsail",
        "hspec",
        "html",
        "html+cheetah",
        "html+django",
        "html+evoque",
        "html+handlebars",
        "html+jinja",
        "html+lasso",
        "html+mako",
        "html+myghty",
        "html+ng2",
        "html+php",
        "html+smarty",
        "html+spitfire",
        "html+twig",
        "html+ul4",
        "html+velocity",
        "hxml",
        "hy",
        "hybris",
        "hylang",
        "i6",
        "i6t",
        "i7",
        "icon",
        "idl",
        "idl4",
        "idr",
        "idris",
        "igor",
        "igorpro",
        "ik",
        "inform6",
        "inform7",
        "ini",
        "io",
        "ioke",
        "irc",
        "isabelle",
        "j",
        "jags",
        "janet",
        "jasmin",
        "jasminxt",
        "java",
        "javascript",
        "javascript+cheetah",
        "javascript+django",
        "javascript+lasso",
        "javascript+mako",
        "javascript+mozpreproc",
        "javascript+myghty",
        "javascript+php",
        "javascript+smarty",
        "jbst",
        "jcl",
        "jinja",
        "jl",
        "jmespath",
        "jp",
        "jproperties",
        "js",
        "js+cheetah",
        "js+django",
        "js+genshi",
        "js+genshitext",
        "js+lasso",
        "js+mako",
        "js+myghty",
        "js+php",
        "js+smarty",
        "js+ul4",
        "jsgf",
        "jslt",
        "json",
        "json-ld",
        "json-object",
        "json5",
        "jsonld",
        "jsonml+bst",
        "jsonnet",
        "jsx",
        "julia",
        "juttle",
        "k",
        "kal",
        "kconfig",
        "kernel-config",
        "kmsg",
        "koka",
        "kotlin",
        "kql",
        "ksh",
        "kuin",
        "kusto",
        "lasso",
        "lassoscript",
        "latex",
        "ldapconf",
        "ldaprc",
        "ldif",
        "lean",
        "lean3",
        "lean4",
        "less",
        "lid",
        "lighttpd",
        "lighty",
        "limbo",
        "linux-config",
        "linuxconfig",
        "liquid",
        "lisp",
        "live-script",
        "livescript",
        "llvm",
        "llvm-mir",
        "llvm-mir-body",
        "lobas",
        "logos",
        "logtalk",
        "lsl",
        "lua",
        "luau",
        "m2",
        "macaulay2",
        "macsyma",
        "mako",
        "man",
        "maql",
        "markdown",
        "mask",
        "mason",
        "mathematica",
        "matlab",
        "mawk",
        "maxima",
        "mcf",
        "mcfunction",
        "mcschema",
        "md",
        "menuconfig",
        "meson",
        "meson.build",
        "minid",
        "miniscript",
        "mips",
        "mma",
        "modelica",
        "modula2",
        "moin",
        "mojo",
        "monkey",
        "monte",
        "moo",
        "moocode",
        "moon",
        "moonscript",
        "mosel",
        "mozhashpreproc",
        "mozpercentpreproc",
        "mq4",
        "mq5",
        "mql",
        "mql4",
        "mql5",
        "ms",
        "msc",
        "mscgen",
        "mupad",
        "mxml",
        "myghty",
        "mysql",
        "nasm",
        "nawk",
        "nb",
        "ncl",
        "nemerle",
        "nesc",
        "nestedtext",
        "newlisp",
        "newspeak",
        "ng2",
        "nginx",
        "nim",
        "nimrod",
        "nit",
        "nix",
        "nixos",
        "nroff",
        "nsh",
        "nsi",
        "nsis",
        "nt",
        "numba_ir",
        "numbair",
        "numpy",
        "nusmv",
        "obj-c",
        "obj-c++",
        "obj-j",
        "objc",
        "objc++",
        "objdump",
        "objdump-nasm",
        "objective-c",
        "objective-c++",
        "objective-j",
        "objectivec",
        "objectivec++",
        "objectivej",
        "objj",
        "ocaml",
        "octave",
        "odin",
        "omg-idl",
        "oobas",
        "ooc",
        "opa",
        "openbugs",
        "openedge",
        "openrc",
        "openscad",
        "org",
        "org-mode",
        "orgmode",
        "pacmanconf",
        "pan",
        "parasail",
        "pawn",
        "pcmk",
        "pddl",
        "peg",
        "pem",
        "perl",
        "phix",
        "php",
        "php3",
        "php4",
        "php5",
        "pig",
        "pike",
        "pkgconfig",
        "pl",
        "plain",
        "po",
        "pointless",
        "pony",
        "posh",
        "postgres-explain",
        "postscr",
        "postscript",
        "pot",
        "pov",
        "powershell",
        "praat",
        "procfile",
        "progress",
        "prolog",
        "promela",
        "promql",
        "properties",
        "proto",
        "protobuf",
        "prql",
        "ps1",
        "psm1",
        "ptx",
        "puppet",
        "purescript",
        "purs",
        "pwsh",
        "py",
        "py+ul4",
        "py2",
        "py2tb",
        "py3",
        "py3tb",
        "pypy",
        "pypylog",
        "pyrex",
        "pytb",
        "python",
        "python2",
        "python3",
        "pyx",
        "q",
        "qbasic",
        "qbs",
        "ql",
        "qlik",
        "qlikscript",
        "qliksense",
        "qlikview",
        "qml",
        "qvt",
        "qvto",
        "r",
        "racket",
        "ragel",
        "ragel-c",
        "ragel-cpp",
        "ragel-d",
        "ragel-em",
        "ragel-java",
        "ragel-objc",
        "rd",
        "react",
        "reason",
        "reasonml",
        "redcode",
        "registry",
        "rego",
        "rell",
        "resource",
        "resourcebundle",
        "rest",
        "restructuredtext",
        "rexx",
        "ride",
        "rita",
        "rkt",
        "rnc",
        "rng-compact",
        "roboconf-graph",
        "roboconf-instances",
        "rocq",
        "rocq-prover",
        "rql",
        "rs",
        "rsl",
        "rst",
        "rts",
        "rust",
        "s",
        "salt",
        "sarl",
        "sas",
        "savi",
        "sbatch",
        "sc",
        "scala",
        "scd",
        "scdoc",
        "scilab",
        "scss",
        "sed",
        "sgf",
        "sh",
        "shell",
        "shen",
        "shex",
        "shexc",
        "sieve",
        "silver",
        "singularity",
        "sls",
        "slurm",
        "smali",
        "smalltalk",
        "smarty",
        "smithy",
        "snbt",
        "snobol",
        "sobas",
        "solidity",
        "soong",
        "sophia",
        "sources.list",
        "sourceslist",
        "sp",
        "sparql",
        "spec",
        "spice",
        "spicelang",
        "spitfire",
        "splus",
        "sql",
        "sql+jinja",
        "squeak",
        "squid",
        "squid.conf",
        "squidconf",
        "srcinfo",
        "ssed",
        "st",
        "stan",
        "stata",
        "supercollider",
        "sv",
        "swift",
        "swig",
        "systemd",
        "systemverilog",
        "t-sql",
        "tablegen",
        "tact",
        "tads3",
        "tal",
        "tap",
        "tasm",
        "tcl",
        "tcsh",
        "td",
        "teal",
        "teraterm",
        "teratermmacro",
        "termcap",
        "terminfo",
        "tex",
        "text",
        "thingsdb",
        "thrift",
        "ti",
        "tid",
        "tlb",
        "tls",
        "todotxt",
        "toml",
        "trac-wiki",
        "trafficscript",
        "ts",
        "tsql",
        "tsx",
        "ttl",
        "turtle",
        "twig",
        "typescript",
        "typoscript",
        "typoscriptcssdata",
        "typoscripthtmldata",
        "typst",
        "ucode",
        "udiff",
        "ul4",
        "unicon",
        "unixconfig",
        "urlencoded",
        "usd",
        "usda",
        "uxntal",
        "v",
        "vala",
        "vapi",
        "vb.net",
        "vbnet",
        "vbscript",
        "vcl",
        "vclsnippet",
        "vclsnippets",
        "vctreestatus",
        "velocity",
        "verifpal",
        "verilog",
        "vfp",
        "vgl",
        "vhdl",
        "vim",
        "visual-basic",
        "visualbasic",
        "visualprolog",
        "visualprologgrammar",
        "vue",
        "vyper",
        "wast",
        "wat",
        "wdiff",
        "webidl",
        "wgsl",
        "whiley",
        "winbatch",
        "winbugs",
        "wl",
        "wolfram",
        "wowtoc",
        "wren",
        "x++",
        "x10",
        "xbase",
        "xml",
        "xml+cheetah",
        "xml+django",
        "xml+evoque",
        "xml+jinja",
        "xml+lasso",
        "xml+mako",
        "xml+myghty",
        "xml+php",
        "xml+smarty",
        "xml+spitfire",
        "xml+ul4",
        "xml+velocity",
        "xorg.conf",
        "xpp",
        "xslt",
        "xten",
        "xtend",
        "xul+mozpreproc",
        "yaml",
        "yaml+jinja",
        "yaml-ld",
        "yamlld",
        "yang",
        "yar",
        "yara",
        "zeek",
        "zephir",
        "zetasql",
        "zig",
        "zone",
        "zsh",
        "🔥",
    ];

    // Include any dynamically registered aliases
    if let Ok(registry) = get_runtime_registry().read() {
        aliases.extend(registry.keys().copied());
    }

    aliases
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::token;

    /// Mock lexer for testing runtime registration.
    struct MockLexer;

    impl Lexer for MockLexer {
        fn get_tokens(&self, _code: &str) -> Vec<(token::TokenType, String)> {
            vec![(token::TEXT, String::from("mock"))]
        }
    }

    #[test]
    fn test_builtin_lexer_lookup() {
        // Built-in lexers should be found via perfect hash
        let python = get_lexer_by_name("python");
        assert!(python.is_some(), "Built-in 'python' lexer should be found");

        let json = get_lexer_by_name("json");
        assert!(json.is_some(), "Built-in 'json' lexer should be found");

        let rust = get_lexer_by_name("rust");
        assert!(rust.is_some(), "Built-in 'rust' lexer should be found");
    }

    #[test]
    fn test_unknown_lexer_not_found() {
        // Unknown lexers should not be found
        let unknown = get_lexer_by_name("definitely-not-a-real-lexer-xyz");
        assert!(unknown.is_none(), "Unknown lexer should not be found");
    }

    #[test]
    fn test_register_and_lookup_dynamic_lexer() {
        // Register a custom lexer
        let result = register_lexer("test-mock-lang", || Box::new(MockLexer));
        assert!(result.is_ok(), "Registration should succeed");

        // Should now be findable
        let lexer = get_lexer_by_name("test-mock-lang");
        assert!(
            lexer.is_some(),
            "Dynamically registered lexer should be found"
        );

        // Cleanup
        unregister_lexer("test-mock-lang");
    }

    #[test]
    fn test_prevent_builtin_override() {
        // Should not be able to override a built-in
        let result = register_lexer("python", || Box::new(MockLexer));
        assert!(
            result.is_err(),
            "Should not be able to override built-in 'python'"
        );
        assert_eq!(
            result.err(),
            Some("Cannot override built-in lexer"),
            "Error message should indicate built-in override attempt"
        );
    }

    #[test]
    fn test_unregister_lexer() {
        // Register a lexer
        let _ = register_lexer("temp-test-lang", || Box::new(MockLexer));
        assert!(
            get_lexer_by_name("temp-test-lang").is_some(),
            "Lexer should exist after registration"
        );

        // Unregister it
        let constructor = unregister_lexer("temp-test-lang");
        assert!(
            constructor.is_some(),
            "unregister_lexer should return the constructor"
        );

        // Should no longer be found
        let lexer = get_lexer_by_name("temp-test-lang");
        assert!(
            lexer.is_none(),
            "Lexer should not be found after unregistration"
        );
    }

    #[test]
    fn test_unregister_nonexistent_lexer() {
        // Unregistering a non-existent lexer should return None
        let result = unregister_lexer("definitely-not-registered-xyz");
        assert!(
            result.is_none(),
            "Unregistering non-existent lexer should return None"
        );
    }

    #[test]
    fn test_unregister_builtin_lexer() {
        // Cannot unregister a built-in lexer
        let result = unregister_lexer("python");
        assert!(
            result.is_none(),
            "Cannot unregister built-in lexer (should return None)"
        );

        // Built-in should still be available
        assert!(
            get_lexer_by_name("python").is_some(),
            "Built-in lexer should still be available"
        );
    }

    #[test]
    fn test_native_aliases_includes_builtins() {
        // Should include common built-in aliases
        let aliases = native_aliases();
        assert!(aliases.contains(&"python"), "Should include 'python'");
        assert!(aliases.contains(&"py"), "Should include 'py'");
        assert!(aliases.contains(&"json"), "Should include 'json'");
        assert!(aliases.contains(&"rust"), "Should include 'rust'");
        assert!(aliases.contains(&"rs"), "Should include 'rs'");
    }

    #[test]
    fn test_native_aliases_includes_dynamic() {
        // Register a custom lexer
        let _ = register_lexer("test-alias-check", || Box::new(MockLexer));

        // Aliases should now include the custom lexer
        let aliases = native_aliases();
        assert!(
            aliases.contains(&"test-alias-check"),
            "Should include dynamically registered lexer"
        );

        // Cleanup
        unregister_lexer("test-alias-check");
    }

    #[test]
    fn test_multiple_dynamic_registrations() {
        // Register multiple lexers
        let _ = register_lexer("test-lang-a", || Box::new(MockLexer));
        let _ = register_lexer("test-lang-b", || Box::new(MockLexer));

        // Both should be findable
        assert!(
            get_lexer_by_name("test-lang-a").is_some(),
            "First lexer should be found"
        );
        assert!(
            get_lexer_by_name("test-lang-b").is_some(),
            "Second lexer should be found"
        );

        // Both should be in aliases
        let aliases = native_aliases();
        assert!(aliases.contains(&"test-lang-a"));
        assert!(aliases.contains(&"test-lang-b"));

        // Cleanup
        unregister_lexer("test-lang-a");
        unregister_lexer("test-lang-b");
    }

    #[test]
    fn test_register_duplicate_dynamic_lexer() {
        // Register a lexer
        let _ = register_lexer("test-duplicate", || Box::new(MockLexer));

        // Try to register the same one again (should succeed, overwriting the old one)
        let result = register_lexer("test-duplicate", || Box::new(MockLexer));
        assert!(
            result.is_ok(),
            "Re-registering dynamic lexer should succeed (no shadowing issue)"
        );

        // Should still be findable
        assert!(get_lexer_by_name("test-duplicate").is_some());

        // Cleanup
        unregister_lexer("test-duplicate");
    }

    #[test]
    fn test_lexer_case_sensitivity() {
        // Lexer names are case-sensitive
        let python_lower = get_lexer_by_name("python");
        let python_upper = get_lexer_by_name("PYTHON");

        assert!(python_lower.is_some(), "Lowercase 'python' should be found");
        assert!(
            python_upper.is_none(),
            "Uppercase 'PYTHON' should not be found (case-sensitive)"
        );
    }

    #[test]
    fn test_concurrent_access_simulation() {
        // Simple test to ensure concurrent-like access doesn't panic
        // (Note: This is not a true concurrency test; actual concurrency
        // testing would require using std::thread or tokio)

        // Register a lexer
        let _ = register_lexer("test-concurrent", || Box::new(MockLexer));

        // Simulate multiple accesses
        for _ in 0..10 {
            let _ = get_lexer_by_name("test-concurrent");
            let _ = native_aliases();
        }

        // Unregister
        let _ = unregister_lexer("test-concurrent");
    }
}
