//! Lexer alias → lexer instance resolution.
//!
//! Mirrors `pygments.lexers.get_lexer_by_name`. New lexers register
//! their aliases by extending both [`get_lexer_by_name`] and
//! [`native_aliases`] (the latter advertises which aliases the
//! native path handles, so callers can decide whether to short-circuit
//! a PyO3 hop).

use crate::lexer::Lexer;
use crate::lexers::diff::DiffLexer;
use crate::lexers::generated;
use crate::lexers::json::JsonLexer;
use crate::lexers::python::PythonLexer;
use crate::lexers::text::TextLexer;

pub fn get_lexer_by_name(alias: &str) -> Option<Box<dyn Lexer>> {
    match alias {
        "text" | "plain" | "" => Some(Box::new(TextLexer)),
        "python" | "py" | "python3" | "py3" => Some(Box::new(PythonLexer)),
        "json" | "json-object" => Some(Box::new(JsonLexer)),
        "diff" | "udiff" => Some(Box::new(DiffLexer)),
        // --- transpiled (tools/gen_lexer.py) ---
        "ini" | "cfg" | "dosini" => Some(Box::new(generated::ini::IniLexer)),
        "properties" | "jproperties" => {
            Some(Box::new(generated::properties::PropertiesLexer))
        }
        "toml" => Some(Box::new(generated::toml::TomlLexer)),
        "pot" | "po" => Some(Box::new(generated::gettext::GettextLexer)),
        "dpatch" => Some(Box::new(generated::darcs::DarcsLexer)),
        "vctreestatus" => Some(Box::new(generated::vctreestatus::VctreestatusLexer)),
        "groff" | "nroff" | "man" => Some(Box::new(generated::groff::GroffLexer)),
        "bash" | "sh" | "ksh" | "zsh" | "shell" | "openrc" => {
            Some(Box::new(generated::bash::BashLexer))
        }
        "cmake" => Some(Box::new(generated::cmake::CmakeLexer)),
        // --- Phase B: config/markup/template formats ---
        "augeas" => Some(Box::new(generated::augeas::AugeasLexer)),
        "bbcode" => Some(Box::new(generated::bbcode::BbcodeLexer)),
        "desktop" => Some(Box::new(generated::desktop::DesktopLexer)),
        "lighttpd" | "lighty" => Some(Box::new(generated::lighttpd::LighttpdLexer)),
        "pacmanconf" => Some(Box::new(generated::pacmanconf::PacmanconfLexer)),
        "pkgconfig" => Some(Box::new(generated::pkgconfig::PkgconfigLexer)),
        "registry" => Some(Box::new(generated::registry::RegistryLexer)),
        "mozhashpreproc" => Some(Box::new(generated::moz_hashpreproc::MozHashpreprocLexer)),
        "mozpercentpreproc" => Some(Box::new(generated::moz_percentpreproc::MozPercentpreprocLexer)),
        "debian.sources" => Some(Box::new(generated::debian_sources::DebianSourcesLexer)),
        "django" | "jinja" => Some(Box::new(generated::django::DjangoLexer)),
        "ng2" => Some(Box::new(generated::ng2::Ng2Lexer)),
        "cfengine3" | "cf3" => Some(Box::new(generated::cfengine3::Cfengine3Lexer)),
        "cfs" => Some(Box::new(generated::cfs::CfsLexer)),
        // --- Phase B batch 2: more configs, installers, templates ---
        "debcontrol" | "control" => Some(Box::new(generated::debcontrol::DebcontrolLexer)),
        "debsources" | "sourceslist" | "sources.list" => Some(Box::new(generated::debsources::DebsourcesLexer)),
        "kconfig" | "menuconfig" | "linux-config" | "kernel-config" => Some(Box::new(generated::kconfig::KconfigLexer)),
        "systemd" => Some(Box::new(generated::systemd::SystemdLexer)),
        "termcap" => Some(Box::new(generated::termcap::TermcapLexer)),
        "terminfo" => Some(Box::new(generated::terminfo::TerminfoLexer)),
        "twig" => Some(Box::new(generated::twig::TwigLexer)),
        "velocity" => Some(Box::new(generated::velocity::VelocityLexer)),
        // --- Phase A: high-value doc/Sphinx languages ---
        "rust" | "rs" => Some(Box::new(generated::rust::RustLexer)),
        "go" | "golang" => Some(Box::new(generated::go::GoLexer)),
        "javascript" | "js" => Some(Box::new(generated::javascript::JavascriptLexer)),
        "swift" => Some(Box::new(generated::swift::SwiftLexer)),
        "perl" | "pl" => Some(Box::new(generated::perl::PerlLexer)),
        "haskell" | "hs" => Some(Box::new(generated::haskell::HaskellLexer)),
        "elixir" | "ex" | "exs" => Some(Box::new(generated::elixir::ElixirLexer)),
        "typescript" | "ts" => Some(Box::new(generated::typescript::TypescriptLexer)),
        "css" => Some(Box::new(generated::css::CssLexer)),
        "xml" => Some(Box::new(generated::xml::XmlLexer)),
        "sql" => Some(Box::new(generated::sql::SqlLexer)),
        "lua" => Some(Box::new(generated::lua::LuaLexer)),
        "splus" | "s" | "r" => Some(Box::new(generated::r::RLexer)),
        "matlab" => Some(Box::new(generated::matlab::MatlabLexer)),
        "julia" | "jl" => Some(Box::new(generated::julia::JuliaLexer)),
        "clojure" | "clj" => Some(Box::new(generated::clojure::ClojureLexer)),
        "erlang" => Some(Box::new(generated::erlang::ErlangLexer)),
        "nginx" => Some(Box::new(generated::nginx::NginxLexer)),
        "apacheconf" | "aconf" | "apache" => Some(Box::new(generated::apache::ApacheLexer)),
        "powershell" | "pwsh" | "posh" | "ps1" | "psm1" => Some(Box::new(generated::powershell::PowershellLexer)),
        "tex" | "latex" => Some(Box::new(generated::tex::TexLexer)),
        "graphql" => Some(Box::new(generated::graphql::GraphqlLexer)),
        "protobuf" | "proto" => Some(Box::new(generated::protobuf::ProtobufLexer)),
        "scala" => Some(Box::new(generated::scala::ScalaLexer)),
        // --- Phase C batch 1: scripting, DSL, business, basic, lisp ---
        "applescript" => Some(Box::new(generated::applescript::ApplescriptLexer)),
        "chaiscript" | "chai" => Some(Box::new(generated::chaiscript::ChaiscriptLexer)),
        "moonscript" | "moon" => Some(Box::new(generated::moonscript::MoonscriptLexer)),
        "alloy" => Some(Box::new(generated::alloy::AlloyLexer)),
        "arrow" => Some(Box::new(generated::arrow::ArrowLexer)),
        "awk" | "gawk" | "mawk" | "nawk" => Some(Box::new(generated::awk::AwkLexer)),
        "bdd" => Some(Box::new(generated::bdd::BddLexer)),
        "abap" => Some(Box::new(generated::abap::AbapLexer)),
        "maql" => Some(Box::new(generated::maql::MaqlLexer)),
        "bbcbasic" => Some(Box::new(generated::bbcbasic::BbcbasicLexer)),
        "blitzmax" | "bmax" => Some(Box::new(generated::blitzmax::BlitzmaxLexer)),
        "newlisp" => Some(Box::new(generated::newlisp::NewlispLexer)),
        "racket" | "rkt" => Some(Box::new(generated::racket::RacketLexer)),
        // --- Phase D: using(this) / using(OtherLexer) lexers ---
        "fortran" | "f90" => Some(Box::new(generated::fortran::FortranLexer)),
        "ampl" => Some(Box::new(generated::ampl::AmplLexer)),
        "typoscriptcssdata" => Some(Box::new(generated::typoscriptcssdata::TyposcriptcssdataLexer)),
        "typoscripthtmldata" => Some(Box::new(generated::typoscripthtmldata::TyposcripthtmldataLexer)),
        "typoscript" => Some(Box::new(generated::typoscript::TyposcriptLexer)),

        // --- bulk transpiled ---
"abnf" => Some(Box::new(generated::abnf::AbnfLexer)),
        "actionscript" | "as" => Some(Box::new(generated::actionscript::ActionscriptLexer)),
        "actionscript3" | "as3" => Some(Box::new(generated::actionscript3::Actionscript3Lexer)),
        "ada" | "ada95" | "ada2005" => Some(Box::new(generated::ada::AdaLexer)),
        "agda" => Some(Box::new(generated::agda::AgdaLexer)),
        "aheui" => Some(Box::new(generated::aheui::AheuiLexer)),
        "ambienttalk" | "ambienttalk/2" | "at" => Some(Box::new(generated::ambienttalk::AmbienttalkLexer)),
        "amdgpu" => Some(Box::new(generated::amdgpu::AmdgpuLexer)),
        "androidbp" | "bp" | "soong" => Some(Box::new(generated::androidbp::AndroidbpLexer)),
        "ansys" | "apdl" => Some(Box::new(generated::ansys::AnsysLexer)),
        "antlr" => Some(Box::new(generated::antlr::AntlrLexer)),
        "apl" => Some(Box::new(generated::apl::AplLexer)),
        "arduino" => Some(Box::new(generated::arduino::ArduinoLexer)),
        "asc" | "pem" => Some(Box::new(generated::asc::AscLexer)),
        "asn1" => Some(Box::new(generated::asn1::Asn1Lexer)),
        "aspectj" => Some(Box::new(generated::aspectj::AspectjLexer)),
        "asymptote" | "asy" => Some(Box::new(generated::asymptote::AsymptoteLexer)),
        "autohotkey" | "ahk" => Some(Box::new(generated::autohotkey::AutohotkeyLexer)),
        "autoit" => Some(Box::new(generated::autoit::AutoitLexer)),
        "bare" => Some(Box::new(generated::bare::BareLexer)),
        "basemake" => Some(Box::new(generated::basemake::BasemakeLexer)),
        "batch" | "bat" | "dosbatch" | "winbatch" => Some(Box::new(generated::batch::BatchLexer)),
        "bc" => Some(Box::new(generated::bc::BcLexer)),
        "befunge" => Some(Box::new(generated::befunge::BefungeLexer)),
        "berry" | "be" => Some(Box::new(generated::berry::BerryLexer)),
        "blitzbasic" | "b3d" | "bplus" => Some(Box::new(generated::blitzbasic::BlitzbasicLexer)),
        "blueprint" => Some(Box::new(generated::blueprint::BlueprintLexer)),
        "bnf" => Some(Box::new(generated::bnf::BnfLexer)),
        "boa" => Some(Box::new(generated::boa::BoaLexer)),
        "boo" => Some(Box::new(generated::boo::BooLexer)),
        "boogie" => Some(Box::new(generated::boogie::BoogieLexer)),
        "bqn" => Some(Box::new(generated::bqn::BqnLexer)),
        "brainfuck" | "bf" => Some(Box::new(generated::brainfuck::BrainfuckLexer)),
        "bst" | "bst-pybtex" => Some(Box::new(generated::bst::BstLexer)),
        "bugs" | "winbugs" | "openbugs" => Some(Box::new(generated::bugs::BugsLexer)),
        "c" => Some(Box::new(generated::c::CLexer)),
        "ca65" => Some(Box::new(generated::ca65::Ca65Lexer)),
        "cadl" => Some(Box::new(generated::cadl::CadlLexer)),
        "camkes" | "idl4" => Some(Box::new(generated::camkes::CamkesLexer)),
        "capdl" => Some(Box::new(generated::capdl::CapdlLexer)),
        "capnp" => Some(Box::new(generated::capnp::CapnpLexer)),
        "carbon" => Some(Box::new(generated::carbon::CarbonLexer)),
        "cbmbas" => Some(Box::new(generated::cbmbas::CbmbasLexer)),
        "cddl" => Some(Box::new(generated::cddl::CddlLexer)),
        "ceylon" => Some(Box::new(generated::ceylon::CeylonLexer)),
        "chapel" | "chpl" => Some(Box::new(generated::chapel::ChapelLexer)),
        "charmci" => Some(Box::new(generated::charmci::CharmciLexer)),
        "cheetah" | "spitfire" => Some(Box::new(generated::cheetah::CheetahLexer)),
        "cirru" => Some(Box::new(generated::cirru::CirruLexer)),
        "clay" => Some(Box::new(generated::clay::ClayLexer)),
        "clean" => Some(Box::new(generated::clean::CleanLexer)),
        "clojurescript" | "cljs" => Some(Box::new(generated::clojurescript::ClojurescriptLexer)),
        "cobol" => Some(Box::new(generated::cobol::CobolLexer)),
        "cobolfree" => Some(Box::new(generated::cobolfree::CobolfreeLexer)),
        "codeql" | "ql" => Some(Box::new(generated::codeql::CodeqlLexer)),
        "coffeescript" | "coffee-script" | "coffee" => Some(Box::new(generated::coffeescript::CoffeescriptLexer)),
        "comal" | "comal80" => Some(Box::new(generated::comal::ComalLexer)),
        "common-lisp" | "cl" | "lisp" => Some(Box::new(generated::common_lisp::CommonLispLexer)),
        "componentpascal" | "cp" => Some(Box::new(generated::componentpascal::ComponentpascalLexer)),
        "coq" | "rocq" | "rocq-prover" => Some(Box::new(generated::coq::CoqLexer)),
        "cplint" => Some(Box::new(generated::cplint::CplintLexer)),
        "cpp" | "c++" => Some(Box::new(generated::cpp::CppLexer)),
        "cpsa" => Some(Box::new(generated::cpsa::CpsaLexer)),
        "crmsh" | "pcmk" => Some(Box::new(generated::crmsh::CrmshLexer)),
        "croc" => Some(Box::new(generated::croc::CrocLexer)),
        "cryptol" | "cry" => Some(Box::new(generated::cryptol::CryptolLexer)),
        "csound-score" | "csound-sco" => Some(Box::new(generated::csound_score::CsoundScoreLexer)),
        "cuda" | "cu" => Some(Box::new(generated::cuda::CudaLexer)),
        "cypher" => Some(Box::new(generated::cypher::CypherLexer)),
        "cython" | "pyx" | "pyrex" => Some(Box::new(generated::cython::CythonLexer)),
        "d" => Some(Box::new(generated::d::DLexer)),
        "dart" => Some(Box::new(generated::dart::DartLexer)),
        "dax" => Some(Box::new(generated::dax::DaxLexer)),
        "devicetree" | "dts" => Some(Box::new(generated::devicetree::DevicetreeLexer)),
        "dg" => Some(Box::new(generated::dg::DgLexer)),
        "docker" | "dockerfile" => Some(Box::new(generated::docker::DockerLexer)),
        "dtd" => Some(Box::new(generated::dtd::DtdLexer)),
        "duel" | "jbst" | "jsonml+bst" => Some(Box::new(generated::duel::DuelLexer)),
        "dylan" => Some(Box::new(generated::dylan::DylanLexer)),
        "dylan-lid" | "lid" => Some(Box::new(generated::dylan_lid::DylanLidLexer)),
        "earl-grey" | "earlgrey" | "eg" => Some(Box::new(generated::earl_grey::EarlGreyLexer)),
        "easytrieve" => Some(Box::new(generated::easytrieve::EasytrieveLexer)),
        "ebnf" => Some(Box::new(generated::ebnf::EbnfLexer)),
        "ec" => Some(Box::new(generated::ec::EcLexer)),
        "ecl" => Some(Box::new(generated::ecl::EclLexer)),
        "eiffel" => Some(Box::new(generated::eiffel::EiffelLexer)),
        "elm" => Some(Box::new(generated::elm::ElmLexer)),
        "emacs-lisp" | "elisp" | "emacs" => Some(Box::new(generated::emacs_lisp::EmacsLispLexer)),
        "evoque" => Some(Box::new(generated::evoque::EvoqueLexer)),
        "execline" => Some(Box::new(generated::execline::ExeclineLexer)),
        "extempore" => Some(Box::new(generated::extempore::ExtemporeLexer)),
        "ezhil" => Some(Box::new(generated::ezhil::EzhilLexer)),
        "factor" => Some(Box::new(generated::factor::FactorLexer)),
        "fan" => Some(Box::new(generated::fan::FanLexer)),
        "fancy" | "fy" => Some(Box::new(generated::fancy::FancyLexer)),
        "felix" | "flx" => Some(Box::new(generated::felix::FelixLexer)),
        "fennel" | "fnl" => Some(Box::new(generated::fennel::FennelLexer)),
        "fift" | "fif" => Some(Box::new(generated::fift::FiftLexer)),
        "fish" | "fishshell" => Some(Box::new(generated::fish::FishLexer)),
        "flatline" => Some(Box::new(generated::flatline::FlatlineLexer)),
        "floscript" | "flo" => Some(Box::new(generated::floscript::FloscriptLexer)),
        "forth" => Some(Box::new(generated::forth::ForthLexer)),
        "foxpro" | "vfp" | "clipper" | "xbase" => Some(Box::new(generated::foxpro::FoxproLexer)),
        "freefem" => Some(Box::new(generated::freefem::FreefemLexer)),
        "fsharp" | "f#" => Some(Box::new(generated::fsharp::FsharpLexer)),
        "fstar" => Some(Box::new(generated::fstar::FstarLexer)),
        "func" | "fc" => Some(Box::new(generated::func::FuncLexer)),
        "futhark" => Some(Box::new(generated::futhark::FutharkLexer)),
        "gap" => Some(Box::new(generated::gap::GapLexer)),
        "gas" | "asm" => Some(Box::new(generated::gas::GasLexer)),
        "gcode" => Some(Box::new(generated::gcode::GcodeLexer)),
        "gdscript" | "gd" => Some(Box::new(generated::gdscript::GdscriptLexer)),
        "genshitext" => Some(Box::new(generated::genshitext::GenshitextLexer)),
        "gherkin" | "cucumber" => Some(Box::new(generated::gherkin::GherkinLexer)),
        "gleam" => Some(Box::new(generated::gleam::GleamLexer)),
        "glsl" => Some(Box::new(generated::glsl::GlslLexer)),
        "gnuplot" => Some(Box::new(generated::gnuplot::GnuplotLexer)),
        "golo" => Some(Box::new(generated::golo::GoloLexer)),
        "gooddata-cl" => Some(Box::new(generated::gooddata_cl::GooddataClLexer)),
        "googlesql" | "zetasql" => Some(Box::new(generated::googlesql::GooglesqlLexer)),
        "gosu" => Some(Box::new(generated::gosu::GosuLexer)),
        "graphviz" | "dot" => Some(Box::new(generated::graphviz::GraphvizLexer)),
        "groovy" => Some(Box::new(generated::groovy::GroovyLexer)),
        "gsql" => Some(Box::new(generated::gsql::GsqlLexer)),
        "handlebars" => Some(Box::new(generated::handlebars::HandlebarsLexer)),
        "hare" => Some(Box::new(generated::hare::HareLexer)),
        "haxeml" | "hxml" => Some(Box::new(generated::haxeml::HaxemlLexer)),
        "hexdump" => Some(Box::new(generated::hexdump::HexdumpLexer)),
        "hlsl" => Some(Box::new(generated::hlsl::HlslLexer)),
        "hsail" | "hsa" => Some(Box::new(generated::hsail::HsailLexer)),
        "hspec" => Some(Box::new(generated::hspec::HspecLexer)),
        "hybris" => Some(Box::new(generated::hybris::HybrisLexer)),
        "hylang" | "hy" => Some(Box::new(generated::hylang::HylangLexer)),
        "i6t" => Some(Box::new(generated::i6t::I6tLexer)),
        "icon" => Some(Box::new(generated::icon::IconLexer)),
        "idl" => Some(Box::new(generated::idl::IdlLexer)),
        "idris" | "idr" => Some(Box::new(generated::idris::IdrisLexer)),
        "igor" | "igorpro" => Some(Box::new(generated::igor::IgorLexer)),
        "inform6" | "i6" => Some(Box::new(generated::inform6::Inform6Lexer)),
        "inform7" | "i7" => Some(Box::new(generated::inform7::Inform7Lexer)),
        "io" => Some(Box::new(generated::io::IoLexer)),
        "ioke" | "ik" => Some(Box::new(generated::ioke::IokeLexer)),
        "irc" => Some(Box::new(generated::irc::IrcLexer)),
        "isabelle" => Some(Box::new(generated::isabelle::IsabelleLexer)),
        "j" => Some(Box::new(generated::j::JLexer)),
        "jags" => Some(Box::new(generated::jags::JagsLexer)),
        "janet" => Some(Box::new(generated::janet::JanetLexer)),
        "jasmin" | "jasminxt" => Some(Box::new(generated::jasmin::JasminLexer)),
        "java" => Some(Box::new(generated::java::JavaLexer)),
        "jcl" => Some(Box::new(generated::jcl::JclLexer)),
        "jmespath" | "jp" => Some(Box::new(generated::jmespath::JmespathLexer)),
        "jsgf" => Some(Box::new(generated::jsgf::JsgfLexer)),
        "jslt" => Some(Box::new(generated::jslt::JsltLexer)),
        "json5" => Some(Box::new(generated::json5::Json5Lexer)),
        "jsonnet" => Some(Box::new(generated::jsonnet::JsonnetLexer)),
        "jsx" | "react" => Some(Box::new(generated::jsx::JsxLexer)),
        "juttle" => Some(Box::new(generated::juttle::JuttleLexer)),
        "k" => Some(Box::new(generated::k::KLexer)),
        "kal" => Some(Box::new(generated::kal::KalLexer)),
        "kmsg" | "dmesg" => Some(Box::new(generated::kmsg::KmsgLexer)),
        "koka" => Some(Box::new(generated::koka::KokaLexer)),
        "kotlin" => Some(Box::new(generated::kotlin::KotlinLexer)),
        "kql" | "kusto" => Some(Box::new(generated::kql::KqlLexer)),
        "kuin" => Some(Box::new(generated::kuin::KuinLexer)),
        "lasso" | "lassoscript" => Some(Box::new(generated::lasso::LassoLexer)),
        "ldapconf" | "ldaprc" => Some(Box::new(generated::ldapconf::LdapconfLexer)),
        "ldif" => Some(Box::new(generated::ldif::LdifLexer)),
        "lean" | "lean3" => Some(Box::new(generated::lean::LeanLexer)),
        "lean4" => Some(Box::new(generated::lean4::Lean4Lexer)),
        "less" => Some(Box::new(generated::less::LessLexer)),
        "limbo" => Some(Box::new(generated::limbo::LimboLexer)),
        "liquid" => Some(Box::new(generated::liquid::LiquidLexer)),
        "livescript" | "live-script" => Some(Box::new(generated::livescript::LivescriptLexer)),
        "llvm" => Some(Box::new(generated::llvm::LlvmLexer)),
        "llvm-mir" => Some(Box::new(generated::llvm_mir::LlvmMirLexer)),
        "llvm-mir-body" => Some(Box::new(generated::llvm_mir_body::LlvmMirBodyLexer)),
        "logos" => Some(Box::new(generated::logos::LogosLexer)),
        "logtalk" => Some(Box::new(generated::logtalk::LogtalkLexer)),
        "lsl" => Some(Box::new(generated::lsl::LslLexer)),
        "luau" => Some(Box::new(generated::luau::LuauLexer)),
        "macaulay2" => Some(Box::new(generated::macaulay2::Macaulay2Lexer)),
        "mako" => Some(Box::new(generated::mako::MakoLexer)),
        "mason" => Some(Box::new(generated::mason::MasonLexer)),
        "mathematica" | "mma" | "nb" | "wl" | "wolfram" => Some(Box::new(generated::mathematica::MathematicaLexer)),
        "maxima" | "macsyma" => Some(Box::new(generated::maxima::MaximaLexer)),
        "mcfunction" | "mcf" => Some(Box::new(generated::mcfunction::McfunctionLexer)),
        "mcschema" => Some(Box::new(generated::mcschema::McschemaLexer)),
        "meson" | "meson.build" => Some(Box::new(generated::meson::MesonLexer)),
        "minid" => Some(Box::new(generated::minid::MinidLexer)),
        "miniscript" | "ms" => Some(Box::new(generated::miniscript::MiniscriptLexer)),
        "mips" => Some(Box::new(generated::mips::MipsLexer)),
        "modula2" | "m2" => Some(Box::new(generated::modula2::Modula2Lexer)),
        "mojo" | "🔥" => Some(Box::new(generated::mojo::MojoLexer)),
        "monkey" => Some(Box::new(generated::monkey::MonkeyLexer)),
        "monte" => Some(Box::new(generated::monte::MonteLexer)),
        "moocode" | "moo" => Some(Box::new(generated::moocode::MoocodeLexer)),
        "mosel" => Some(Box::new(generated::mosel::MoselLexer)),
        "mql" | "mq4" | "mq5" | "mql4" | "mql5" => Some(Box::new(generated::mql::MqlLexer)),
        "mscgen" | "msc" => Some(Box::new(generated::mscgen::MscgenLexer)),
        "mupad" => Some(Box::new(generated::mupad::MupadLexer)),
        "mxml" => Some(Box::new(generated::mxml::MxmlLexer)),
        "myghty" => Some(Box::new(generated::myghty::MyghtyLexer)),
        "mysql" => Some(Box::new(generated::mysql::MysqlLexer)),
        "nasm" => Some(Box::new(generated::nasm::NasmLexer)),
        "ncl" => Some(Box::new(generated::ncl::NclLexer)),
        "nemerle" => Some(Box::new(generated::nemerle::NemerleLexer)),
        "nesc" => Some(Box::new(generated::nesc::NescLexer)),
        "nestedtext" | "nt" => Some(Box::new(generated::nestedtext::NestedtextLexer)),
        "newspeak" => Some(Box::new(generated::newspeak::NewspeakLexer)),
        "nimrod" | "nim" => Some(Box::new(generated::nimrod::NimrodLexer)),
        "nit" => Some(Box::new(generated::nit::NitLexer)),
        "nixos" | "nix" => Some(Box::new(generated::nixos::NixosLexer)),
        "nsis" | "nsi" | "nsh" => Some(Box::new(generated::nsis::NsisLexer)),
        "numba_ir" | "numbair" => Some(Box::new(generated::numba_ir::NumbaIrLexer)),
        "numpy" => Some(Box::new(generated::numpy::NumpyLexer)),
        "nusmv" => Some(Box::new(generated::nusmv::NusmvLexer)),
        "objdump" => Some(Box::new(generated::objdump::ObjdumpLexer)),
        "objdump-nasm" => Some(Box::new(generated::objdump_nasm::ObjdumpNasmLexer)),
        "objective-c" | "objectivec" | "obj-c" | "objc" => Some(Box::new(generated::objective_c::ObjectiveCLexer)),
        "objective-c++" | "objectivec++" | "obj-c++" | "objc++" => Some(Box::new(generated::objective_cpp::ObjectiveCppLexer)),
        "objective-j" | "objectivej" | "obj-j" | "objj" => Some(Box::new(generated::objective_j::ObjectiveJLexer)),
        "ocaml" => Some(Box::new(generated::ocaml::OcamlLexer)),
        "octave" => Some(Box::new(generated::octave::OctaveLexer)),
        "odin" => Some(Box::new(generated::odin::OdinLexer)),
        "omg-idl" => Some(Box::new(generated::omg_idl::OmgIdlLexer)),
        "ooc" => Some(Box::new(generated::ooc::OocLexer)),
        "opa" => Some(Box::new(generated::opa::OpaLexer)),
        "openedge" | "abl" | "progress" => Some(Box::new(generated::openedge::OpenedgeLexer)),
        "openscad" => Some(Box::new(generated::openscad::OpenscadLexer)),
        "org" | "orgmode" | "org-mode" => Some(Box::new(generated::org::OrgLexer)),
        "pan" => Some(Box::new(generated::pan::PanLexer)),
        "parasail" => Some(Box::new(generated::parasail::ParasailLexer)),
        "pawn" => Some(Box::new(generated::pawn::PawnLexer)),
        "pddl" => Some(Box::new(generated::pddl::PddlLexer)),
        "peg" => Some(Box::new(generated::peg::PegLexer)),
        "phix" => Some(Box::new(generated::phix::PhixLexer)),
        "php" | "php3" | "php4" | "php5" => Some(Box::new(generated::php::PhpLexer)),
        "pig" => Some(Box::new(generated::pig::PigLexer)),
        "pike" => Some(Box::new(generated::pike::PikeLexer)),
        "pointless" => Some(Box::new(generated::pointless::PointlessLexer)),
        "pony" => Some(Box::new(generated::pony::PonyLexer)),
        "postgres-explain" => Some(Box::new(generated::postgres_explain::PostgresExplainLexer)),
        "postscript" | "postscr" => Some(Box::new(generated::postscript::PostscriptLexer)),
        "pov" => Some(Box::new(generated::pov::PovLexer)),
        "praat" => Some(Box::new(generated::praat::PraatLexer)),
        "procfile" => Some(Box::new(generated::procfile::ProcfileLexer)),
        "prolog" => Some(Box::new(generated::prolog::PrologLexer)),
        "promela" => Some(Box::new(generated::promela::PromelaLexer)),
        "promql" => Some(Box::new(generated::promql::PromqlLexer)),
        "prql" => Some(Box::new(generated::prql::PrqlLexer)),
        "ptx" => Some(Box::new(generated::ptx::PtxLexer)),
        "puppet" => Some(Box::new(generated::puppet::PuppetLexer)),
        "py2tb" => Some(Box::new(generated::py2tb::Py2tbLexer)),
        "pypylog" | "pypy" => Some(Box::new(generated::pypylog::PypylogLexer)),
        "pytb" | "py3tb" => Some(Box::new(generated::pytb::PytbLexer)),
        "python2" | "py2" => Some(Box::new(generated::python2::Python2Lexer)),
        "q" => Some(Box::new(generated::q::QLexer)),
        "qbasic" | "basic" => Some(Box::new(generated::qbasic::QbasicLexer)),
        "qlik" | "qlikview" | "qliksense" | "qlikscript" => Some(Box::new(generated::qlik::QlikLexer)),
        "qml" | "qbs" => Some(Box::new(generated::qml::QmlLexer)),
        "qvto" | "qvt" => Some(Box::new(generated::qvto::QvtoLexer)),
        "ragel" => Some(Box::new(generated::ragel::RagelLexer)),
        "ragel-em" => Some(Box::new(generated::ragel_em::RagelEmLexer)),
        "rd" => Some(Box::new(generated::rd::RdLexer)),
        "reasonml" | "reason" => Some(Box::new(generated::reasonml::ReasonmlLexer)),
        "redcode" => Some(Box::new(generated::redcode::RedcodeLexer)),
        "rego" => Some(Box::new(generated::rego::RegoLexer)),
        "rell" => Some(Box::new(generated::rell::RellLexer)),
        "resourcebundle" | "resource" => Some(Box::new(generated::resourcebundle::ResourcebundleLexer)),
        "rexx" | "arexx" => Some(Box::new(generated::rexx::RexxLexer)),
        "ride" => Some(Box::new(generated::ride::RideLexer)),
        "rita" => Some(Box::new(generated::rita::RitaLexer)),
        "rng-compact" | "rnc" => Some(Box::new(generated::rng_compact::RngCompactLexer)),
        "roboconf-graph" => Some(Box::new(generated::roboconf_graph::RoboconfGraphLexer)),
        "roboconf-instances" => Some(Box::new(generated::roboconf_instances::RoboconfInstancesLexer)),
        "rql" => Some(Box::new(generated::rql::RqlLexer)),
        "rsl" => Some(Box::new(generated::rsl::RslLexer)),
        "sarl" => Some(Box::new(generated::sarl::SarlLexer)),
        "sas" => Some(Box::new(generated::sas::SasLexer)),
        "savi" => Some(Box::new(generated::savi::SaviLexer)),
        "scdoc" | "scd" => Some(Box::new(generated::scdoc::ScdocLexer)),
        "scilab" => Some(Box::new(generated::scilab::ScilabLexer)),
        "scss" => Some(Box::new(generated::scss::ScssLexer)),
        "sed" | "gsed" | "ssed" => Some(Box::new(generated::sed::SedLexer)),
        "sgf" => Some(Box::new(generated::sgf::SgfLexer)),
        "shen" => Some(Box::new(generated::shen::ShenLexer)),
        "shexc" | "shex" => Some(Box::new(generated::shexc::ShexcLexer)),
        "sieve" => Some(Box::new(generated::sieve::SieveLexer)),
        "silver" => Some(Box::new(generated::silver::SilverLexer)),
        "slurm" | "sbatch" => Some(Box::new(generated::slurm::SlurmLexer)),
        "smali" => Some(Box::new(generated::smali::SmaliLexer)),
        "smalltalk" | "squeak" | "st" => Some(Box::new(generated::smalltalk::SmalltalkLexer)),
        "smarty" => Some(Box::new(generated::smarty::SmartyLexer)),
        "smithy" => Some(Box::new(generated::smithy::SmithyLexer)),
        "snbt" => Some(Box::new(generated::snbt::SnbtLexer)),
        "snobol" => Some(Box::new(generated::snobol::SnobolLexer)),
        "solidity" => Some(Box::new(generated::solidity::SolidityLexer)),
        "sophia" => Some(Box::new(generated::sophia::SophiaLexer)),
        "sp" => Some(Box::new(generated::sp::SpLexer)),
        "sparql" => Some(Box::new(generated::sparql::SparqlLexer)),
        "spec" => Some(Box::new(generated::spec::SpecLexer)),
        "spice" | "spicelang" => Some(Box::new(generated::spice::SpiceLexer)),
        "squidconf" | "squid.conf" | "squid" => Some(Box::new(generated::squidconf::SquidconfLexer)),
        "srcinfo" => Some(Box::new(generated::srcinfo::SrcinfoLexer)),
        "stan" => Some(Box::new(generated::stan::StanLexer)),
        "stata" | "do" => Some(Box::new(generated::stata::StataLexer)),
        "supercollider" | "sc" => Some(Box::new(generated::supercollider::SupercolliderLexer)),
        "swig" => Some(Box::new(generated::swig::SwigLexer)),
        "systemverilog" | "sv" => Some(Box::new(generated::systemverilog::SystemverilogLexer)),
        "tact" => Some(Box::new(generated::tact::TactLexer)),
        "tads3" => Some(Box::new(generated::tads3::Tads3Lexer)),
        "tal" | "uxntal" => Some(Box::new(generated::tal::TalLexer)),
        "tap" => Some(Box::new(generated::tap::TapLexer)),
        "tasm" => Some(Box::new(generated::tasm::TasmLexer)),
        "tcl" => Some(Box::new(generated::tcl::TclLexer)),
        "tcsh" | "csh" => Some(Box::new(generated::tcsh::TcshLexer)),
        "teal" => Some(Box::new(generated::teal::TealLexer)),
        "teratermmacro" | "teraterm" | "ttl" => Some(Box::new(generated::teratermmacro::TeratermmacroLexer)),
        "thrift" => Some(Box::new(generated::thrift::ThriftLexer)),
        "ti" | "thingsdb" => Some(Box::new(generated::ti::TiLexer)),
        "tlb" => Some(Box::new(generated::tlb::TlbLexer)),
        "tls" => Some(Box::new(generated::tls::TlsLexer)),
        "todotxt" => Some(Box::new(generated::todotxt::TodotxtLexer)),
        "trac-wiki" | "moin" => Some(Box::new(generated::trac_wiki::TracWikiLexer)),
        "trafficscript" | "rts" => Some(Box::new(generated::trafficscript::TrafficscriptLexer)),
        "tsql" | "t-sql" => Some(Box::new(generated::tsql::TsqlLexer)),
        "tsx" => Some(Box::new(generated::tsx::TsxLexer)),
        "turtle" => Some(Box::new(generated::turtle::TurtleLexer)),
        "typst" => Some(Box::new(generated::typst::TypstLexer)),
        "ucode" => Some(Box::new(generated::ucode::UcodeLexer)),
        "ul4" => Some(Box::new(generated::ul4::Ul4Lexer)),
        "unicon" => Some(Box::new(generated::unicon::UniconLexer)),
        "unixconfig" | "linuxconfig" => Some(Box::new(generated::unixconfig::UnixconfigLexer)),
        "urlencoded" => Some(Box::new(generated::urlencoded::UrlencodedLexer)),
        "usd" | "usda" => Some(Box::new(generated::usd::UsdLexer)),
        "vala" | "vapi" => Some(Box::new(generated::vala::ValaLexer)),
        "vb.net" | "vbnet" | "lobas" | "oobas" | "sobas" | "visual-basic" | "visualbasic" => Some(Box::new(generated::vb_net::VbNetLexer)),
        "vbscript" => Some(Box::new(generated::vbscript::VbscriptLexer)),
        "vcl" => Some(Box::new(generated::vcl::VclLexer)),
        "vclsnippets" | "vclsnippet" => Some(Box::new(generated::vclsnippets::VclsnippetsLexer)),
        "verifpal" => Some(Box::new(generated::verifpal::VerifpalLexer)),
        "verilog" | "v" => Some(Box::new(generated::verilog::VerilogLexer)),
        "vgl" => Some(Box::new(generated::vgl::VglLexer)),
        "vhdl" => Some(Box::new(generated::vhdl::VhdlLexer)),
        "vim" => Some(Box::new(generated::vim::VimLexer)),
        "visualprolog" => Some(Box::new(generated::visualprolog::VisualprologLexer)),
        "visualprologgrammar" => Some(Box::new(generated::visualprologgrammar::VisualprologgrammarLexer)),
        "vue" => Some(Box::new(generated::vue::VueLexer)),
        "vyper" => Some(Box::new(generated::vyper::VyperLexer)),
        "wast" | "wat" => Some(Box::new(generated::wast::WastLexer)),
        "wdiff" => Some(Box::new(generated::wdiff::WdiffLexer)),
        "webidl" => Some(Box::new(generated::webidl::WebidlLexer)),
        "wgsl" => Some(Box::new(generated::wgsl::WgslLexer)),
        "whiley" => Some(Box::new(generated::whiley::WhileyLexer)),
        "wowtoc" => Some(Box::new(generated::wowtoc::WowtocLexer)),
        "wren" => Some(Box::new(generated::wren::WrenLexer)),
        "x10" | "xten" => Some(Box::new(generated::x10::X10Lexer)),
        "xorg.conf" => Some(Box::new(generated::xorg_conf::XorgConfLexer)),
        "xslt" => Some(Box::new(generated::xslt::XsltLexer)),
        "xtend" => Some(Box::new(generated::xtend::XtendLexer)),
        "yang" => Some(Box::new(generated::yang::YangLexer)),
        "yara" | "yar" => Some(Box::new(generated::yara::YaraLexer)),
        "zeek" | "bro" => Some(Box::new(generated::zeek::ZeekLexer)),
        "zephir" => Some(Box::new(generated::zephir::ZephirLexer)),
        "zig" => Some(Box::new(generated::zig::ZigLexer)),
        "zone" => Some(Box::new(generated::zone::ZoneLexer)),
        _ => None,
    }
}

/// Aliases for which a native Rust lexer exists. Sorted by primary
/// name first so the list is stable for snapshotting.
pub fn native_aliases() -> &'static [&'static str] {
    &[
        "text",
        "plain",
        "",
        "python",
        "py",
        "python3",
        "py3",
        "json",
        "json-object",
        "diff",
        "udiff",
        // --- transpiled ---
        "ini",
        "cfg",
        "dosini",
        "properties",
        "jproperties",
        "toml",
        "pot",
        "po",
        "dpatch",
        "vctreestatus",
        "groff",
        "nroff",
        "man",
        "bash",
        "sh",
        "ksh",
        "zsh",
        "shell",
        "openrc",
        "cmake",
        // --- Phase B: config/markup/template formats ---
        "augeas",
        "bbcode",
        "desktop",
        "lighttpd",
        "lighty",
        "pacmanconf",
        "pkgconfig",
        "registry",
        "mozhashpreproc",
        "mozpercentpreproc",
        "debian.sources",
        "django",
        "jinja",
        "ng2",
        "cfengine3",
        "cf3",
        "cfs",
        // --- Phase B batch 2 ---
        "debcontrol",
        "control",
        "debsources",
        "sourceslist",
        "sources.list",
        "kconfig",
        "menuconfig",
        "linux-config",
        "kernel-config",
        "systemd",
        "termcap",
        "terminfo",
        "twig",
        "velocity",
        // --- Phase A ---
        "rust",
        "rs",
        "go",
        "golang",
        "javascript",
        "js",
        "swift",
        "perl",
        "pl",
        "haskell",
        "hs",
        "elixir",
        "ex",
        "exs",
        "typescript",
        "ts",
        "css",
        "xml",
        "sql",
        "lua",
        "splus",
        "s",
        "r",
        "matlab",
        "julia",
        "jl",
        "clojure",
        "clj",
        "erlang",
        "nginx",
        "apacheconf",
        "aconf",
        "apache",
        "powershell",
        "pwsh",
        "posh",
        "ps1",
        "psm1",
        "tex",
        "latex",
        "graphql",
        "protobuf",
        "proto",
        "scala",
        // --- Phase C batch 1 ---
        "applescript",
        "chaiscript",
        "chai",
        "moonscript",
        "moon",
        "alloy",
        "arrow",
        "awk",
        "gawk",
        "mawk",
        "nawk",
        "bdd",
        "abap",
        "maql",
        "bbcbasic",
        "blitzmax",
        "bmax",
        "newlisp",
        "racket",
        "rkt",
        // --- Phase D: using(this) / using(OtherLexer) ---
        "fortran",
        "f90",
        "ampl",
        "typoscriptcssdata",
        "typoscripthtmldata",
        "typoscript",

        // --- bulk transpiled aliases ---
"abnf",
        "actionscript",
        "as",
        "actionscript3",
        "as3",
        "ada",
        "ada95",
        "ada2005",
        "agda",
        "aheui",
        "ambienttalk",
        "ambienttalk/2",
        "at",
        "amdgpu",
        "androidbp",
        "bp",
        "soong",
        "ansys",
        "apdl",
        "antlr",
        "apl",
        "arduino",
        "asc",
        "pem",
        "asn1",
        "aspectj",
        "asymptote",
        "asy",
        "autohotkey",
        "ahk",
        "autoit",
        "bare",
        "basemake",
        "batch",
        "bat",
        "dosbatch",
        "winbatch",
        "bc",
        "befunge",
        "berry",
        "be",
        "blitzbasic",
        "b3d",
        "bplus",
        "blueprint",
        "bnf",
        "boa",
        "boo",
        "boogie",
        "bqn",
        "brainfuck",
        "bf",
        "bst",
        "bst-pybtex",
        "bugs",
        "winbugs",
        "openbugs",
        "c",
        "ca65",
        "cadl",
        "camkes",
        "idl4",
        "capdl",
        "capnp",
        "carbon",
        "cbmbas",
        "cddl",
        "ceylon",
        "chapel",
        "chpl",
        "charmci",
        "cheetah",
        "spitfire",
        "cirru",
        "clay",
        "clean",
        "clojurescript",
        "cljs",
        "cobol",
        "cobolfree",
        "codeql",
        "ql",
        "coffeescript",
        "coffee-script",
        "coffee",
        "comal",
        "comal80",
        "common-lisp",
        "cl",
        "lisp",
        "componentpascal",
        "cp",
        "coq",
        "rocq",
        "rocq-prover",
        "cplint",
        "cpp",
        "c++",
        "cpsa",
        "crmsh",
        "pcmk",
        "croc",
        "cryptol",
        "cry",
        "csound-score",
        "csound-sco",
        "cuda",
        "cu",
        "cypher",
        "cython",
        "pyx",
        "pyrex",
        "d",
        "dart",
        "dax",
        "devicetree",
        "dts",
        "dg",
        "docker",
        "dockerfile",
        "dtd",
        "duel",
        "jbst",
        "jsonml+bst",
        "dylan",
        "dylan-lid",
        "lid",
        "earl-grey",
        "earlgrey",
        "eg",
        "easytrieve",
        "ebnf",
        "ec",
        "ecl",
        "eiffel",
        "elm",
        "emacs-lisp",
        "elisp",
        "emacs",
        "evoque",
        "execline",
        "extempore",
        "ezhil",
        "factor",
        "fan",
        "fancy",
        "fy",
        "felix",
        "flx",
        "fennel",
        "fnl",
        "fift",
        "fif",
        "fish",
        "fishshell",
        "flatline",
        "floscript",
        "flo",
        "forth",
        "foxpro",
        "vfp",
        "clipper",
        "xbase",
        "freefem",
        "fsharp",
        "f#",
        "fstar",
        "func",
        "fc",
        "futhark",
        "gap",
        "gas",
        "asm",
        "gcode",
        "gdscript",
        "gd",
        "genshitext",
        "gherkin",
        "cucumber",
        "gleam",
        "glsl",
        "gnuplot",
        "golo",
        "gooddata-cl",
        "googlesql",
        "zetasql",
        "gosu",
        "graphviz",
        "dot",
        "groovy",
        "gsql",
        "handlebars",
        "hare",
        "haxeml",
        "hxml",
        "hexdump",
        "hlsl",
        "hsail",
        "hsa",
        "hspec",
        "hybris",
        "hylang",
        "hy",
        "i6t",
        "icon",
        "idl",
        "idris",
        "idr",
        "igor",
        "igorpro",
        "inform6",
        "i6",
        "inform7",
        "i7",
        "io",
        "ioke",
        "ik",
        "irc",
        "isabelle",
        "j",
        "jags",
        "janet",
        "jasmin",
        "jasminxt",
        "java",
        "jcl",
        "jmespath",
        "jp",
        "jsgf",
        "jslt",
        "json5",
        "jsonnet",
        "jsx",
        "react",
        "juttle",
        "k",
        "kal",
        "kmsg",
        "dmesg",
        "koka",
        "kotlin",
        "kql",
        "kusto",
        "kuin",
        "lasso",
        "lassoscript",
        "ldapconf",
        "ldaprc",
        "ldif",
        "lean",
        "lean3",
        "lean4",
        "less",
        "limbo",
        "liquid",
        "livescript",
        "live-script",
        "llvm",
        "llvm-mir",
        "llvm-mir-body",
        "logos",
        "logtalk",
        "lsl",
        "luau",
        "macaulay2",
        "mako",
        "mason",
        "mathematica",
        "mma",
        "nb",
        "wl",
        "wolfram",
        "maxima",
        "macsyma",
        "mcfunction",
        "mcf",
        "mcschema",
        "meson",
        "meson.build",
        "minid",
        "miniscript",
        "ms",
        "mips",
        "modula2",
        "m2",
        "mojo",
        "🔥",
        "monkey",
        "monte",
        "moocode",
        "moo",
        "mosel",
        "mql",
        "mq4",
        "mq5",
        "mql4",
        "mql5",
        "mscgen",
        "msc",
        "mupad",
        "mxml",
        "myghty",
        "mysql",
        "nasm",
        "ncl",
        "nemerle",
        "nesc",
        "nestedtext",
        "nt",
        "newspeak",
        "nimrod",
        "nim",
        "nit",
        "nixos",
        "nix",
        "nsis",
        "nsi",
        "nsh",
        "numba_ir",
        "numbair",
        "numpy",
        "nusmv",
        "objdump",
        "objdump-nasm",
        "objective-c",
        "objectivec",
        "obj-c",
        "objc",
        "objective-c++",
        "objectivec++",
        "obj-c++",
        "objc++",
        "objective-j",
        "objectivej",
        "obj-j",
        "objj",
        "ocaml",
        "octave",
        "odin",
        "omg-idl",
        "ooc",
        "opa",
        "openedge",
        "abl",
        "progress",
        "openscad",
        "org",
        "orgmode",
        "org-mode",
        "pan",
        "parasail",
        "pawn",
        "pddl",
        "peg",
        "phix",
        "php",
        "php3",
        "php4",
        "php5",
        "pig",
        "pike",
        "pointless",
        "pony",
        "postgres-explain",
        "postscript",
        "postscr",
        "pov",
        "praat",
        "procfile",
        "prolog",
        "promela",
        "promql",
        "prql",
        "ptx",
        "puppet",
        "py2tb",
        "pypylog",
        "pypy",
        "pytb",
        "py3tb",
        "python2",
        "py2",
        "q",
        "qbasic",
        "basic",
        "qlik",
        "qlikview",
        "qliksense",
        "qlikscript",
        "qml",
        "qbs",
        "qvto",
        "qvt",
        "ragel",
        "ragel-em",
        "rd",
        "reasonml",
        "reason",
        "redcode",
        "rego",
        "rell",
        "resourcebundle",
        "resource",
        "rexx",
        "arexx",
        "ride",
        "rita",
        "rng-compact",
        "rnc",
        "roboconf-graph",
        "roboconf-instances",
        "rql",
        "rsl",
        "sarl",
        "sas",
        "savi",
        "scdoc",
        "scd",
        "scilab",
        "scss",
        "sed",
        "gsed",
        "ssed",
        "sgf",
        "shen",
        "shexc",
        "shex",
        "sieve",
        "silver",
        "slurm",
        "sbatch",
        "smali",
        "smalltalk",
        "squeak",
        "st",
        "smarty",
        "smithy",
        "snbt",
        "snobol",
        "solidity",
        "sophia",
        "sp",
        "sparql",
        "spec",
        "spice",
        "spicelang",
        "squidconf",
        "squid.conf",
        "squid",
        "srcinfo",
        "stan",
        "stata",
        "do",
        "supercollider",
        "sc",
        "swig",
        "systemverilog",
        "sv",
        "tact",
        "tads3",
        "tal",
        "uxntal",
        "tap",
        "tasm",
        "tcl",
        "tcsh",
        "csh",
        "teal",
        "teratermmacro",
        "teraterm",
        "ttl",
        "thrift",
        "ti",
        "thingsdb",
        "tlb",
        "tls",
        "todotxt",
        "trac-wiki",
        "moin",
        "trafficscript",
        "rts",
        "tsql",
        "t-sql",
        "tsx",
        "turtle",
        "typst",
        "ucode",
        "ul4",
        "unicon",
        "unixconfig",
        "linuxconfig",
        "urlencoded",
        "usd",
        "usda",
        "vala",
        "vapi",
        "vb.net",
        "vbnet",
        "lobas",
        "oobas",
        "sobas",
        "visual-basic",
        "visualbasic",
        "vbscript",
        "vcl",
        "vclsnippets",
        "vclsnippet",
        "verifpal",
        "verilog",
        "v",
        "vgl",
        "vhdl",
        "vim",
        "visualprolog",
        "visualprologgrammar",
        "vue",
        "vyper",
        "wast",
        "wat",
        "wdiff",
        "webidl",
        "wgsl",
        "whiley",
        "wowtoc",
        "wren",
        "xorg.conf",
        "xpp",
        "x++",
        "xslt",
        "xtend",
        "yang",
        "yara",
        "yar",
        "zeek",
        "bro",
        "zephir",
        "zig",
        "zone",
    ]
}
