//! Rust source analysis through rustdoc's versioned JSON output.
//!
//! This is the practical H14 fallback boundary: rustdoc itself produces the
//! resolved item graph, while this crate owns only JSON acquisition, schema
//! validation, and lowering into [`super::SourceDeclaration`]. Compiler
//! internal `librustdoc` types never cross that boundary.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use rustdoc_types as rustdoc;

use super::{
    AnalysisDiagnostic, AnalysisError, AnalysisSnapshot, BackendPolicy, DeclarationKind,
    DiagnosticSeverity, SourceAnalysisRequest, SourceAnalyzer, SourceDeclaration, SourceLanguage,
    SourcePosition, SourceSpan, Visibility, hash_bytes, normalize_path, normalize_text,
};

/// rustdoc JSON backend identity for persisted snapshots and diagnostics.
pub const BACKEND: &str = "rustdoc-json";
pub const BACKEND_VERSION: &str = "rustdoc-types-0.61";

/// Rust analyzer consuming a rustdoc JSON file generated by a matching
/// rustdoc executable.
#[derive(Debug, Clone, Default)]
pub struct RustdocJsonAnalyzer {
    /// Optional caller-visible toolchain identity stored on snapshots.
    pub toolchain: Option<String>,
}

impl RustdocJsonAnalyzer {
    pub fn new(toolchain: Option<String>) -> Self {
        Self { toolchain }
    }

    /// Lower an already-loaded rustdoc JSON blob. This is useful to callers
    /// that acquire JSON through Cargo or a hermetic build service.
    pub fn analyze_json_bytes(
        &self,
        request: &SourceAnalysisRequest,
        json_path: &Path,
        bytes: &[u8],
    ) -> Result<AnalysisSnapshot, AnalysisError> {
        let rustdoc_crate: rustdoc::Crate = serde_json::from_slice(bytes).map_err(|error| {
            AnalysisError::Parse {
                backend: BACKEND.to_string(),
                message: format!("{}: {error}", json_path.display()),
            }
        })?;
        if rustdoc_crate.format_version != rustdoc::FORMAT_VERSION {
            return Err(AnalysisError::BackendUnavailable {
                backend: BACKEND.to_string(),
                message: format!(
                    "{} has JSON format {}, but rustdoc-types expects {}",
                    json_path.display(),
                    rustdoc_crate.format_version,
                    rustdoc::FORMAT_VERSION
                ),
            });
        }

        let source_root = if request.source_root.is_file() {
            request
                .source_root
                .parent()
                .unwrap_or(Path::new("."))
                .to_path_buf()
        } else {
            request.source_root.clone()
        };
        let mut lowerer = Lowerer::new(&rustdoc_crate, &source_root, request.include_private);
        lowerer.lower_root()?;
        let mut snapshot = AnalysisSnapshot::new(
            SourceLanguage::Rust,
            BACKEND,
            format!("{BACKEND_VERSION}/format-{}", rustdoc::FORMAT_VERSION),
            &source_root,
            hash_bytes(bytes),
            lowerer.declarations,
            lowerer.diagnostics,
        );
        snapshot.toolchain = self.toolchain.clone();
        snapshot.set_request_identity(request);
        snapshot.normalize_and_sort();
        Ok(snapshot)
    }

    fn json_path(request: &SourceAnalysisRequest) -> Option<PathBuf> {
        if request.source_root.is_file()
            && request.source_root.extension().is_some_and(|ext| ext == "json")
        {
            return Some(request.source_root.clone());
        }
        request
            .selected
            .iter()
            .find(|path| path.extension().is_some_and(|ext| ext == "json"))
            .cloned()
    }
}

impl SourceAnalyzer for RustdocJsonAnalyzer {
    fn analyze(
        &self,
        request: &SourceAnalysisRequest,
    ) -> Result<AnalysisSnapshot, AnalysisError> {
        let Some(json_path) = Self::json_path(request) else {
            let policy = match request.backend_policy {
                BackendPolicy::Required => "required",
                BackendPolicy::AllowFallback => "allow-fallback",
                BackendPolicy::Auto => "auto",
            };
            return Err(AnalysisError::BackendUnavailable {
                backend: BACKEND.to_string(),
                message: format!(
                    "no rustdoc JSON path supplied ({policy}); generate JSON with the matching rustdoc executable and select it in SourceAnalysisRequest"
                ),
            });
        };
        let bytes = fs::read(&json_path).map_err(|error| AnalysisError::Io {
            path: json_path.display().to_string(),
            message: error.to_string(),
        })?;
        self.analyze_json_bytes(request, &json_path, &bytes)
    }

    fn cache_identity(&self, request: &SourceAnalysisRequest) -> String {
        let toolchain = self
            .toolchain
            .as_deref()
            .map(|identity| hash_bytes(identity.as_bytes()))
            .unwrap_or_else(|| "unspecified".to_string());
        format!(
            "rustdoc-json-v1:{}:{BACKEND_VERSION}:format-{}:toolchain-{toolchain}",
            request.cache_identity(),
            rustdoc::FORMAT_VERSION,
        )
    }
}

struct Lowerer<'a> {
    rustdoc_crate: &'a rustdoc::Crate,
    source_root: &'a Path,
    include_private: bool,
    declarations: Vec<SourceDeclaration>,
    diagnostics: Vec<AnalysisDiagnostic>,
    id_to_index: HashMap<rustdoc::Id, usize>,
    uses: Vec<(Option<String>, rustdoc::Use, Option<SourceSpan>)>,
    source_cache: HashMap<PathBuf, Vec<u8>>,
}

impl<'a> Lowerer<'a> {
    fn new(rustdoc_crate: &'a rustdoc::Crate, source_root: &'a Path, include_private: bool) -> Self {
        Self {
            rustdoc_crate,
            source_root,
            include_private,
            declarations: Vec::new(),
            diagnostics: Vec::new(),
            id_to_index: HashMap::new(),
            uses: Vec::new(),
            source_cache: HashMap::new(),
        }
    }

    fn lower_root(&mut self) -> Result<(), AnalysisError> {
        let root = self
            .rustdoc_crate
            .index
            .get(&self.rustdoc_crate.root)
            .ok_or_else(|| AnalysisError::Parse {
                backend: BACKEND.to_string(),
                message: "rustdoc JSON root item is missing from index".to_string(),
            })?
            .clone();
        let crate_name = self
            .rustdoc_crate
            .paths
            .get(&self.rustdoc_crate.root)
            .and_then(|summary| summary.path.first())
            .cloned()
            .unwrap_or_else(|| "crate".to_string());
        self.visit_item(
            self.rustdoc_crate.root,
            &root,
            &crate_name,
            None,
            true,
        );
        self.apply_reexports();
        Ok(())
    }

    fn visit_item(
        &mut self,
        id: rustdoc::Id,
        item: &rustdoc::Item,
        qualified_name: &str,
        parent_kind: Option<DeclarationKind>,
        force_include: bool,
    ) {
        if !force_include
            && !self.include_private
            && !is_public_or_api_child(&item.visibility, item.inner.item_kind(), parent_kind.as_ref())
        {
            return;
        }

        if let rustdoc::ItemEnum::Use(use_item) = &item.inner {
            let source = item.span.as_ref().map(|span| self.span(span));
            self.uses
                .push((parent_name(qualified_name), use_item.clone(), source));
            return;
        }

        let Some(kind) = declaration_kind(&item.inner) else {
            return;
        };
        let source = item
            .span
            .as_ref()
            .map(|span| self.span(span))
            .unwrap_or_else(|| self.synthetic_span());
        let (signature, type_text) = signature_and_type(&item.inner);
        let mut declaration = SourceDeclaration::new(
            SourceLanguage::Rust,
            BACKEND,
            qualified_name,
            "::",
            kind.clone(),
            signature,
            type_text,
            item.docs.as_deref().unwrap_or_default(),
            lower_visibility(&item.visibility),
            source,
        );
        declaration.deprecated = item.deprecation.is_some();
        declaration.noindex = item
            .attrs
            .iter()
            .any(|attribute| matches!(attribute, rustdoc::Attribute::Other(value) if value.contains("doc(hidden)")));
        for attribute in &item.attrs {
            let value = format!("{attribute:?}");
            declaration
                .attributes
                .insert(attribute_key(attribute), normalize_text(&value));
        }
        for (link, target) in &item.links {
            declaration
                .attributes
                .insert(format!("doc-link:{link}"), target.0.to_string());
        }
        let index = self.declarations.len();
        self.id_to_index.insert(id, index);
        self.declarations.push(declaration);

        let child_ids = child_ids(&item.inner);
        for child_id in child_ids {
            let Some(child) = self.rustdoc_crate.index.get(&child_id).cloned() else {
                self.diagnostics.push(AnalysisDiagnostic {
                    severity: DiagnosticSeverity::Warning,
                    backend: BACKEND.to_string(),
                    message: format!("item {child_id:?} is referenced but missing from index"),
                    source: None,
                    declaration: Some(qualified_name.to_string()),
                });
                continue;
            };
            let child_name = child_name_for(&child, &item.inner, qualified_name, child_id);
            self.visit_item(child_id, &child, &child_name, Some(kind.clone()), false);
            let child_declaration_id = self
                .id_to_index
                .get(&child_id)
                .and_then(|child_index| self.declarations.get(*child_index))
                .map(|declaration| declaration.id.clone());
            if let Some(parent) = self.declarations.get_mut(index) {
                if let Some(child_declaration_id) = child_declaration_id {
                    parent.add_child(child_declaration_id);
                }
            }
        }
    }

    fn apply_reexports(&mut self) {
        for (parent, use_item, source) in std::mem::take(&mut self.uses) {
            let Some(target_id) = use_item.id else {
                continue;
            };
            let Some(target_index) = self.id_to_index.get(&target_id).copied() else {
                self.diagnostics.push(AnalysisDiagnostic {
                    severity: DiagnosticSeverity::Warning,
                    backend: BACKEND.to_string(),
                    message: format!("reexport target {:?} is unavailable", target_id),
                    source,
                    declaration: Some(use_item.name),
                });
                continue;
            };
            let alias = parent
                .map(|parent| format!("{parent}::{}", use_item.name))
                .unwrap_or(use_item.name);
            if let Some(target) = self.declarations.get_mut(target_index) {
                target.add_alias(alias);
            }
        }
    }

    fn span(&mut self, span: &rustdoc::Span) -> SourceSpan {
        let path = normalize_path(&span.filename);
        let full_path = if span.filename.is_absolute() {
            span.filename.clone()
        } else {
            self.source_root.join(&span.filename)
        };
        let bytes = self
            .source_cache
            .entry(full_path.clone())
            .or_insert_with(|| fs::read(&full_path).unwrap_or_default());
        SourceSpan::new(
            path,
            position(span.begin, bytes),
            Some(position(span.end, bytes)),
        )
    }

    fn synthetic_span(&self) -> SourceSpan {
        SourceSpan::new(
            "<rustdoc-json>",
            SourcePosition {
                byte: 0,
                line: 1,
                column: 0,
            },
            None,
        )
    }
}

fn declaration_kind(item: &rustdoc::ItemEnum) -> Option<DeclarationKind> {
    Some(match item {
        rustdoc::ItemEnum::AssocConst { .. } => DeclarationKind::AssociatedConstant,
        rustdoc::ItemEnum::AssocType { .. } => DeclarationKind::AssociatedType,
        rustdoc::ItemEnum::Constant { .. } => DeclarationKind::Constant,
        rustdoc::ItemEnum::Enum(_) => DeclarationKind::Enum,
        rustdoc::ItemEnum::Function(_) => DeclarationKind::Function,
        rustdoc::ItemEnum::Impl(_) => DeclarationKind::Impl,
        rustdoc::ItemEnum::Macro(_) | rustdoc::ItemEnum::ProcMacro(_) => DeclarationKind::Macro,
        rustdoc::ItemEnum::Module(_) => DeclarationKind::Module,
        rustdoc::ItemEnum::Static(_) => DeclarationKind::Static,
        rustdoc::ItemEnum::Struct(_) => DeclarationKind::Struct,
        rustdoc::ItemEnum::StructField(_) => DeclarationKind::Field,
        rustdoc::ItemEnum::Trait(_) | rustdoc::ItemEnum::TraitAlias(_) => DeclarationKind::Trait,
        rustdoc::ItemEnum::TypeAlias(_) => DeclarationKind::TypeAlias,
        rustdoc::ItemEnum::Union(_) => DeclarationKind::Union,
        rustdoc::ItemEnum::Variant(_) => DeclarationKind::Variant,
        rustdoc::ItemEnum::ExternCrate { .. }
        | rustdoc::ItemEnum::ExternType
        | rustdoc::ItemEnum::Primitive(_)
        | rustdoc::ItemEnum::Use(_) => return None,
    })
}

fn child_ids(item: &rustdoc::ItemEnum) -> Vec<rustdoc::Id> {
    match item {
        rustdoc::ItemEnum::Enum(item) => item
            .variants
            .iter()
            .copied()
            .chain(item.impls.iter().copied())
            .collect(),
        rustdoc::ItemEnum::Impl(item) => item.items.clone(),
        rustdoc::ItemEnum::Module(module) => module.items.clone(),
        rustdoc::ItemEnum::Struct(item) => {
            let fields = match &item.kind {
                rustdoc::StructKind::Plain { fields, .. } => fields.clone(),
                rustdoc::StructKind::Tuple(fields) => fields.iter().flatten().copied().collect(),
                rustdoc::StructKind::Unit => Vec::new(),
            };
            fields.into_iter().chain(item.impls.iter().copied()).collect()
        }
        rustdoc::ItemEnum::Trait(item) => item.items.clone(),
        rustdoc::ItemEnum::Union(item) => item
            .fields
            .iter()
            .copied()
            .chain(item.impls.iter().copied())
            .collect(),
        rustdoc::ItemEnum::Variant(item) => match &item.kind {
            rustdoc::VariantKind::Plain => Vec::new(),
            rustdoc::VariantKind::Struct { fields, .. } => fields.clone(),
            rustdoc::VariantKind::Tuple(fields) => fields.iter().flatten().copied().collect(),
        },
        _ => Vec::new(),
    }
}

fn child_name_for(
    child: &rustdoc::Item,
    parent_item: &rustdoc::ItemEnum,
    parent_name: &str,
    child_id: rustdoc::Id,
) -> String {
    if let Some(name) = &child.name {
        return format!("{parent_name}::{name}");
    }
    if let rustdoc::ItemEnum::Impl(implementation) = &child.inner {
        let trait_name = implementation
            .trait_
            .as_ref()
            .map(|path| path.path.as_str())
            .unwrap_or("inherent");
        return format!("{parent_name}::<impl {trait_name}>");
    }
    let parent_kind = parent_item.item_kind();
    format!("{parent_name}::<{}-{}>", format_item_kind(parent_kind), child_id.0)
}

fn signature_and_type(item: &rustdoc::ItemEnum) -> (Option<String>, Option<String>) {
    match item {
        rustdoc::ItemEnum::AssocConst { type_, value, .. } => (Some(format!("const: {}", render_type(type_))), value.clone()),
        rustdoc::ItemEnum::AssocType { type_, .. } => (Some("type".to_string()), type_.as_ref().map(render_type)),
        rustdoc::ItemEnum::Constant { type_, const_ } => (Some(format!("const: {}", render_type(type_))), Some(const_.expr.clone())),
        rustdoc::ItemEnum::Enum(item) => (Some(format!("enum{}", render_generics(&item.generics))), None),
        rustdoc::ItemEnum::Function(function) => (Some(render_function(function)), None),
        rustdoc::ItemEnum::Impl(item) => (Some(render_impl(item)), None),
        rustdoc::ItemEnum::Macro(value) => (Some(value.clone()), None),
        rustdoc::ItemEnum::ProcMacro(_) => (Some("proc-macro".to_string()), None),
        rustdoc::ItemEnum::Static(item) => (Some(format!("static: {}", render_type(&item.type_))), Some(item.expr.clone())),
        rustdoc::ItemEnum::Struct(item) => (Some(format!("struct{}", render_generics(&item.generics))), None),
        rustdoc::ItemEnum::StructField(type_) => (None, Some(render_type(type_))),
        rustdoc::ItemEnum::Trait(item) => (Some(format!("trait{}", render_generics(&item.generics))), None),
        rustdoc::ItemEnum::TraitAlias(item) => (Some(format!("trait{}", render_generics(&item.generics))), None),
        rustdoc::ItemEnum::TypeAlias(item) => (Some("type".to_string()), Some(render_type(&item.type_))),
        rustdoc::ItemEnum::Union(item) => (Some(format!("union{}", render_generics(&item.generics))), None),
        rustdoc::ItemEnum::Variant(variant) => (variant.discriminant.as_ref().map(|value| format!("= {}", value.expr)), None),
        _ => (None, None),
    }
}

fn render_function(function: &rustdoc::Function) -> String {
    let mut output = String::new();
    if function.header.is_const {
        output.push_str("const ");
    }
    if function.header.is_unsafe {
        output.push_str("unsafe ");
    }
    if function.header.is_async {
        output.push_str("async ");
    }
    output.push_str("fn");
    output.push_str(&render_generics(&function.generics));
    output.push('(');
    for (index, (name, type_)) in function.sig.inputs.iter().enumerate() {
        if index > 0 {
            output.push_str(", ");
        }
        output.push_str(name);
        output.push_str(": ");
        output.push_str(&render_type(type_));
    }
    if function.sig.is_c_variadic {
        if !function.sig.inputs.is_empty() {
            output.push_str(", ");
        }
        output.push_str("...");
    }
    output.push(')');
    if let Some(output_type) = &function.sig.output {
        output.push_str(" -> ");
        output.push_str(&render_type(output_type));
    }
    output
}

fn render_impl(item: &rustdoc::Impl) -> String {
    let mut output = String::from("impl");
    output.push_str(&render_generics(&item.generics));
    if let Some(trait_) = &item.trait_ {
        output.push(' ');
        output.push_str(&trait_.path);
        output.push_str(" for ");
    } else {
        output.push(' ');
    }
    output.push_str(&render_type(&item.for_));
    output
}

fn render_generics(generics: &rustdoc::Generics) -> String {
    let params = generics
        .params
        .iter()
        .map(|param| match &param.kind {
            rustdoc::GenericParamDefKind::Lifetime { outlives } => {
                if outlives.is_empty() {
                    param.name.clone()
                } else {
                    format!("{}: {}", param.name, outlives.join(" + "))
                }
            }
            rustdoc::GenericParamDefKind::Type { bounds, default, .. } => {
                let mut value = param.name.clone();
                if !bounds.is_empty() {
                    value.push_str(": ");
                    value.push_str(&bounds.iter().map(render_bound).collect::<Vec<_>>().join(" + "));
                }
                if let Some(default) = default {
                    value.push_str(" = ");
                    value.push_str(&render_type(default));
                }
                value
            }
            rustdoc::GenericParamDefKind::Const { type_, default } => {
                let mut value = format!("const {}: {}", param.name, render_type(type_));
                if let Some(default) = default {
                    value.push_str(" = ");
                    value.push_str(default);
                }
                value
            }
        })
        .collect::<Vec<_>>();
    if params.is_empty() {
        String::new()
    } else {
        format!("<{}>", params.join(", "))
    }
}

fn render_bound(bound: &rustdoc::GenericBound) -> String {
    match bound {
        rustdoc::GenericBound::TraitBound { trait_, .. } => trait_.path.clone(),
        rustdoc::GenericBound::Outlives(value) => value.clone(),
        rustdoc::GenericBound::Use(values) => format!("use<{}>", values.len()),
    }
}

fn render_type(type_: &rustdoc::Type) -> String {
    match type_ {
        rustdoc::Type::Array { type_, len } => format!("[{}; {}]", render_type(type_), len),
        rustdoc::Type::BorrowedRef { lifetime, is_mutable, type_ } => format!("&{}{} {}", lifetime.as_deref().map(|value| format!("{value} ")).unwrap_or_default(), if *is_mutable { "mut" } else { "" }, render_type(type_)),
        rustdoc::Type::DynTrait(trait_) => format!(
            "dyn {}{}",
            trait_.traits.iter().map(|bound| bound.trait_.path.as_str()).collect::<Vec<_>>().join(" + "),
            trait_.lifetime.as_deref().map(|lifetime| format!(" + {lifetime}")).unwrap_or_default()
        ),
        rustdoc::Type::FunctionPointer(function) => render_function_pointer(function),
        rustdoc::Type::Generic(value) | rustdoc::Type::Primitive(value) => value.clone(),
        rustdoc::Type::ImplTrait(bounds) => format!("impl {}", bounds.iter().map(render_bound).collect::<Vec<_>>().join(" + ")),
        rustdoc::Type::Infer => "_".to_string(),
        rustdoc::Type::Pat { type_, .. } => render_type(type_),
        rustdoc::Type::QualifiedPath { name, self_type, .. } => format!("{}::{}", render_type(self_type), name),
        rustdoc::Type::RawPointer { is_mutable, type_ } => format!("*{} {}", if *is_mutable { "mut" } else { "const" }, render_type(type_)),
        rustdoc::Type::ResolvedPath(path) => {
            format!("{}{}", path.path, path.args.as_deref().map(render_args).unwrap_or_default())
        }
        rustdoc::Type::Slice(value) => format!("[{}]", render_type(value)),
        rustdoc::Type::Tuple(values) => format!("({})", values.iter().map(render_type).collect::<Vec<_>>().join(", ")),
    }
}

fn render_function_pointer(function: &rustdoc::FunctionPointer) -> String {
    let mut output = String::from("fn(");
    output.push_str(&function.sig.inputs.iter().map(|(_, type_)| render_type(type_)).collect::<Vec<_>>().join(", "));
    output.push(')');
    if let Some(output_type) = &function.sig.output {
        output.push_str(" -> ");
        output.push_str(&render_type(output_type));
    }
    output
}

fn render_args(args: &rustdoc::GenericArgs) -> String {
    match args {
        rustdoc::GenericArgs::AngleBracketed { args, constraints } => {
            let mut values = args.iter().map(render_arg).collect::<Vec<_>>();
            values.extend(constraints.iter().map(|constraint| constraint.name.clone()));
            format!("<{}>", values.join(", "))
        }
        rustdoc::GenericArgs::Parenthesized { inputs, output } => {
            let mut value = format!("({})", inputs.iter().map(render_type).collect::<Vec<_>>().join(", "));
            if let Some(output) = output {
                value.push_str(" -> ");
                value.push_str(&render_type(output));
            }
            value
        }
        rustdoc::GenericArgs::ReturnTypeNotation => "(..)".to_string(),
    }
}

fn render_arg(arg: &rustdoc::GenericArg) -> String {
    match arg {
        rustdoc::GenericArg::Const(value) => value.expr.clone(),
        rustdoc::GenericArg::Infer => "_".to_string(),
        rustdoc::GenericArg::Lifetime(value) => value.clone(),
        rustdoc::GenericArg::Type(value) => render_type(value),
    }
}

fn lower_visibility(visibility: &rustdoc::Visibility) -> Visibility {
    match visibility {
        rustdoc::Visibility::Crate => Visibility::Restricted("crate".to_string()),
        rustdoc::Visibility::Default => Visibility::Private,
        rustdoc::Visibility::Public => Visibility::Public,
        rustdoc::Visibility::Restricted { path, .. } => Visibility::Restricted(path.clone()),
    }
}

fn is_public_or_api_child(
    visibility: &rustdoc::Visibility,
    kind: rustdoc::ItemKind,
    parent_kind: Option<&DeclarationKind>,
) -> bool {
    if matches!(visibility, rustdoc::Visibility::Public) {
        return true;
    }
    matches!(
        (kind, parent_kind),
        (rustdoc::ItemKind::AssocConst, Some(DeclarationKind::Trait))
                | (rustdoc::ItemKind::AssocType, Some(DeclarationKind::Trait))
                | (rustdoc::ItemKind::Function, Some(DeclarationKind::Trait))
                | (rustdoc::ItemKind::StructField, Some(DeclarationKind::Struct | DeclarationKind::Union | DeclarationKind::Variant))
                | (rustdoc::ItemKind::Variant, Some(DeclarationKind::Enum))
    )
}

fn parent_name(qualified_name: &str) -> Option<String> {
    qualified_name.rsplit_once("::").map(|(parent, _)| parent.to_string())
}

fn attribute_key(attribute: &rustdoc::Attribute) -> String {
    match attribute {
        rustdoc::Attribute::AutomaticallyDerived => "automatically_derived".to_string(),
        rustdoc::Attribute::ExportName(_) => "export_name".to_string(),
        rustdoc::Attribute::LinkSection(_) => "link_section".to_string(),
        rustdoc::Attribute::MacroExport => "macro_export".to_string(),
        rustdoc::Attribute::MustUse { .. } => "must_use".to_string(),
        rustdoc::Attribute::NoMangle => "no_mangle".to_string(),
        rustdoc::Attribute::NonExhaustive => "non_exhaustive".to_string(),
        rustdoc::Attribute::Other(value) => value.trim_start_matches('#').to_string(),
        rustdoc::Attribute::Repr(_) => "repr".to_string(),
        rustdoc::Attribute::TargetFeature { .. } => "target_feature".to_string(),
    }
}

fn format_item_kind(kind: rustdoc::ItemKind) -> &'static str {
    match kind {
        rustdoc::ItemKind::AssocConst => "associated-constant",
        rustdoc::ItemKind::AssocType => "associated-type",
        rustdoc::ItemKind::Constant => "constant",
        rustdoc::ItemKind::Enum => "enum",
        rustdoc::ItemKind::Function => "function",
        rustdoc::ItemKind::Impl => "impl",
        rustdoc::ItemKind::Macro => "macro",
        rustdoc::ItemKind::Module => "module",
        rustdoc::ItemKind::Static => "static",
        rustdoc::ItemKind::Struct => "struct",
        rustdoc::ItemKind::Trait => "trait",
        rustdoc::ItemKind::TypeAlias => "type",
        rustdoc::ItemKind::Union => "union",
        rustdoc::ItemKind::Variant => "variant",
        _ => "item",
    }
}

fn position((line, column): (usize, usize), bytes: &[u8]) -> SourcePosition {
    let mut current_line = 1usize;
    let mut line_start = 0usize;
    for (index, byte) in bytes.iter().enumerate() {
        if current_line == line {
            break;
        }
        if *byte == b'\n' {
            current_line += 1;
            line_start = index + 1;
        }
    }
    SourcePosition {
        byte: line_start + column.saturating_sub(1),
        line,
        column: column.saturating_sub(1),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_requests_without_an_explicit_json_path() {
        let request = SourceAnalysisRequest::new("target");
        let error = RustdocJsonAnalyzer::default().analyze(&request).unwrap_err();
        assert!(error.to_string().contains("no rustdoc JSON path supplied"));
    }

    #[test]
    fn cache_identity_includes_rustdoc_schema_and_hashed_toolchain() {
        let request = SourceAnalysisRequest::new("fixture");
        let toolchain = RustdocJsonAnalyzer::new(Some("rustc-private-path".into()));
        let changed_toolchain = RustdocJsonAnalyzer::new(Some("rustc-other".into()));
        let unspecified_toolchain = RustdocJsonAnalyzer::default();
        let identity = toolchain.cache_identity(&request);

        assert!(identity.contains(BACKEND_VERSION));
        assert!(identity.contains(&format!("format-{}", rustdoc::FORMAT_VERSION)));
        assert!(!identity.contains("rustc-private-path"));
        assert_ne!(identity, changed_toolchain.cache_identity(&request));
        assert_ne!(identity, unspecified_toolchain.cache_identity(&request));
    }

    #[test]
    fn positions_convert_one_based_rustdoc_columns() {
        let value = b"one\ntwo\n";
        let position = position((2, 2), value);
        assert_eq!(position.byte, 5);
        assert_eq!(position.line, 2);
        assert_eq!(position.column, 1);
    }

    #[test]
    fn type_renderer_preserves_common_rust_forms() {
        let value = rustdoc::Type::BorrowedRef {
            lifetime: Some("'a".to_string()),
            is_mutable: true,
            type_: Box::new(rustdoc::Type::Primitive("str".to_string())),
        };
        assert_eq!(render_type(&value), "&'a mut str");

        let tuple = rustdoc::Type::Tuple(vec![
            rustdoc::Type::Primitive("u8".to_string()),
            rustdoc::Type::Infer,
        ]);
        assert_eq!(render_type(&tuple), "(u8, _)");
    }

    #[test]
    fn fixture_json_lowers_api_metadata_and_reexports_deterministically() {
        let fixture_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/h14/rust");
        let json_path = fixture_root.parent().unwrap().join("rustdoc.json");
        let bytes = fs::read(&json_path).unwrap();
        let request = SourceAnalysisRequest::new(&fixture_root);
        let analyzer = RustdocJsonAnalyzer::new(Some("fixture-toolchain".to_string()));
        let first = analyzer.analyze_json_bytes(&request, &json_path, &bytes).unwrap();
        let second = analyzer.analyze_json_bytes(&request, &json_path, &bytes).unwrap();
        assert_eq!(first.declarations, second.declarations);
        assert_eq!(first.toolchain.as_deref(), Some("fixture-toolchain"));

        let component = first
            .declarations
            .iter()
            .find(|declaration| declaration.qualified_name == "fixture::api::Component")
            .unwrap();
        assert_eq!(component.aliases, vec!["fixture::PublicComponent"]);
        assert!(!component.children.is_empty());
        assert!(first
            .declarations
            .iter()
            .any(|declaration| declaration.qualified_name == "fixture::api::Component::value"));

        let answer = first
            .declarations
            .iter()
            .find(|declaration| declaration.qualified_name == "fixture::api::answer")
            .unwrap();
        assert_eq!(answer.signature.as_deref(), Some("fn<T>(value: T) -> T"));
        assert_eq!(answer.documentation, "Return the answer.");
        assert_eq!(answer.attributes.get("doc-link:Component").map(String::as_str), Some("2"));
        assert_eq!(answer.source.path, "src/api.rs");
        assert_eq!(answer.source.start.line, 9);

        let hidden = first
            .declarations
            .iter()
            .find(|declaration| declaration.qualified_name == "fixture::hidden_item")
            .unwrap();
        assert!(hidden.noindex);
        assert!(first
            .declarations
            .iter()
            .all(|declaration| declaration.qualified_name != "fixture::private_item"));

        let mut include_private = request.clone();
        include_private.include_private = true;
        let private_snapshot = analyzer
            .analyze_json_bytes(&include_private, &json_path, &bytes)
            .unwrap();
        assert!(private_snapshot
            .declarations
            .iter()
            .any(|declaration| declaration.qualified_name == "fixture::private_item"));
        assert!(first
            .declarations
            .iter()
            .find(|declaration| declaration.qualified_name == "fixture::old_answer")
            .is_some_and(|declaration| declaration.deprecated));
    }

    #[test]
    fn rejects_fixture_with_an_unsupported_format_version() {
        let fixture_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/h14/rust");
        let json_path = fixture_root.parent().unwrap().join("rustdoc.json");
        let bytes = fs::read_to_string(&json_path)
            .unwrap()
            .replace("\"format_version\": 61", "\"format_version\": 60");
        let error = RustdocJsonAnalyzer::default()
            .analyze_json_bytes(
                &SourceAnalysisRequest::new(&fixture_root),
                &json_path,
                bytes.as_bytes(),
            )
            .unwrap_err();
        assert!(matches!(error, AnalysisError::BackendUnavailable { .. }));
        assert!(error.to_string().contains("expects 61"));
    }
}