//! [`Markup`] — the safe-HTML newtype.
//!
//! Mirrors `markupsafe.Markup` from the Python package.

use std::fmt;
use std::ops::{Add, AddAssign, Deref};

use serde::{Deserialize, Serialize};

use crate::escape::{escape_to, html_escape_char};

/// A string that is known to be safe HTML/XML markup.
///
/// Creating a `Markup` value implies that the contents have already been
/// escaped or were generated by trusted code and do not require escaping.
///
/// # Construction
///
/// | Method | Behaviour |
/// |--------|-----------|
/// | [`Markup::from_safe`] | Wraps an already-safe string **without** escaping. |
/// | [`Markup::escape`] | Escapes the input and wraps the result. |
/// | [`escape`](crate::escape::escape) | Free-function alias for `Markup::escape`. |
///
/// # Python compatibility
///
/// `Markup` mirrors the Python `markupsafe.Markup` class:
/// - `Markup(s)` → `Markup::escape(s)` (escape on construction from `str`).
/// - `Markup.__html__()` → `Markup::into_string` / `Deref` to `str`.
/// - `Markup + str` → `Markup::add(&str)` (escapes the `str` operand).
/// - `Markup.format(…)` → not directly available; use `MarkupEscape` trait.
/// - `Markup.unescape()` → [`Markup::unescape`].
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Default, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Markup(String);

impl Markup {
    /// Wrap an already-safe string without any escaping.
    ///
    /// The caller is responsible for ensuring `s` contains only safe HTML.
    /// Using this with untrusted input is a security vulnerability.
    #[inline]
    pub fn from_safe(s: impl Into<String>) -> Self {
        Markup(s.into())
    }

    /// Escape `s` and return the safe result.
    ///
    /// Equivalent to `markupsafe.Markup.escape(s)` in Python.
    ///
    /// ```rust
    /// use markupsafers::Markup;
    /// let m = Markup::escape("<b>bold & bright</b>");
    /// assert_eq!(m.as_str(), "&lt;b&gt;bold &amp; bright&lt;/b&gt;");
    /// ```
    #[inline]
    pub fn escape(s: &str) -> Self {
        let mut out = String::with_capacity(s.len() + 16);
        escape_to(s, &mut out);
        Markup(out)
    }

    /// Return a reference to the inner safe string.
    #[inline]
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Consume and return the inner safe string.
    #[inline]
    pub fn into_string(self) -> String {
        self.0
    }

    /// Reverse escaping: replace HTML entities with their literal characters.
    ///
    /// Mirrors `Markup.unescape()` in Python.
    ///
    /// Only the five entities produced by [`escape`](crate::escape::escape) are
    /// reversed: `&amp;`, `&lt;`, `&gt;`, `&#34;`/`&quot;`, `&#39;`/`&apos;`.
    ///
    /// ```rust
    /// use markupsafers::Markup;
    /// let m = Markup::from_safe("&lt;b&gt;bold&lt;/b&gt;");
    /// assert_eq!(m.unescape(), "<b>bold</b>");
    /// ```
    pub fn unescape(&self) -> String {
        let s = &self.0;
        let mut out = String::with_capacity(s.len());
        let mut rest = s.as_str();
        while let Some(amp) = rest.find('&') {
            out.push_str(&rest[..amp]);
            let tail = &rest[amp..];
            if let Some(stripped) = tail.strip_prefix("&amp;") {
                out.push('&');
                rest = stripped;
            } else if let Some(stripped) = tail.strip_prefix("&lt;") {
                out.push('<');
                rest = stripped;
            } else if let Some(stripped) = tail.strip_prefix("&gt;") {
                out.push('>');
                rest = stripped;
            } else if let Some(stripped) = tail.strip_prefix("&#34;") {
                out.push('"');
                rest = stripped;
            } else if let Some(stripped) = tail.strip_prefix("&quot;") {
                out.push('"');
                rest = stripped;
            } else if let Some(stripped) = tail.strip_prefix("&#39;") {
                out.push('\'');
                rest = stripped;
            } else if let Some(stripped) = tail.strip_prefix("&apos;") {
                out.push('\'');
                rest = stripped;
            } else {
                out.push('&');
                rest = &tail[1..];
            }
        }
        out.push_str(rest);
        out
    }

    /// Return `true` if this markup is empty.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// Return the length in bytes of the underlying string.
    #[inline]
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Concatenate with another `Markup` value (both are already safe).
    #[inline]
    pub fn concat(mut self, other: &Markup) -> Self {
        self.0.push_str(&other.0);
        self
    }

    /// Append an escaped version of `s` to this markup.
    ///
    /// Mirrors the behaviour of Python `Markup.__add__` when the right-hand
    /// operand is a plain string.
    pub fn push_escaped(&mut self, s: &str) {
        escape_to(s, &mut self.0);
    }

    /// Return a `Markup` holding a joined sequence of items.
    ///
    /// Each item is formatted with `{item}` (via `Display`) and then escaped
    /// **unless** it already implements `__html__` (i.e. is itself a `Markup`).
    ///
    /// Mirrors `Markup.join(iterable)` in Python.
    ///
    /// ```rust
    /// use markupsafers::Markup;
    /// let sep = Markup::from_safe(", ");
    /// let result = sep.join(["<a>", "<b>", "<c>"]);
    /// assert_eq!(result.as_str(), "&lt;a&gt;, &lt;b&gt;, &lt;c&gt;");
    /// ```
    pub fn join<I, S>(&self, items: I) -> Markup
    where
        I: IntoIterator<Item = S>,
        S: fmt::Display,
    {
        let mut out = String::new();
        let sep = &self.0;
        let mut first = true;
        for item in items {
            if !first {
                out.push_str(sep);
            }
            first = false;
            escape_to(&item.to_string(), &mut out);
        }
        Markup(out)
    }

    /// Join pre-escaped `Markup` items (no additional escaping).
    pub fn join_markup<I>(&self, items: I) -> Markup
    where
        I: IntoIterator<Item = Markup>,
    {
        let sep = &self.0;
        let parts: Vec<_> = items.into_iter().collect();
        let mut out = String::with_capacity(
            parts.iter().map(|m| m.len()).sum::<usize>()
                + sep.len() * parts.len().saturating_sub(1),
        );
        for (i, item) in parts.into_iter().enumerate() {
            if i > 0 {
                out.push_str(sep);
            }
            out.push_str(&item.0);
        }
        Markup(out)
    }

    /// Wrap text in a `Markup` by applying a printf/format-style operation.
    ///
    /// All positional format arguments are escaped before substitution.
    /// Named arguments are escaped as well. The format string itself is
    /// assumed to be trusted (it is part of the template, not user data).
    ///
    /// ```rust
    /// use markupsafers::Markup;
    /// let tmpl = Markup::from_safe("<em>{}</em>");
    /// let result = tmpl.format_args(&["<script>alert(1)</script>"]);
    /// assert_eq!(result.as_str(), "<em>&lt;script&gt;alert(1)&lt;/script&gt;</em>");
    /// ```
    pub fn format_args(&self, args: &[&str]) -> Markup {
        let mut out = String::with_capacity(self.0.len());
        let mut rest = self.0.as_str();
        let mut arg_idx = 0;
        while let Some(open) = rest.find('{') {
            out.push_str(&rest[..open]);
            if rest[open..].starts_with("{{") {
                out.push('{');
                rest = &rest[open + 2..];
                continue;
            }
            if let Some(close) = rest[open..].find('}') {
                let placeholder = &rest[open + 1..open + close];
                rest = &rest[open + close + 1..];
                if placeholder.is_empty() {
                    // positional argument
                    if let Some(&arg) = args.get(arg_idx) {
                        escape_to(arg, &mut out);
                        arg_idx += 1;
                    }
                } else if let Ok(n) = placeholder.parse::<usize>() {
                    if let Some(&arg) = args.get(n) {
                        escape_to(arg, &mut out);
                    }
                } else {
                    // keep unknown placeholders as-is
                    out.push('{');
                    out.push_str(placeholder);
                    out.push('}');
                }
            } else {
                // no matching '}' — treat as literal
                out.push_str(&rest[open..]);
                rest = "";
                break;
            }
        }
        // handle closing `}}` → `}`
        let mut rem = rest;
        while let Some(p) = rem.find("}}") {
            out.push_str(&rem[..p]);
            out.push('}');
            rem = &rem[p + 2..];
        }
        out.push_str(rem);
        Markup(out)
    }
}

// ── Deref / AsRef ─────────────────────────────────────────────────────────────

impl Deref for Markup {
    type Target = str;
    #[inline]
    fn deref(&self) -> &str {
        &self.0
    }
}

impl AsRef<str> for Markup {
    #[inline]
    fn as_ref(&self) -> &str {
        &self.0
    }
}

// ── Display / Debug ───────────────────────────────────────────────────────────

impl fmt::Display for Markup {
    #[inline]
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl fmt::Debug for Markup {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Markup({:?})", self.0)
    }
}

// ── Concatenation ─────────────────────────────────────────────────────────────

/// `Markup + Markup` — both sides are already safe.
impl Add<Markup> for Markup {
    type Output = Markup;
    fn add(mut self, rhs: Markup) -> Markup {
        self.0.push_str(&rhs.0);
        self
    }
}

/// `Markup + &Markup` — right side is already safe.
impl Add<&Markup> for Markup {
    type Output = Markup;
    fn add(mut self, rhs: &Markup) -> Markup {
        self.0.push_str(&rhs.0);
        self
    }
}

/// `Markup + &str` — escape the plain string before appending.
impl Add<&str> for Markup {
    type Output = Markup;
    fn add(mut self, rhs: &str) -> Markup {
        escape_to(rhs, &mut self.0);
        self
    }
}

/// `Markup + String` — escape the plain string before appending.
impl Add<String> for Markup {
    type Output = Markup;
    fn add(mut self, rhs: String) -> Markup {
        escape_to(&rhs, &mut self.0);
        self
    }
}

/// `Markup += Markup` — already safe.
impl AddAssign<Markup> for Markup {
    fn add_assign(&mut self, rhs: Markup) {
        self.0.push_str(&rhs.0);
    }
}

/// `Markup += &str` — escape and append.
impl AddAssign<&str> for Markup {
    fn add_assign(&mut self, rhs: &str) {
        escape_to(rhs, &mut self.0);
    }
}

// ── Conversions ───────────────────────────────────────────────────────────────

impl From<Markup> for String {
    #[inline]
    fn from(m: Markup) -> String {
        m.0
    }
}

impl From<String> for Markup {
    /// Escape the string and wrap it as `Markup`.
    ///
    /// Matches Python `Markup(str)` constructor behaviour.
    #[inline]
    fn from(s: String) -> Markup {
        Markup::escape(&s)
    }
}

impl From<&str> for Markup {
    /// Escape the string slice and wrap it as `Markup`.
    #[inline]
    fn from(s: &str) -> Markup {
        Markup::escape(s)
    }
}

// ── Helper for escape module ──────────────────────────────────────────────────

/// Escape a single character to its HTML entity, if required.
///
/// Returns `None` when the character needs no escaping.
#[inline]
#[allow(dead_code)]
pub(crate) fn escape_char_lookup(c: char) -> Option<&'static str> {
    html_escape_char(c)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn from_safe_is_not_escaped() {
        let m = Markup::from_safe("<b>bold</b>");
        assert_eq!(m.as_str(), "<b>bold</b>");
    }

    #[test]
    fn escape_escapes_special_chars() {
        let m = Markup::escape("< > & \" '");
        assert_eq!(m.as_str(), "&lt; &gt; &amp; &#34; &#39;");
    }

    #[test]
    fn unescape_round_trips() {
        let original = "<b>bold & \"quoted\"</b>";
        let m = Markup::escape(original);
        assert_eq!(m.unescape(), original);
    }

    #[test]
    fn add_str_escapes() {
        let m = Markup::from_safe("<b>") + "<script>";
        assert_eq!(m.as_str(), "<b>&lt;script&gt;");
    }

    #[test]
    fn add_markup_does_not_escape() {
        let a = Markup::from_safe("<b>");
        let b = Markup::from_safe("</b>");
        let c = a + b;
        assert_eq!(c.as_str(), "<b></b>");
    }

    #[test]
    fn join_escapes_plain_strings() {
        let sep = Markup::from_safe(", ");
        let result = sep.join(["<a>", "<b>"]);
        assert_eq!(result.as_str(), "&lt;a&gt;, &lt;b&gt;");
    }

    #[test]
    fn join_markup_no_escaping() {
        let sep = Markup::from_safe(", ");
        let result = sep.join_markup([Markup::from_safe("<a>"), Markup::from_safe("<b>")]);
        assert_eq!(result.as_str(), "<a>, <b>");
    }

    #[test]
    fn format_args_escapes_positional() {
        let tmpl = Markup::from_safe("<em>{}</em>");
        let r = tmpl.format_args(&["<script>"]);
        assert_eq!(r.as_str(), "<em>&lt;script&gt;</em>");
    }

    #[test]
    fn serde_round_trip() {
        let m = Markup::from_safe("<b>ok</b>");
        let json = serde_json::to_string(&m).unwrap();
        assert_eq!(json, r#""<b>ok</b>""#);
        let back: Markup = serde_json::from_str(&json).unwrap();
        assert_eq!(back.as_str(), "<b>ok</b>");
    }
}
