name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    env:
      CARGO_NET_RETRY: 10
      #CARGO_HTTP_MULTIPLEXING: "false"
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: "true"
    defaults:
      run:
        working-directory: src
    steps:
      - run: git config --global core.checkRoundtrip false
        working-directory: .
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      # - uses: dtolnay/rust-toolchain@nightly
      #   with:
      #     components: rustfmt, clippy
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - uses: mozilla-actions/sccache-action@v0.0.10
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src

      - run: python -m pip install sphinx pygments

      #- run: cargo +nightly fmt --all --check

      # - run: cargo fmt --all --check
      #   working-directory: src/docutilsrs
      # - run: cargo fmt --all --check
      #   working-directory: src/jinja2rs
      # - run: cargo fmt --all --check
      #   working-directory: src/markupsafers
      # - run: cargo fmt --all --check
      #   working-directory: src/mathrenderrs
      # #- run: cargo fmt --all --check
      # #  working-directory: src/minijinja
      # - run: cargo fmt --all --check
      #   working-directory: src/myst-md-rs
      # #- run: cargo fmt --all --check
      # #  working-directory: src/pulldown-cmark
      # - run: cargo fmt --all --check
      #   working-directory: src/pygmentsrs
      # # - run: cargo fmt --all --check
      # #   working-directory: src/RaTeX
      # - run: cargo fmt --all --check
      #   working-directory: src/sphinxdocrs

      - run: cargo clippy --workspace --all-targets -- -D warnings
      - run: cargo test --workspace --all-targets
      - run: cargo test --workspace --doc

  python:
    runs-on: ubuntu-latest
    env:
      CARGO_NET_RETRY: 10
      #CARGO_HTTP_MULTIPLEXING: "false"
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: "true"
    defaults:
      run:
        working-directory: src
    steps:
      - run: git config --global core.checkRoundtrip false
        working-directory: .
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - uses: mozilla-actions/sccache-action@v0.0.10
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src
      - run: python -m venv .venv
      - run: ${{ github.workspace }}/src/.venv/bin/python -m pip install maturin pytest pytest-cov
      #- run: ${{ github.workspace }}/src/.venv/bin/python -m pip install -r requirements.txt
      - name: maturin develop pygmentsrs
        run: ${{ github.workspace }}/src/.venv/bin/maturin develop --profile release-fast
        working-directory: src/pygmentsrs
      - name: maturin develop docutilsrs
        run: ${{ github.workspace }}/src/.venv/bin/maturin develop --profile release-fast
        working-directory: src/docutilsrs
      - name: maturin develop ratex-py
        run: ${{ github.workspace }}/src/.venv/bin/maturin develop --profile release
        working-directory: src/RaTeX/crates/ratex-py
      - name: maturin develop myst-md-rs
        run: ${{ github.workspace }}/src/.venv/bin/maturin develop --profile release-fast
        working-directory: src/myst-md-rs
      - name: maturin develop markupsafers
        run: ${{ github.workspace }}/src/.venv/bin/maturin develop --profile release-fast
        working-directory: src/markupsafers
      - name: maturin develop jinja2rs
        run: ${{ github.workspace }}/src/.venv/bin/maturin develop --profile release-fast
        working-directory: src/jinja2rs
      - name: maturin develop mathrenderrs
        run: ${{ github.workspace }}/src/.venv/bin/maturin develop --profile release-fast
        working-directory: src/mathrenderrs
      - name: maturin develop sphinxdocrs
        run: ${{ github.workspace }}/src/.venv/bin/maturin develop --profile release-fast
        working-directory: src/sphinxdocrs
      - run: >-
          ${{ github.workspace }}/src/.venv/bin/pytest -v -l tests/ 
          --cov=. --cov-branch --cov-report=xml:cov.xml
          --junitxml=pytest-results.xml tests/
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: python-test-artifacts
          path: |
            ${{ github.workspace }}/src/cov.xml
            ${{ github.workspace }}/src/pytest-results.xml