#!/usr/bin/env python3
"""Generate optimized phf::Map-based lexer registry from current match statement."""

import re
from pathlib import Path

REGISTRY_PATH = Path(__file__).parent.parent / "pygmentsrs" / "src" / "lexers" / "registry.rs"


def parse_registry() -> dict[str, str]:
    """Extract all alias -> lexer mappings from current registry.rs"""
    content = REGISTRY_PATH.read_text()
    
    # Find the match arms section
    match_start = content.find('match alias {')
    match_end = content.find('_ => None,')
    if match_start == -1 or match_end == -1:
        raise ValueError("Could not parse registry.rs structure")
    
    match_body = content[match_start + 13 : match_end]
    
    mappings: dict[str, str] = {}
    # Match lines like: `"alias1" | "alias2" => Some(Box::new(SomeLexer)),`
    pattern = re.compile(r'"([^"]+)"\s*(?:\|\s*"[^"]+")* => Some\(Box::new\(([^)]+)\)\)')
    
    for line in match_body.split('\n'):
        line = line.strip()
        if not line or line.startswith('//'):
            continue
        
        # Extract all aliases from this line
        aliases_match = re.findall(r'"([^"]+)"', line)
        lexer_match = re.search(r'Box::new\(([^)]+)\)', line)
        
        if aliases_match and lexer_match:
            lexer = lexer_match.group(1)
            for alias in aliases_match:
                mappings[alias] = lexer
    
    return mappings


def generate_phf_registry(mappings: dict[str, str]) -> str:
    """Generate phf::Map-based registry code"""
    
    # Type definition for lexer constructor
    type_def = '''type LexerConstructor = fn() -> Box<dyn Lexer>;

// Compile-time perfect hash function (generated by phf macro)
// O(1) lookup with zero runtime overhead
static LEXER_MAP: phf::Map<&'static str, LexerConstructor> = phf_map! {
'''
    
    # Generate phf_map entries (must be sorted for deterministic output)
    entries = []
    for alias in sorted(mappings.keys()):
        lexer = mappings[alias]
        # Create a closure that constructs the lexer
        entries.append(f'    "{alias}" => || Box::new({lexer}),')
    
    body = '\n'.join(entries)
    footer = '};'
    
    # The main function is now just a lookup
    get_fn = '''
pub fn get_lexer_by_name(alias: &str) -> Option<Box<dyn Lexer>> {
    LEXER_MAP.get(alias).map(|ctor| ctor())
}
'''
    
    return type_def + '\n' + body + '\n' + footer + get_fn


def main():
    import sys
    
    # Check if we're being called with --generate-code flag
    generate_code = "--generate-code" in sys.argv
    
    print("Parsing current registry.rs...", file=sys.stderr)
    mappings = parse_registry()
    print(f"Found {len(mappings)} lexer alias mappings", file=sys.stderr)
    
    print("Generating optimized phf-based registry...", file=sys.stderr)
    phf_code = generate_phf_registry(mappings)
    
    if generate_code:
        # Output the actual code to stdout
        print(phf_code)
    else:
        # Print a sample
        print("\nSample output (first 20 lines):", file=sys.stderr)
        print('\n'.join(phf_code.split('\n')[:20]), file=sys.stderr)
        print("...", file=sys.stderr)
        print(f"\nTotal lines: {len(phf_code.split(chr(10)))}", file=sys.stderr)
        print("\nThis will give you:", file=sys.stderr)
        print("  ✓ O(1) lookup instead of O(n)", file=sys.stderr)
        print("  ✓ Compile-time perfect hashing", file=sys.stderr)
        print("  ✓ Zero runtime initialization cost", file=sys.stderr)
        print("  ✓ Smaller code size", file=sys.stderr)
        print("  ✓ Deterministic performance", file=sys.stderr)


if __name__ == "__main__":
    main()
